### ISSUE TITLE
Scale Inputfield duplication 🐛 

### ISSUE THREAD

**Issue by MrChaosXx** [telekom/scale#1001]
Hey together, 

in my webapp I am using the scale inputfield and when I am routing around with the vue router some of my inputfields duplicate.
![image](https://user-images.githubusercontent.com/90321106/164221726-640b9f09-a9be-4de3-9d43-8834d30df6ac.png)
3x routing result in:
![image](https://user-images.githubusercontent.com/90321106/164221798-25107f7e-2472-4dd6-8091-7231ab91f19a.png)

The strange thing is, that I don´t have the problem in other views, just in one. Here is one short code snippet:
```
<template>
    <div id="mailarchiv" style="min-width:1105px">
        <div class="container-fluid">
            <h1 style="text-align: center">Mailarchiv</h1>
            <div class="mailFilter ">
                <div v-if="displayFilter" class="d-grid gap-4 m-3">            
                    <div class="row justify-content">
                        <div class="archivName col-2">
                            <scale-text-field label="Archivname" placeholder="Name" size="small"></scale-text-field>
                        </div>
                        <div class="templateName col-2">
                            <scale-text-field label="Template" placeholder="Name" size="small"></scale-text-field>
                        </div>
                        <div class="date col-2">
                            <scale-text-field label="Datum" placeholder="Name" size="small"></scale-text-field>
                        </div>                    
                    </div>
                    <div class="row justify-content" style="display: flex">
                        <div class="customerNumber col-2">
                           <scale-text-field label="Kundennummer" placeholder="Name" size="small"></scale-text-field>
                        </div>
                        <div class="contractNumber col-2">
                            <scale-text-field label="Vertrags-Nr." placeholder="Name" size="small"></scale-text-field>
                        </div>
                        <div class="salesNumber col-2">
                            <scale-text-field label="Vertriebs-Nr." placeholder="Name" size="small"></scale-text-field>
                        </div>
                            <div class="orderNumber col-2">
                            <scale-text-field label="Auftrags-ID" placeholder="Name" size="small"></scale-text-field>
                        </div>
                    </div>
                </div>
...
</template>
```

One time I also used the scale checkbox in the same view and they also duplicated.

Do you know what the problem could be? Is it maybe something in my code?
If you need some more details, just send me a message :)

greetings
Paul

**Comment by felix-ico** [comment]
Hi @MrChaosXx, thanks for reporting the issue. The code snippet looks fine to me,  would it be possible for you to create a code sandbox that shows this bug in action?

**Comment by MrChaosXx** [comment]
Hi @felix-ico,
sorry for the late reply. At the moment I am very busy at work and with my studies. I will try to set up a project for you next week.
I hope that this is not too late.

**Comment by MrChaosXx** [comment]
Hi @felix-ico,

I added you to an repository with a test project. There you can route around and see the duplication bug.
Please excuse the long wait!

**Comment by felix-ico** [comment]
@MrChaosXx I pushed a fix to your repo, I am still investigating why the vue.config.js is not working properly but the on-the-fly template compilation

```
const app = Vue.createApp({});
app.config.compilerOptions.isCustomElement = (tag) => tag.startsWith('scale-');
```

seems to work

**Comment by MrChaosXx** [comment]
Nice thank you :) 👍🏼

**Comment by acstll** [comment]
Looks like this one is fixed. Please re-open if not @MrChaosXx 🙏
