### ISSUE TITLE
scale-app-header rendering bug 🐛 

### ISSUE THREAD

**Issue by MrChaosXx** [telekom/scale#1002]
Hello together,

I found a rendering bug from the scale-app-header.
At a width of 1023px the header renders over the whole page:
![image](https://user-images.githubusercontent.com/90321106/164224019-6bbff2ea-53bd-4b97-bd22-73bfe9709435.png)

I also saw the bug on other websites, which are using the scale header.

best regards
Paul

**Comment by nowseemee** [comment]
Hi Paul, thanks for opening this question. It looks like the library is not initialized. Are you sure it's [properly](https://github.com/telekom/scale#setup-with-a-bundler-or-es-modules) set up? If yes, could you please provide a code sandbox example reproduction of the bug? Thanks!

**Comment by MrChaosXx** [comment]
Hi @nowseemee ,
sorry for the late reply. At the moment I am very busy at work and with my studies. I will try to set up a project for you next week.
I hope that this is not too late.

**Comment by nowseemee** [comment]
hi, @MrChaosXx thanks a lot for the repo - I'll take a look and get back to you.

**Comment by nowseemee** [comment]
hey Paul, could you share the repo again? Thanks!

**Comment by MrChaosXx** [comment]
Is out :)

**Comment by acstll** [comment]
This seems to be fixed (tested with the latest version).

What did you exactly mean with "is out" 🤓? @MrChaosXx

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/851105/176741282-b5addd5b-9732-41ed-888d-364acf690aa8.png">

**Comment by acstll** [comment]
Closing this assuming it's all good, please re-open or get in touch if not. Thanks again for your feedback @MrChaosXx 💜
