### ISSUE TITLE
Scale-button disappearing attributes

### ISSUE THREAD

**Issue by reed665** [telekom/scale#1011]
Hi! We have a strange issue connected to scale-button in several projects

![image](https://user-images.githubusercontent.com/4117678/165061357-7187d9fa-90d0-4ee9-b0eb-c1ab93dae158.png)

It looks like some scale-button attributes like variant="secondary" are missing except the button in the first item of the list

we use button with an icon inside the list like this
```vue
<ul>
  <li v-for="item of list" :key="item.id">
    <scale-button
        type="button"
        variant="secondary"
        icon-only
        @click="handleClick(item)"
      >
        <scale-icon-action-edit
          accessibility-title="edit"
          size="16"
        />
    </scale-button>
  </li>
</ul>
```

This issue never appears when developing locally using webpack-dev-server but after build and deploy to the server we can see it pretty often

We use vue 3 and and latest version of scale
```json
"dependencies": {
  "@telekom/scale-components": "^3.0.0-beta.102",
  "vue": "^3.0.0",
  ...
}
```

we connect scale in index.html like this
```html
<link
    rel="stylesheet"
    href="<%= BASE_URL %>scale-components/scale-components.css"
  />
...
<script
  type="module"
  src="<%= BASE_URL %>scale-components/scale-components.esm.js"
></script>
```

Do you guys have any ideas why we are facing such an issue on a built and deployed app and never when developing locally? Not 100% sure if this is a scale issue but struggling to find a reason and solution/workaround

**Comment by felix-ico** [comment]
Hi @reed665, thanks for reporting this. I can not give you an answer right away but I will try to reproduce the bug and see if we can find a cause and solution to this.

**Comment by felix-ico** [comment]
Hi @reed665, I tried to reproduce this issue but unfortunately I was unsuccessful. My Vue apps get built correctly and shows no difference between dev and prod. 

The only thing different in my app is that I import scale from node_modules while you mentioned that: 

> we connect scale in index.html like this
> 
> <link
>     rel="stylesheet"
>     href="<%= BASE_URL %>scale-components/scale-components.css"
>   />
> ...
> <script
>   type="module"
>   src="<%= BASE_URL %>scale-components/scale-components.esm.js"
> ></script>
> 

Just from seeing the code I would not expect it to work like that, but evidently it seems to work for you (at least scale components render). I would import scale as documented here https://www.brand-design.telekom.com/scale/?path=/docs/setup-info-scale-and-vue--page, are you doing this already?

**Comment by reed665** [comment]
Hi @felix-ico, thanks for your effort!

We just copied dist/scale-components and pasted into public folder due to some issues related to dynamic imports, but before that we were connecting scale via main.ts exactly as on scale docs page you provided.

I will try to create a minimal repo with a reproducible issue.

**Comment by reed665** [comment]
After we reconnected scale via main.ts like this
```typescript
import { defineCustomElements } from '@telekom/scale-components/loader';
import '@telekom/scale-components/dist/scale-components/scale-components.css';

// ...

defineCustomElements();
```
we got more stange issue - duplicated icons after navigation from any page

![image](https://user-images.githubusercontent.com/4117678/166867657-7f3a0659-8362-41c0-a6a9-167c4b280a59.png)

> I will try to create a minimal repo with a reproducible issue.
working on that

**Comment by felix-ico** [comment]
Hi again @reed665, we've had a similar issue on another Vue3 production app and I noticed a similarity with your initial code snippet:

`<scale-icon-action-edit
          accessibility-title="edit"
          size="16"
        />`

could you try changing this to `<scale-icon-action-edit accessibility-title="edit" size="16"></scale-icon-action-edit accessibility-title="edit" size="16">` 

removing the self-closing tag (not allowed in custom components) solved the issue for us.

**Comment by reed665** [comment]
Hi @felix-ico, so I replaced self-closing tag like this but no luck

```vue
<scale-button
          type="button"
          variant="secondary"
          icon-only
        >
        <scale-icon
          name="edit"
          accessibility-title="edit"
          size="16"
        ></scale-icon>
 </scale-button>
        ```
        
![image](https://user-images.githubusercontent.com/4117678/167775715-7bb858d5-5f31-45bd-849c-fa77515a5b1b.png)


I'm still trying to make a minimal repo with a reproducible issue. When I created one from scratch I didn't see a bug, so I working on existing one with a bug to make it as small as possible

**Comment by felix-ico** [comment]
Hi @reed665 I just pushed to your repro repo, I think the problem here was with vite - support with our current ionic/stencil version is limited (although that should be improved soon, keep an eye out for our next releases)

**Comment by reed665** [comment]
Hi @felix-ico, looks like it helped, thanks a lot!!

The only strange thing here that we have this project running under Vue CLI 5 a ween ago and we had the same issue, will check other projects.


For those who faced the same issue here is the solution (if you're using **vite** as a build tool)

**vite.config.ts**
```typescript
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
  plugins: [
    vue({
      template: {
          compilerOptions: {
            // do no use isCustomElement option for now here or it will make some of your scale-button and scale-icon attributes disappear when serving built project
            // isCustomElement: (tag) => tag.startsWith('scale-'),
          },
        },
    })
  ]
})
```
