### ISSUE TITLE
Text Filed font-weight bug?

### ISSUE THREAD

**Issue by robertgebhard** [telekom/scale#1012]
Hi,

I noticed that the error text and help text of the Text Field is different from all other input components. Which style is correct?

Text Field:
![Bildschirmfoto 2022-04-25 um 15 24 21](https://user-images.githubusercontent.com/95682620/165098930-e2eb3fc0-68d0-471e-91dd-65d04a8edcb5.png)

![Bildschirmfoto 2022-04-25 um 15 24 07](https://user-images.githubusercontent.com/95682620/165098883-9e4b11aa-c1b7-4f89-813c-effcea585bc5.png)

Others:
![Bildschirmfoto 2022-04-25 um 15 24 45](https://user-images.githubusercontent.com/95682620/165098993-8230bdd9-2ca8-4de3-ad5f-6b55de48112c.png)
![Bildschirmfoto 2022-04-25 um 15 25 06](https://user-images.githubusercontent.com/95682620/165099012-74c08e9c-cf28-4911-a7fc-3efd97411301.png)
![Bildschirmfoto 2022-04-25 um 15 25 22](https://user-images.githubusercontent.com/95682620/165099038-811770e5-66ca-4e3b-aa1e-a35f05c109c5.png)

Thanks!
Robert

**Comment by felix-ico** [comment]
Hi @robertgebhard, you are right there is an inconsistency - the font-weight for the Text field Error should be 700. I will open a PR to fix this, thanks for reporting!

**Comment by robertgebhard** [comment]
@felix-ico Sorry, I have discovered another error here. As you can see in the screenshots, the error message in the "Text Area" component starts on the left and in the others the error message always starts left-aligned with the label.
