### ISSUE TITLE
<scale-link> is not compatible with <scale-breadcrumb> 

### ISSUE THREAD

**Issue by adamfeher64** [telekom/scale#1016]
This works:
``` html
<scale-breadcrumb>
  <a href="#1"> First link </a>
  <a href="#2"> Second link </a>
  <a href="#3"> Third link </a>
</scale-breadcrumb>
```
Unexpectedly, this doesn't work:
``` html
<scale-breadcrumb>
  <scale-link href="#1"> First link </scale-link>
  <scale-link href="#2"> Second link </scale-link>
  <scale-link href="#3"> Third link </scale-link>
</scale-breadcrumb>
```

**Comment by marvinLaubenstein** [comment]
Hi @adamfeher64, I could now take a look at it. 

Unfortunately, I could not reproduce the error. 

![Bildschirmfoto 2022-04-27 um 13 39 49](https://user-images.githubusercontent.com/82942834/165511303-c6a0550a-31cb-4793-b419-1e0928ba7822.png)
<img width="284" alt="Bildschirmfoto 2022-04-27 um 13 39 04" src="https://user-images.githubusercontent.com/82942834/165511308-724464b3-6a68-4699-aa28-7a2664497698.png">

Could you maybe give us some more information. For example browser in which the error occurs and your scale version, maybe also your wrapping code, in which the **scale-breadcrump** was integrated. Thank you :)

Regards,
Marvin

**Comment by adamfeher64** [comment]
Hi @marvinLaubenstein, 
I'm using Scale version 3.0.0-beta.102 installed via NPM, integrated into Angular project with version 13.2.4. I'm trying to implement `<scale-breadcrump>` tag into `menu-main` slot of `<scale-app-header>` tag just like this:
``` html
<scale-app-header slot="header">
  <div slot="menu-main">
    <scale-breadcrumb>
      <scale-link omit-underline [routerLink]="['/en', 'first']">
        <span> Link #1 </span>
      </scale-link>
      <scale-link omit-underline [routerLink]="['/en', 'second']">
        <span> Link #2 </span>
      </scale-link>
    </scale-breadcrumb>
  </div>
</scale-app-header>
```
The code above is saved as Angular component with `<app-header>` tag selector and injected into `<scale-app-shell>` tag, just like this:
``` html
<scale-app-shell>
  <app-header slot="header"> </app-header>
  <div class="content">
    <router-outlet></router-outlet>
  </div>
  <app-footer slot="footer"></app-footer>
</scale-app-shell>
```
The problem is, that `<a>` tags with `[routerLink]` arguments causes reloading whole website, which is not expected behavior in Angular projects (more info can be found [here](https://angular.io/guide/router-tutorial)). I particulary solved that problem by using `<scale-link>` tags instead of `<a>` tags, which behaves as expected (smooth navigation between routes without reloading whole page), but the problem is, that `<scale-link>` tags nested in `<scale-breadcrumb>` tag are no longer clickable, so they behaves as a regular `<span>` plain text tags.

**Comment by acstll** [comment]
Here's a rather similar issue in which we found a solution, with Angular, maybe it helps?

https://github.com/telekom/scale/issues/969
