### ISSUE TITLE
Scale dropdown in dark mode in Chrome is visually broken

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1018]
https://www.brand-design.telekom.com/scale/?path=/docs/components-dropdown--standard&globals=locale:en;colorMode:dark

![image](https://user-images.githubusercontent.com/49948501/165729579-da736c3d-ff12-40fd-ae35-b011037f1a75.png)

**Comment by nowseemee** [comment]
This should be fixed in the latest published release.
