### ISSUE TITLE
Text Field label transition animation not working 

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1021]
Hi,

in latest release (3.0.0-beta.102) transition animations on Text Field are no longer working. Looks like --tranistion variable is not correct.

scale-text-field
--transition: all var(--telekom-motion-duration-transition) var(--telekom-motion-easing-standard);

scale-textarea
--transition: all var(--telekom-motion-duration-transition) cubic-bezier(var(--telekom-motion-easing-standard));

**Comment by maomaoZH** [comment]
Hi @nikolab-pn  thanks for reporting this. We will fix it asap.
