### ISSUE TITLE
BUG: wrongly set Z-Index for DataGrid flyout-menu when 'freeze-header' is enabled

### ISSUE THREAD

**Issue by Darkavid** [telekom/scale#1024]
Hello Scale Team,

I discovered a bug in the DataGrid component for React.

The `scale-menu-flyout-list` for Settings menu has this style:
```
:host {
   (...)
    z-index: var(--scl-z-index-20);
   (...)
}
```
Which is normally correct:
![image](https://user-images.githubusercontent.com/28023185/166219114-430c1307-b73d-48f2-aa54-a250f1cde38f.png)

However, when you enable 'freeze-header' on DataGrid, the Settings menu gets behind it:
![image](https://user-images.githubusercontent.com/28023185/166219305-59484a9a-9bc1-4597-9e3b-7189c7704dc2.png)

The problem is that when the --freeze-header class is applied, the `<thead>` element has higher z-index than the flyout-menu's:
```
.data-grid--freeze-header .thead {
   (...)
    z-index: 30;
   (...)
}
```
As these styles are encapsulated inside the shadow DOM, there are only messy ways to fix this outside the package.
Please, correct the styling, so I could use these two functionalities together.

Many thanks in advance!

**Comment by felix-ico** [comment]
Hi @Darkavid thank you for bringing this up! there is already a PR open to increase the z-index of the flyout menu https://github.com/telekom/scale/pull/1022 and it will be merged and released very soon!
