### ISSUE TITLE
Brand Header claimLang en

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1031]
Is it by design that there is no claim when claimLang prop is set to en?

**Comment by marvinLaubenstein** [comment]
Hi @nikolab-pn, exactly, we had the instruction from design/company side that the claim should be omitted in the english version.

**Comment by marvinLaubenstein** [comment]
I would now close the ticket. If you have any questions about this topic, you can always reopen the ticket. Thank you.
