### ISSUE TITLE
Z-index for Notification Toast should be configurable 

### ISSUE THREAD

**Issue by kolianovich** [telekom/scale#1038]
Hello!

I faced problem with z-index of notification toast. I need to increase it to prevent overlapping from other components, but I found out that z-index is hardcoded and equal 1:

.notification-toast {
....
  z-index: 1; 
....
}

Please replace hardcoded value of z-index with CSS variable to make it changeable.
Thanks a lot/.

**Comment by marvinLaubenstein** [comment]
Hi @kolianovich, thank you for the description of your problem. We can implement this :)
