### ISSUE TITLE
Data Grid bottom scrollbar on Firefox

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1040]
There is bottom scrollbar on Data Grid in Firefox when there should not be one.

[Scale Data Grid - standard](https://www.brand-design.telekom.com/scale/?path=/story/components-data-grid--standard&globals=locale:en;colorMode:light)

![image](https://user-images.githubusercontent.com/98950408/167352253-a2ed9e8e-5703-4a49-98d9-ebf799ddf43d.png)

**Comment by maomaoZH** [comment]
@nikolab-pn  thanks for reporting this issue. Do you mind telling us the version of scale and your operation system as well as your firefox version. We had a similar issue before, see here https://github.com/telekom/scale/issues/861 .

**Comment by nikolab-pn** [comment]
Picture is from your documentation page, so whatever scale version is there.
I'm running macOS 12.3.1 and Firefox 100.0 (64-bit)

**Comment by felix-ico** [comment]
closing this as the issue can not be reproduced anymore
