### ISSUE TITLE
Datepicker feature: disable text input/readonly text input

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#1042]
Hello there,

I would recommend a new Feature for the `DatePicker` `Component`.

It would be nice, if you could disable the text input.

**Comment by nowseemee** [comment]
Hi @christopherGdynia, it should be possible by adding the `disabled` attribute: https://www.brand-design.telekom.com/scale/?path=/docs/components-date-picker--disabled

Let me know if this doesn't work for you. Thanks!

**Comment by christopherGdynia** [comment]
Hi @nowseemee,

it would be nice if you only allow using the `datepicker` `menu` and disable the text input.

**Comment by nowseemee** [comment]
Ah, I get it - you want to disallow typing into the input while the date picker is still enabled? What would be the use case? This would introduce accessibility concerns.
