### ISSUE TITLE
Footer missing claimLang property

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#1044]
**Scale Version**
beta.102

**Framework and version**
react 17, nextjs 12
scale-react beta 102

**Current Behavior**
The title from the `scale-logo` is in the wrong language.
AppFooter doesn't take a `claimLang` property

**Expected Behavior**
AppFooter takes a `claimLang` property

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

```tsx
// appFooter.tsx line 66
// language hasnt any property
 <scale-logo
                    transparent
                    variant="white"
                    language=""
                    size={24}
                    href={this.logoHref}
                    logoTitle={this.logoTitle}
                    onClick={this.logoClick}
                    logoAriaDescribedBy={this.logoAriaDescribedBy}
                  ></scale-logo>
```
Please add the `claimLang` property that the `scale-logo` gets the right language.

**Comment by marvinLaubenstein** [comment]
Hi Christopher, thanks for creating the issue. We will have a look at it.
