### ISSUE TITLE
Button injecting CSS styles not working

### ISSUE THREAD

**Issue by Sony2k20** [telekom/scale#1046]
**Scale Version**
Version from the documentation

**Current Behavior**
After injecting a CSS style nothing is changing.
![button-css](https://user-images.githubusercontent.com/69435047/167588521-df84a7d3-d955-448c-bc10-1f97b871e64b.png)

**Expected Behavior**
The button should change to the used CSS style

**Comment by felix-ico** [comment]
actually, on a closer look, while some components in storybook do not pass the styles the button is not one of those. It just needs to target an element like so `:host .button { width: 1000px;}`
