### ISSUE TITLE
Scale button - propagate title attribute

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1050]
**Describe the feature request**

Propagate title attribute in Scale button so that if title is defined in scale button it will be added also to shadow button element.

**Describe the use case**

The use case is to be able to use other icons like font awesome seamlessly with scale button.

```html
<scale-button
  icon-only="true"
  title="my title"
>
  <span class="fas fa-sun" aria-hidden="true"></span>
</scale-button>
```

The problem now is that JAWS + Chrome reads additional statements because it gets confused about shadow button not having title property.

**Describe alternatives you've considered**

Alternative is to use html button with font awesome icon, or to use scale button with scale icon.

**Additional context**

I'll try to create PR for this, if you agree

**Comment by nowseemee** [comment]
Hi @mato-a, thanks a lot for the detailed report - we would be happy to have your PR. Many thanks

**Comment by nowseemee** [comment]
Seems like the button tag is not taking a title attribute according to the specification so I'd be hesitant to add it. Does the font awesome icon library support another way to apply icons to elements?

**Comment by mato-a** [comment]
Hi @nowseemee,

What specification do you mean?

Title attribute is global attribute and can be applied to any element: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

**Comment by nowseemee** [comment]
Hi @mato-a, you are right, the title attribute is a global one, could be used - it's my bad. Although many articles mention the accessibility problems it may cause. Do you think font awesome has another way to apply icons to elements? That would be excellent. We have this API for rendering additional icons within the button:
```
<scale-button>
  <scale-icon-action-search></scale-icon-action-search> Label
</scale-button>
```

I hope this is helpful - let me know.

**Comment by mato-a** [comment]
I've checked it. Font Awesome has alternative to use SVG + js. I'll try to implement it and will let you know if it resolved the issue.

**Comment by mato-a** [comment]
Hi @nowseemee 

We have switched Font Awesome from **Web Fonts + CSS** to **SVG + JS**.
https://fontawesome.com/docs/web/dig-deeper/webfont-vs-svg

Also specifically for our Angular project we have switched to:
https://github.com/FortAwesome/angular-fontawesome

With this set up Font Awesome generates very similar DOM as Scale icons: `title` element inside `svg` element which is read correctly by JAWS + Chrome.

Thanks for help @nowseemee and @matandre1. 👍 

The issue can be closed.
