### ISSUE TITLE
Data Grid inside Tab Navigation not rendering rows

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1052]
**Scale Version**
@telekom/scale-components 3.0.0-beta.102

**Framework and version**
@telekom/scale-components-react 3.0.0-beta.102

**Current Behavior**
When using Data Grind inside Tab Navigation and fetching async data for Data Grid rows are not rendered.

**Expected Behavior**
When using Data Grind inside Tab Navigation and fetching async data for Data Grid rows are rendered.

**Code Reproduction**
https://codesandbox.io/s/priceless-lamport-05y7s0?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser: Chrome
 - Version: 101.0.4951.54

**Comment by jano314159** [comment]
This is a problem that we also have :( Did you find any solution for that?

**Comment by biharvarijozsef** [comment]
> This is a problem that we also have :( Did you find any solution for that?

I'm using the angular material cdk table (https://material.angular.io/cdk/table/overview) and style it as the scale table :|

**Comment by jano314159** [comment]
Thank you for your response @acstll  :) 
We are using react :D and I actually fixed that  on our side. In a nutshell if the tab nav is changed we try to force re-render the actual component and it's works really well so I'm happy with that solution for now :D

**Comment by acstll** [comment]
I'm closing but feel free to keep the conversation going if needed (thank you!) ✌️

**Comment by nikolab-pn** [comment]
Hi @acstll,

This two would work good with our current setup:
- [ ] one should be able to select a tab declaratively with a selected attribute or similar (currently it only handles some styles)
- [ ] it should emit a custom event on selection
