### ISSUE TITLE
Notification toast disappears right after opening

### ISSUE THREAD

**Issue by kolianovich** [telekom/scale#1053]
**Scale Version**
@telekom/scale-components-neutral": "3.0.0-beta.104

**Framework and version**
Angular 12

**Current Behavior**
In a second after opening the Notification Toast component disappears.

**Expected Behavior**
It should be visible while property opened=true or autohide event is not invoked.

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

\<scale-notification-toast variant="success" opened>
\<p slot="header">Informational toast headline\</p>
\<p slot="body">Subheadline goes here.\</p>
\</scale-notification-toast>

https://codesandbox.io/s/scale-components-angular13-forked-0wds05?file=/src/app/app.component.html - link to sandbox where you can observe this problem

**Additional context**
We found out that the problem is within CSS classes:

.notification-toast {
....
opacity: 0;
....
}

.notification-toast--show {
    right: 12px;
    animation: fadeIn 0.5s ease-in-out;
    top: 12px;
    ~~opacity: 1;~~
}

in a second after opening class .notification-toast with opacity: 0 overrides .notification-toast--show class with property opacity: 1

**Comment by marvinLaubenstein** [comment]
Hi @kolianovich, thanks for the detailed description of the problem. We will look at it as soon as possible

**Comment by marvinLaubenstein** [comment]
Hi @kolianovich, I have now looked at your sandbox and tried to reproduce the whole issue again locally. For me it actually works flawlessly. 

Does it work for you in the sandbox, or does the bug also occur there ? If so, could you please send me a screenshot of the css (.notification-toast & .notification-toast--show) together with the app.component.html ( like my attached image)? 

<img width="1379" alt="Bildschirmfoto 2022-05-13 um 15 40 33" src="https://user-images.githubusercontent.com/82942834/168297354-ea3ff0da-ed17-4a66-8a21-55f880e5fcff.png">

Thank you

**Comment by christopherGdynia** [comment]
Hey,

same with `react` `wrapper`

![image](https://user-images.githubusercontent.com/84845536/168532339-5a2372bf-ee98-4175-b848-a1a5f4e6cbcd.png)
![image](https://user-images.githubusercontent.com/84845536/168532380-54ccaa86-f2a4-4b1b-95af-e008ddecc16a.png)

**Comment by nowseemee** [comment]
hey all, thanks a lot for working on this - the fix ☝🏻 has been published `3.0.0-beta.106`
