### ISSUE TITLE
Notification Toast has extra "white borders"

### ISSUE THREAD

**Issue by kolianovich** [telekom/scale#1055]
Scale Version
@telekom/scale-components-neutral": "3.0.0-beta.104

Framework and version
Angular 12&13

**Current Behavior**
Right top and right bottom corners of Notification Toast component have "white borders". It is clearly visible on a dark background.

**Expected Behavior**
No extra "white borders".

**Code Reproduction**
Just make a black background behind Toast
![123](https://user-images.githubusercontent.com/25793946/168296620-d82bb4ee-3505-46cc-9570-91605a4110f3.jpg)

**Additional context**

We found out that by default border radius of div with class .notification-toast is less than border radius of inner div with class .notification-toast__icon-container.

**Comment by nowseemee** [comment]
hey all, thanks a lot for working on this - the fix ☝🏻 has been published `3.0.0-beta.106`
