### ISSUE TITLE
Notification Message and Notification Banner don't emit scale-close Event

### ISSUE THREAD

**Issue by lukascorona** [telekom/scale#1057]
**Describe the feature request**
Currently, unlike the scale-modal, no `scale-close` event is emitted when the close button is clicked. Here it would be desirable that a corresponding event is emitted so that a controlled underlying state can be updated accordingly.

**Describe the use case**
We want to use the `scale-notification-message` to display notifications that get stored locally. However, when clicking the close icon, we need to mark them as read so that they are not displayed again when the page is reloaded.

**Describe alternatives you've considered**
As an alternative, a slot for a custom close button could be provided. Consistent event emitting similar to the scale-modal would certainly be more understandable though

**Additional context**
![image](https://user-images.githubusercontent.com/33840479/168559230-793c6a8f-2279-4527-920a-83732345d840.png)
The image shows our planned usage for the notifications. A click on the close button should permanently delete the respective notification from the quick menu

**Comment by acstll** [comment]
I would be in favor also of emitting `scale-close` 👍 — thanks for opening this @lukascorona

**Comment by nowseemee** [comment]
3.0.0-beta.105 has this addition
