### ISSUE TITLE
QUE: How to set a logo link in scale-header component, so that it works in all modes?

### ISSUE THREAD

**Issue by daredevel66** [telekom/scale#1068]
**Scale Version**
"@telekom/scale-components": "^3.0.0-beta.41",

**Framework and version**
Angular
Angular CLI: 13.2.2       
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Package                      Version
@angular-devkit/architect    0.1302.2 (cli-only)
@angular-devkit/core         13.2.2 (cli-only)
@angular-devkit/schematics   13.2.2 (cli-only)
@schematics/angular          13.2.2 (cli-only)

Question:
I'm using the scale header component (standard) and added a custom link (href="/") to the logo (via slot logo).
In normal mode the link I set works fine. But when I scroll the page down so that the menu
switches to mobile mode I only get a "javascript:void(0)".

What am I doing wrong or is this a bug?
How should the link to be set so that it works for the logo even in responsive design?

**Desktop (please complete the following information):**
 - OS:Microsoft Windows 10 Enterprise
      21H2 (10.0.19044.1645)
      64bit
 - Browser: Chrome
 - Version:  101.0.4951.41 (Offizieller Build) (64-Bit)

**Additional context**
I tried to insert some code snippet, but because of some reason the content was not displayed correctly .

Regards Holger

**Comment by nowseemee** [comment]
hey @daredevel66 thanks a lot for opening this issue - the fix ☝🏻 has been published `3.0.0-beta.106`
