### ISSUE TITLE
Data Grid ghost actions accessiblity contrast

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1074]
Scale Version
@telekom/scale-components 3.0.0-beta.102

Framework and version
@telekom/scale-components-react 3.0.0-beta.102

Current Behavior
When using Data Grind with actions column and if using ghost buttons color contrast too low (4.4:1). 
![image](https://user-images.githubusercontent.com/98950408/169774612-6fadd38b-2e7d-4c8d-a1d6-69e1d091158e.png)

Expected Behavior
When using Data Grind with actions column and using ghost buttons I want component to pass WCAG 2.1 contrast requirements (> 4.5:1).

Code Reproduction
https://codesandbox.io/s/priceless-lamport-05y7s0?file=/src/App.js

Desktop (please complete the following information):

OS: macOS 12.3.1
Browser: Chrome

Version: 101.0.4951.54

**Comment by JoschaIco** [comment]
Hi Nikolab-pn, 

thanks for sharing your findings! We are currently reworking the interactive Icon as a separate component. The new component will work with the text & icon color-tokens (which we measured against all basic background colors). 

We currently don't have a release date for the new interactive icon, but I am confident that it will be ready soon.

Best regards
Joscha
