### ISSUE TITLE
ScaleDropdown dynamic loading of options leads to graphical bug

### ISSUE THREAD

**Issue by ledex** [telekom/scale#1078]
**Scale Version**
3.0.0-beta.105

**Framework and version**
React 18.0.0 w/ @telekom/scale-components-react

**Current Behavior**
When the current value of a dropbox is not set and options are added the first option will be shown on top of the label in the dropdown but it's not selected an the 'onScaleChange' will not be triggered. (Also see the attached picture)

![image](https://user-images.githubusercontent.com/39191120/169796943-c7095314-dc70-49f8-865e-42ae314cc4f6.png)

When the dropdown-box only contains one option it is not possible to make a selection after this bug occurred. 

**Expected Behavior**
When the dropdown options change the appearance should stay as is.

**Code Reproduction**
https://codesandbox.io/s/scale-components-react18-with-wrapper-forked-34g0t9
Just set any dropdown-value

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version 99.0.4844.51

**Additional context**
N/a

**Comment by nowseemee** [comment]
Hi @ledex, thanks for reporting this, and big thanks for the reproduction example. I've tried to patch it but decided to give up as we have a brand new rewrite of the dropdown in the works - quite close to a beta release. The new component won't have this problem so I'd rather focus on shipping the improved version instead of patching this problem. I hope this is fine for you.

**Comment by nowseemee** [comment]
Hi @ledex, sure, you can follow the progress of the PR: https://github.com/telekom/scale/pull/1069
We need to clarify some questions regarding the expected focus behavior and do the quality assurance  - those are the last steps before we release it as beta.

**Comment by tshimber** [comment]
Hi! my team asks me, if it would be fixed before autumn, maybe you could tell or it's not clear yet? thanks in advance!

**Comment by nowseemee** [comment]
The new `dropdown-select` is now published with `3.0.0-beta.109`.
https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard
