### ISSUE TITLE
In Modal customClass Property doesn't work

### ISSUE THREAD

**Issue by biharvarijozsef** [telekom/scale#1093]
**Scale Version**
"@telekom/scale-components": "^3.0.0-beta.103",

**Framework and version**
Angular 13

**Current Behavior**
The class doesn't get injected into the shadow DOM

**Expected Behavior**
The class should be injected into the shadow DOM

**Code Reproduction**
scale-modal custom-class="'MyCustomScaleModalClass'" heading="Change direct service assignment to CGs" size="large" opened="true"></scale-modal>

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by acstll** [comment]
Hi @biharvarijozsef, thanks for opening this!

The `customClass` attribute was removed in v2. I see we have a leftover in the Modal, sorry (we will remove it). This attribute used to work with a previous architecture for adding custom styles, which is no longer available, so it's practically useless.

What is it that you were trying to achieve? We'd be glad to help.

**Comment by biharvarijozsef** [comment]
Hi!
I wanted to set the Modal height to 100% percent. I could solve it only that way:
<scale-modal
  heading="Change direct service assignment to CGs"
  size="large"
  [opened]="isAssignmentModalOpen"
  (scaleClose)="onModalClose($any($event))"
  **styles=".modal__window{height: 100% !important;}"**
  >

**Comment by biharvarijozsef** [comment]
Thanks a lot.
