### ISSUE TITLE
Data Grid settings menu localization

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1113]
**Describe the feature request**
Possiblity to change language in Data Grid settings menu like in Header or to add custom localization strings like in Date Picker

**Describe the use case**
We have multilanguage application and would also be able to have this component in both languages (en, de)

**Comment by mato-a** [comment]
Also for example titles of sorting buttons in table header can't be translated now, they seem to be hard-coded - https://github.com/telekom/scale/blob/main/packages/components/src/components/data-grid/data-grid.tsx#L998

Also related to this - it seems that even if Pagination on its own can be localized, it is currently not possible to change translations for Pagination that is managed by Data Grid component.
