### ISSUE TITLE
<scale-tab-nav> change focus of tab-header/tab-panel not possible

### ISSUE THREAD

**Issue by NorbertDreher** [telekom/scale#1115]
**Scale Version**
@telekom/scale-components : 3.0.0-beta.41
@telekom/scale-design-tokens : 3.0.0-beta.53

**Framework and version**
Angular : 11.2.14

**Code Reproduction**

`<scale-tab-nav>
    <scale-tab-header slot="tab" >
        Ausgewählte Netzelemente
    </scale-tab-header>
    <scale-tab-panel slot="panel">

        <app-netz-table
            [ngClass]="{'hidden': !service || !service.id || !showStaticTable}"
            [isChecked]="isChecked"
            (onChecked)="onChecked()"
            [showBtn]="true"
            [seId]="service.id"
            [body]="searchParams"
            [visibleColumns]="visibleColumns"
            [mode]="'static'"
            [serviceLoaded]="serviceLoaded"
            [needToUpdate]="needToUpdateStatic">
        </app-netz-table>

    </scale-tab-panel>

    <scale-tab-header slot="tab" id="searchResultsTabLabel">
        Gefundene Netzelemente
    </scale-tab-header>
    <scale-tab-panel slot="panel">

        <app-netz-table
            [ngClass]="{'hidden': !service || !service.id || !showStaticTable || !(service && service.id && searchParams )}"
            [isChecked]="isChecked"
            (onChecked)="onChecked()"
            [showBtn]="false"
            [seId]="service.id"
            [body]="searchParams"
            [visibleColumns]="visibleColumns"
            [mode]="'search'">
          </app-netz-table>

    </scale-tab-panel>
</scale-tab-nav>`

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser : Google Chrome Version 102.0.5005.115 (Offizieller Build) (64-Bit)

**Additional context**
Is it possible to change the focus to a tab using a function?
left beside this scale-tab-nav is a search area with a search button. I want to switch to the search result after pushing the search button.
I didn't found a solution.

**Comment by acstll** [comment]
Hey @NorbertDreher — thanks for opening this.

I realised there is no "idiomatic" way to do this, but there's an "easy" solution. You can trigger a click on the tab header that you want to select. Something like this:

```ts
import { Component, ViewChild, ElementRef } from '@angular/core';

@Component({
  template: `
    <div>
      <scale-tab-nav>
        <scale-tab-header slot="tab" #tab1>Tab 1</scale-tab-header>
        <scale-tab-panel slot="panel">1</scale-tab-panel>
        <scale-tab-header slot="tab">Tab 2</scale-tab-header>
        <scale-tab-panel slot="panel">2</scale-tab-panel>
      </scale-tab-nav>
      <scale-button (click)="selectTab1()">Go to Tab 1</scale-button>
    </div>
  `
})
export class AppComponent {
  @ViewChild('tab1') tab1!:ElementRef;

  selectTab1() {
    // Trigger click on DOM element
    this.tab1.nativeElement.click()
  }
}
```

---
We'll think of a way to try and improve upon this use case.

**Comment by NorbertDreher** [comment]
Hey Arturo,

thanks fort the answer!

I also tried to address both tabs with different buttons.
How does this work?
<scale-button (click)="selectTab1()">Go to Tab 1</scale-button>
<scale-button (click)="selectTab2()">Go to Tab 2</scale-button>

Best regards
Norbert

Von: Arturo Castillo Delgado ***@***.***>
Gesendet: Mittwoch, 29. Juni 2022 15:59
An: telekom/scale ***@***.***>
Cc: Dreher, Norbert ***@***.***>; Mention ***@***.***>
Betreff: Re: [telekom/scale] <scale-tab-nav> change focus of tab-header/tab-panel not possible (Issue #1115)


Hey @NorbertDreher<https://github.com/NorbertDreher> — thanks for opening this.

I realised there is no "idiomatic" way to do this, but there's an "easy" solution. You can trigger a click on the tab header that you want to select. Something like this:

import { Component, ViewChild, ElementRef } from ***@***.***/core';







@Component({



  template: `



    <div>



      <scale-tab-nav>



        <scale-tab-header slot="tab" #tab1>Tab 1</scale-tab-header>



        <scale-tab-panel slot="panel">1</scale-tab-panel>



        <scale-tab-header slot="tab">Tab 2</scale-tab-header>



        <scale-tab-panel slot="panel">2</scale-tab-panel>



      </scale-tab-nav>



      <scale-button (click)="selectTab1()">Go to Tab 1</scale-button>



    </div>



  `



})



export class AppComponent {



  @ViewChild('tab1') tab1!:ElementRef;







  selectTab1() {



    // Trigger click on DOM element



    this.tab1.nativeElement.click()



  }



}

________________________________

We'll think of a way to try and improve upon this use case.

**Comment by acstll** [comment]
You're welcome!

For many tabs you need to have a reference (`ElementRef`) for every `scale-tab-header`

```html
<scale-tab-header slot="tab" #tab1>Tab 1</scale-tab-header>
...
<scale-tab-header slot="tab" #tab2>Tab 2</scale-tab-header>
etc...
```

And then you can either have a separate function for every tab, or target them by "name". (`tab1` and `tab2` are names for illustrating the idea, you can name the references however it makes more sense).

e.g. with separate functions:

```ts
export class AppComponent {
  @ViewChild('tab1') tab1!:ElementRef;
  @ViewChild('tab2') tab2!:ElementRef;

  selectTab1() {
    this.tab1.nativeElement.click()
  }
  selectTab2() {
    this.tab2.nativeElement.click()
  }
}
```

e.g. with a single function:

```ts
export class AppComponent {
  @ViewChild('tab1') tab1!:ElementRef;
  @ViewChild('tab2') tab2!:ElementRef;

  selectTab(refName) {
    this[refName].nativeElement.click()
  }
}
```

plus:

```html
<scale-button (click)="selectTab('tab1')">Go to Tab 1</scale-button>
<scale-button (click)="selectTab('tab2')">Go to Tab 2</scale-button>
```

I hope this helps.

**Comment by NorbertDreher** [comment]
Thanks very much!
