### ISSUE TITLE
Scale-menu-flyout-list sublists are not closing after switching between them

### ISSUE THREAD

**Issue by Tireile** [telekom/scale#1122]
Hello!

It looks like there is wrong behavior of closing scale-menu-flyout-list sub lists in case when we switching between them.
When we have an opened sub list and then will try to select another one the first opened sub list continue displaying instead of closing.

Demo:
![bug](https://user-images.githubusercontent.com/35307181/177285073-358f788c-f62c-48bb-b076-98759f5b2148.gif)

**Comment by Tireile** [comment]
> 

^3.0.0-beta.107

**Comment by acstll** [comment]
Reported here before https://github.com/telekom/scale/issues/712

**Comment by acstll** [comment]
Fixed in #1131, release to follow very soon.

**Comment by Tireile** [comment]
Thanx for fix!
