### ISSUE TITLE
Dropdown options always in dark mode in firefox

### ISSUE THREAD

**Issue by lippielip** [telekom/scale#1138]
**Scale Version**
"@telekom/scale-components": "^3.0.0-beta.107"

**Framework and version**
Are you using web components in a specific framework (react, angular, vue)? If so what version of the framework? Are you using one of the auto-generated scale wrapper packages?
"react": "^17.0.2",
"@telekom/scale-components-react": "^3.0.0-beta.56",

**Current Behavior**
When opening a Dropdown field on Firefox, the Dropdown options always display in dark mode. Changing Windows or Firefox Theme does not change this. Manually forcing dark mode off, has no effect either

**Expected Behavior**
Dropdown options should adhere to dark/light mode settings.

**Code Reproduction**
`<scale-dropdown label="select">`
`  <option value="1">item 1</option>`
`  <option value="2" selected>item 2</option>`
`  <option value="3">item 3</option>`
`</scale-dropdown>`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 102

**Comment by lippielip** [comment]
current
![grafik](https://user-images.githubusercontent.com/55237772/178738758-f5758adb-24a3-449e-94dc-aa125b9e3393.png)

expected
![grafik](https://user-images.githubusercontent.com/55237772/178738915-e53d8ed7-e152-4020-be25-eab71158ec70.png)

**Comment by marvinLaubenstein** [comment]
Hi @lippielip, thanks for the detailed description of the problem. Soon we will release a new version of the `dropdown`component. Of course, we also make sure that current problems will be fixed.

As soon as the new `dropdown`component is released I will inform you here again.
