### ISSUE TITLE
Scale in Server Side Rendered ASP.NET Core Environment

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#1146]
Hello there,

I have a `ASP.NET Core MVC` Application with `Scale Components` currently it is working with the following snippet inside the `HTML` `head`.

Today it didn't work, because of some issues.
When it's working it is loading for ages, futher more I need to change it, because of security reasons.

I have tried to create a project that uses the exact `components` as in the other project and try to bundle it. At first I created a npm project, added `Scale` and a Bundler, bundled it at first with `rollup`, than with 'vite', but it doesn't work.

I have tried to compile the project, but it doesn't work.

I am kinda annoyed and mad.

If I am still using unpkg, I need to add  `Subresource Integrity` more on this [here](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)

Can you help me on this one.

Current state
```html
  <link rel="stylesheet" href="https://unpkg.com/@@telekom/scale-components/dist/scale-components/scale-components.css" />
    <script type="module" src="https://unpkg.com/@@telekom/scale-components/dist/scale-components/scale-components.esm.js"></script>

```

**Comment by christopherGdynia** [comment]
It works to copy the folder from "node_modules/@telekom/scale-components/dist/scale-components" to the static content folder, it's not pretty but it works reliable.

**Comment by acstll** [comment]
Yep, definitely not pretty but it's effectively the same as using the CDN, only that the files are on your server. (I know you know this but I would only like to emphasise it.)

Are you using some automation to copy over the files?

What kept you from using `Subresource Integrity`?

Thanks for opening this @christopherGdynia.

**Comment by christopherGdynia** [comment]
> What kept you from using Subresource Integrity?

Hey, there are two reasons, first the cdn was inconsistent in terms of speed and I didn't know how to do it, but it loaded forever
