### ISSUE TITLE
Header and Footer borders are different

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#1151]
**Scale Version**
3.0.0-beta.108

**Framework and version**
Not the case

**Current Behavior**
Not sure if this is a bug, but previously the footer and the header borders used to have the same looks, now the footer one is slimmer and lighter, making it really hard to notice.

**Expected Behavior**
I would expect both borders to have the same looks(thickness, color).

**Code Reproduction**
Just an app-shell with a header and footer, and enough content to make the page scrollable.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 103.0.5060.134 

![image](https://user-images.githubusercontent.com/22682250/181201535-502f2caa-8223-4c81-8b96-bd78afb1fb93.png)

**Comment by JoschaIco** [comment]
Hey @pomoalex, thanks for your feedback…you are right! The divider for the footer uses the wrong color token. We'll fix that!
