### ISSUE TITLE
Overlapping DropDown/MegaMenu

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#1156]
Hi there,

see below. I created an example on codesandbox

Greetings

**Scale Version**
Tested with current Version 108

**Framework and version**
Tested with React 17

**Current Behavior**
If a dropdown Menu is open with all the options visible and I move the Mouse to the Brand Header/Menu options the dropdown is still visible and overlaps with the navigation Menu.

**Expected Behavior**
Dropdown is not visible. Only Brand Header / Menu options should be visible.

**Code Reproduction**
https://codesandbox.io/s/megamenu-overlap-ulfwe6

**Desktop (please complete the following information):**
Tested on windows with all browsers.

**Comment by ayeshaa-m** [comment]
@tommy-codez The dropdown options will be closed when you click outside. I perhaps might have not understood the description. What is expected behaviour "when the dropdown should not be visible"?

**Comment by tommy-codez** [comment]
The problem was an overlapping of both (mega menu + dropdown) when it was opened. I didnt tested it with the new component, though. 
![image](https://user-images.githubusercontent.com/66920189/229076460-d574d44e-a3c8-4f05-946c-1f34a0853491.png)

**Comment by ayeshaa-m** [comment]
Hi @tommy-codez ,
Kindly use dropdown-select component (https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard). This is the new (beta) version of the dropdown and the previous scale-dropdown (https://telekom.github.io/scale/?path=/docs/components-dropdown--standard) will be deprecated. I checked with dropdown-select component and this issue does not occur.
--- Thanks
