### ISSUE TITLE
Extra scrolling in scale-modal

### ISSUE THREAD

**Issue by Tireile** [telekom/scale#1173]
Hello!! 
I've found out a strange bug. In case of <scale-modal> has huge content and the <scale-checkbox-group /> after it,  then appears an extra scrolling. 
In the same time if we add <scale-checkbox-group /> before huge content, then we won't see an extra scrolling.

Sandbox: [https://codesandbox.io/s/bold-ride-4b3k5b](https://codesandbox.io/s/bold-ride-4b3k5b)

**Demonstration**

![scale-issue](https://user-images.githubusercontent.com/35307181/185376451-70b7cd55-e506-4ed5-968c-0cc68307389e.gif)

**Comment by acstll** [comment]
This is quite an edge case! Thanks a lot for reporting it and creating the sandbox @Tireile — We will take a look in the upcoming days in order to fix it.

**Comment by maomaoZH** [comment]
We had this issue reported before. It was caused by checkbox or checkbox group here. I will have a look again why it appears again.
