### ISSUE TITLE
Scale link size not adjusting on iPhone in landscape

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#1193]
**Scale Version**
[3.0.0-beta.111](https://github.com/telekom/scale/compare/v3.0.0-beta.110...v3.0.0-beta.111)

**Framework and version**
No framework

**Current Behavior**
When tilting the iPhone and switching to landscape mode the text sizes adjust, all but the scale-link component. This is not the case on other devices(desktop on similar sized window and Android).

**Expected Behavior**
I expect scale-link text to behave same as all other texts in the page.

**Code Reproduction**
<scale-app-shell id="app-shell">

    <scale-app-header
            slot="header"
            id="header">
    </scale-app-header>

    <h4 class="scl-font-variant-heading-4">Some title</h4>
    <span>Some text and <scale-link target="_blank" href="#">some link</scale-link>.</span>
    <br>
    <span class="scl-font-variant-smaller">Some text and <scale-link target="_blank" href="#">some link</scale-link>.</span>

    <scale-app-footer id="footer" variant="minimal">
    </scale-app-footer>

</scale-app-shell>

**iPhone:**
 - Device: iPhone XR
 - OS: iOS 14.2
 - Browser Safari
 - Version 14

https://user-images.githubusercontent.com/22682250/187925562-b24edb00-cc04-4942-8f47-fa74bfbb8dc1.mp4

**Comment by felix-ico** [comment]
hi @pomoalex and thanks for reporting the issue. I was just testing it and can confirm the issue. It seems however that the text resize is triggered by iOS Safari, rather than some specific styling in scale. Adding 
```
html {
    -webkit-text-size-adjust: 100%;
}
``` 
in my app stylesheet solved the issue, keeping the text size the same in both portrait and landscape mode.

**Comment by felix-ico** [comment]
Closing as resolved, but please feel free to re-open if needed
