### ISSUE TITLE
DropdownSelectItem don't have a value in Vue 3 / Vite 3

### ISSUE THREAD

**Issue by niclas18** [telekom/scale#1194]
**Scale Version**
@telekom/scale-components 3.0.0-beta.111

**Framework and version**
Vue 3.2.38
Vite 3.0.9 

**Current Behavior**
In our project the new DropdownSelect is broken, because the value attribute of DropdownSelectItem is not passed to the child components. In this case the Component looks really crazy when click on one option in the Dropdown.

**Expected Behavior**
Everything works like in the Storybook.
[Storybook-DropdownSelect](https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard)

**Code Reproduction**
I use the same code, as in the Storybook:
`<scale-dropdown-select label="select">`
`<scale-dropdown-select-item value="caspar">Caspar</scale-dropdown-select-item>`
`<scale-dropdown-select-item value="cedric">Cedric</scale-dropdown-select-item>`
`<scale-dropdown-select-item value="cem">Cem</scale-dropdown-select-item>`
`</scale-dropdown-select>`

The CodeSandbox don't work at the moment with Vue 3 and Vite 3.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise - 21H2
 - Browser: Chrome
 - Version: 104.0.5112.102
 
**Additional context**
In the StoryBook I see with the Developer-Mode that all DropdownSelectItems have the value attribute in HTML-tree. In our project we have also the 3 DropdownSelectItems, but the value attribute don't passed into the HTML-tree.

For testing I add [here](https://github.com/telekom/scale/blob/main/packages/components/src/components/dropdown-select-item/dropdown-select-item.tsx) in line 16 a new line with the Host tag: `<Host value={this?.value}>` and end tag in line 28: `</Host>`.
Then it works like expected in our project.

**Comment by niclas18** [comment]
It look like a problem in the vue-router package, without using this, the component works well.

**Comment by acstll** [comment]
> It look like a problem in the vue-router package, without using this, the component works well.

that's still weird 😮 (thanks for reporting!)

> For testing I add [here](https://github.com/telekom/scale/blob/main/packages/components/src/components/dropdown-select-item/dropdown-select-item.tsx) in line 16 a new line with the Host tag: <Host value={this?.value}> and end tag in line 28: </Host>.
Then it works like expected in our project.

could you be so kind and test adding the [`reflect` option](https://stenciljs.com/docs/properties#reflect-properties-values-to-attributes-reflect) (`@Prop({ reflect: true })`) for the `value` prop on [line 12](https://github.com/telekom/scale/blob/main/packages/components/src/components/dropdown-select-item/dropdown-select-item.tsx#L12)? — I'm thinking that would have the same effect, only using a "different API".

**Comment by niclas18** [comment]
> could you be so kind and test adding the [reflect option](https://stenciljs.com/docs/properties#reflect-properties-values-to-attributes-reflect) (@Prop({ reflect: true })) for the value prop on [line 12](https://github.com/telekom/scale/blob/main/packages/components/src/components/dropdown-select-item/dropdown-select-item.tsx#L12)? — I'm thinking that would have the same effect, only using a "different API".

I deleted the Host tag and add the reflect option, as you mentioned. This makes working this component for our project, too.

It is possible, that you add this globally in the package?
Otherwise I have to find out, why vue-router blocks the values without using Host or reflect, which can be really complicated, I think.

**Comment by acstll** [comment]
> It is possible, that you add this globally in the package?

definitely, will do! Thanks for testing.

**Comment by niclas18** [comment]
Thanks for your quick response and the PR for that!
