### ISSUE TITLE
Header logo issues depending on selected claim-lang

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#1198]
**Scale Version**
3.0.0-beta.111

**Framework and version**
No framework

**Current Behavior**
When selecting an unsupported(but still valid) claim-lang, the logo disappears completely. Also, when selecting "en" the logo appears without the motto section, which wasn't the case previously.

**Expected Behavior**
I expect the main logo to be shown for any given locale(even if invalid) and the motto section of the logo to change in case of a recognized and supported locale.

**Code Reproduction**
```
<scale-app-shell id="app-shell">

    <scale-app-header slot="header" id="header" claim-lang="es">
    </scale-app-header>

</scale-app-shell>
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 105.0.5195.102

**Comment by felix-ico** [comment]
Hi, Thank you for reporting this issue. As you can see I had opened a PR to achieve what you wanted, but after some discussion with the team I was able to gather that this is indeed the desired behavior of the brand header from a design/branding perspective.
