### ISSUE TITLE
Don't render expand button in data grid when HTML cell is empty

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1199]
**Describe the feature request**
Don't render expand button in data grid when HTML cell is empty

**Describe the use case**
We would like to show data as expanded row but not for all rows

https://codesandbox.io/s/zen-torvalds-y7o4x5?file=/src/App.js

**Comment by felix-ico** [comment]
this should be available in the next release https://github.com/telekom/scale/pull/1573
