### ISSUE TITLE
Text Field helper messages all use the same id attribute

### ISSUE THREAD

**Issue by Scrumplex** [telekom/scale#1206]
**Scale Version**
3.0.0-beta.111

**Framework and version**
No Framework

**Current Behavior**
Helper texts of text fields all have the same `id="helper-message-4"` HTML attribute, which seems to cause issues with screen readers.

**Expected Behavior**
Every helper message should have a unique id

**Code Reproduction**
```
<scale-text-field id="one" label="One" helper-text="textbox1"></scale-text-field>
<scale-text-field id="two" label="Two" helper-text="textbox2"></scale-text-field>
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Microsoft Edge, Firefox
 - Version Firefox 104.0.2, Microsoft Edge 105.0.1343.33

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by marvinLaubenstein** [comment]
Hi @Scrumplex, thanks for mentioning this possible issue. I will take a look.

**Comment by marvinLaubenstein** [comment]
Unfortunately, I can't find any issue in assigning the helper-text IDs. 

<img width="1727" alt="Bildschirmfoto 2022-09-23 um 09 56 04" src="https://user-images.githubusercontent.com/82942834/191917212-a92c7a30-32df-4bf5-96b0-a5d094b01e28.png">

If the issue should occur nevertheless I would ask you to send me a screenshot of the issue, similarly to my attached **screenshot**. It might also help us to know in which **framework** or environment you are using scale. 

I could also suggest that you send me a **sandbox**. You may fork one of the available sandboxes as a base:

[Scale and Plain HTML](https://codesandbox.io/s/scale-components-plain-html-template-qfi9mp)
[Scale and React18](https://codesandbox.io/s/scale-components-react18-75ci1x)
[Scale and React18 with Wrapper Package](https://codesandbox.io/s/scale-components-react18-with-wrapper-xqqkrv)
[Scale and Angular13](https://codesandbox.io/s/scale-components-angular13-kxzv2k)
[Scale and Vue3](https://codesandbox.io/s/scale-components-vue3-b14993)

**Comment by Scrumplex** [comment]
I have recreated this behavior in a plain HTML sandbox: https://codesandbox.io/s/scale-components-plain-html-template-forked-l8rone?file=/index.html

Just enter some text in one of the password fields, which will generate a helper text.

**Comment by marvinLaubenstein** [comment]
I see the problem. We will take care of the issue as soon as possible. Thanks a lot!

**Comment by marvinLaubenstein** [comment]
Thank you for finding the problem. We have solved it and will release it in the near future. 

I am closing the ticket, if there are still problems after the release, please open it again.
