### ISSUE TITLE
Notification Message elements don't have role="alert"

### ISSUE THREAD

**Issue by Scrumplex** [telekom/scale#1207]
**Scale Version**
3.0.0-beta.111

**Framework and version**
No Framework

**Current Behavior**
Notification Messages do not have the `role="alert"` tag which would improve accessibility.

**Code Reproduction**
```html
<scale-notification-message dismissible opened>
  Notification text goes here
</scale-notification-message>
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Microsoft Edge, Firefox
 - Version Firefox 104.0.2, Microsoft Edge 105.0.1343.33

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by marvinLaubenstein** [comment]
Hi @Scrumplex, thank you for pointing this out. Actually, our `scale-notification-message` should contain the `role="alert"`.  I will have a closer look.
