### ISSUE TITLE
header expands over entire page when page width is between 1023px and 1024px

### ISSUE THREAD

**Issue by JoKurth** [telekom/scale#1209]
**Scale Version**
v3.0.0-beta.112

**Framework and version**
Vue 3.2.38
Vite 3.1.0

**Current Behavior**
The magenta part of the header expands over almost the entire page when the size of the page/window is between 1023px and 1024px. It seems like the corresponding media-queries should not be `max-width: 1023px` and `min-width: 1024px` but rather `max-width: 1023.99px` and `min-width: 1024px`
![image](https://user-images.githubusercontent.com/71062996/189927546-ab44cd5e-ccb6-4f69-9668-27aff85f8a19.png)

**Expected Behavior**
The header should break smoothly and not hide the page.

**Code Reproduction**
Use the `<scale-app-shell>`. I tested the issue in the following codesandboxes by simply adding the `scale-app-shell` around the given code.
[Scale and React18](https://codesandbox.io/s/scale-components-react18-75ci1x)
[Scale and Vue3](https://codesandbox.io/s/scale-components-vue3-b14993)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave (Chromium)
 - Version 1.43.89 (Chromium: 105.0.5195.102)

**Comment by tshimber** [comment]
hi! not it reproduces on 1039.20 px. should i create another issue?
![image](https://github.com/telekom/scale/assets/110041439/d847cb58-1246-4899-9a50-f86d66d373f4)

**Comment by felix-ico** [comment]
hi @JoKurth @tshimber, I just tried testing this with the new header and could not reproduce the issue (see attached video).


https://github.com/telekom/scale/assets/97440128/af727df5-da3b-4968-ae16-e683e0e73f86



Please reopen the issue if you think the header is still buggy, perhaps I misunderstood the issue.

**Comment by tshimber** [comment]
@felix-ico hi) we use old app-shell, and honestly nobody cares except me) i guess we need to move to new one if somebody will complain, so nothing from my side here, thanks!
