### ISSUE TITLE
Scale-Grid Documentation is still missing from the Storybook

### ISSUE THREAD

**Issue by Lalaluka** [telekom/scale#1211]
**Scale Version**
3.0.0-beta.56

**Framework and version**
Not relevant

**Documentation Request**
The feature `scale-grid` (not data-grid) is still missing its documentation in the Storybook. While the Custom Element is working it's only documented in a pretty old PR: #674

I would volunteer to add the Documentation but I'm not sure if it should be a component or a section in `Setup & Info` or `Guidelines` and if there is anything already in the works.

**Comment by acstll** [comment]
Hey @Lalaluka, thanks a lot!

We released it but left it undocumented a bit on purpose so we could test it and see how it felt, before making it "official".

Have you been able to use it _successfully_?

> I'm not sure if it should be a component or a section in Setup & Info or Guidelines and if there is anything already in the works.

I'm really not sure either… I think it would make more sense to have it in the Components section, but it's true it's not a "standard" component. Maybe you can try like that?

Let me know if you have any doubts. Also, if you change your mind about volunteering, just say so. In any case, thanks in advance 🙏

**Comment by Lalaluka** [comment]
I have not used it yet mainly because it was hard to find and the missing documentation stopped me to use it yet.

I will try 👍

**Comment by amir-ba** [comment]
I will close this due to it not being relevant any more
