### ISSUE TITLE
Tab navigation for tooltip is focusing it´s shadow root element

### ISSUE THREAD

**Issue by VictoriaStefanikova** [telekom/scale#1225]
**Scale Version**
3.0.0-beta.112

**Framework and version**
Angular 14

**Code Reproduction**
Hi. After implementation of tooltip component in the application, focusing with tab is behaving weird. I have noticed, that while tooltip component has tabindex = "-1", it´s shadow root element has tabindex = "0". So whenever I want to move focus from one element to the other, I have to click tab twice.

Is there some workaround how to disable focusing element in shadow root?

![image](https://user-images.githubusercontent.com/56870904/192710867-05a7c206-fbcf-40a9-9b73-f030a73475a1.png)

**Comment by acstll** [comment]
Hi @VictoriaStefanikova, thanks a lot for opening this. This is a known issue. It has been fix in a working branch https://github.com/telekom/scale/pull/1170 — so it should be released soon.

Could you maybe check the Tooltip in this preview link to double check it's exactly what you mean? https://telekom-scale-storybook-preview-pr-1170.onrender.com/

**Comment by VictoriaStefanikova** [comment]
Hi @acstll. Thank you for the answer, however, the link you provided opens home screen of Telekom Scale, therefore I am not quite sure what to check.

**Comment by acstll** [comment]
Oh sorry I did not clarify, it's the home screen but for a specific branch which includes the fix (not the latest release). There you can scroll down in the left menu and find the Tooltip, in the Beta Components section. There you can test a bit how tab navigation works.

**Comment by VictoriaStefanikova** [comment]
Thank you for clarification, I understand now and after test I can confirm that this is exactly what I mean by this issue. Thank you

**Comment by acstll** [comment]
Perfect, thanks again for reporting, and testing. Will post here when the fix is released.

**Comment by goatfryed-holos** [comment]
Hello, is there any news on when will the fix be released?

**Comment by acstll** [comment]
> Hello, is there any news on when will the fix be released?

hey, a fix is merged… it'll be released pretty pretty soon!

**Comment by acstll** [comment]
Closing now since release is imminent. Please re-open if after testing you still have the bug.
