### ISSUE TITLE
Not able to hide default html tooltip from Telekom logo

### ISSUE THREAD

**Issue by VictoriaStefanikova** [telekom/scale#1233]
**Framework and version**
Angular 14

**Code Reproduction**
Hi. I am currently using scale-tooltip component over the main Telekom logo in top left corner. The issue I am facing is, that while the tooltip is working as expected, I can see other html tooltip as well. I can not remove it with setting  logo-title attribute to empty string.

Can you suggest some workaround or working solution? Thank you.

![image](https://user-images.githubusercontent.com/56870904/193250393-ef35bad8-8ccf-4028-87a2-324b9ba2b4e6.png)

![image](https://user-images.githubusercontent.com/56870904/193250445-0ef33f91-6481-4cfc-a844-821c091a44e5.png)

**Comment by marvinLaubenstein** [comment]
Hi @VictoriaStefanikova, in the next releases there will be a possibility to hide the logo title with the prop `logoHideTitle`. 
If there is still a problem after that please don't hesitate to reopen the ticket.
