### ISSUE TITLE
Data Grid sorting does not work as expected

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1257]
**Scale Version**
v3.0.0-beta.114 - latest at the time of writing

**Framework and version**
Any

**Current Behavior**

Clicking on the sort button in Data Grid table header will switch between 3 states:

- sorted in ascending order
- sorted in descending order
- unsorted - UI doesn't show this in any special way - either sorted by ascending or descending order icon is shown (small arrow-like icon pointing up or down)

**Expected Behavior**

Clicking the sort buttons in Data Grid table header should switch between 2 states:

- sorted in ascending order
- sorted in descending order

**Code Reproduction**

Can be reproduces also in Storybook: https://telekom.github.io/scale/?path=/docs/components-data-grid--standard

**Comment by nowseemee** [comment]
is this really a bug we should fix?

**Comment by felix-ico** [comment]
@nowseemee maybe we need some UX feedback but I thought that sorting between three different states (ascending/descending/no sorting) is unexpected behavior.

**Comment by nowseemee** [comment]
@mato-a good point, thanks for posting an update - we should discuss this within the team together with @felix-ico 🙌🏻

**Comment by felix-ico** [comment]
hi @mato-a this should be fixed in the next release https://github.com/telekom/scale/pull/1396
