### ISSUE TITLE
Scale dropdown in system dark mode is visually broken

### ISSUE THREAD

**Issue by Fanky9** [telekom/scale#1279]
**Scale Version**
v3.0.0-beta.114

**Framework and version**
any

**Current Behavior**
same bug as #1018 but for system dark mode.
![image](https://user-images.githubusercontent.com/115473672/195010410-6dfabacc-0fab-4fad-9c31-0f6aa784ec40.png)
in the (#1059) is only  fix for ` data-mode` and not `@media (prefers-color-scheme: dark)`

**Code Reproduction**
Set dark mode for apps in windows and open [example](https://codesandbox.io/s/scale-components-react18-forked-sf7q3j?file=/src/App.js)

**Comment by felix-ico** [comment]
Hello @Fanky9 this is a known issue and is due to the system styles for elements such as dropdowns (different browsers render them differently). There is a new beta component "dropdown select" that aims to fix this issue https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard. Would you mind giving that a try?

**Comment by Fanky9** [comment]
You can add this in dropdown styles and it will be fixed.
```
@media (prefers-color-scheme: dark) {
  .dropdown .input__dropdown {
    background-color: var(--telekom-color-background-canvas);
  }

  .dropdown:not(.dropdown--disabled):not(.dropdown--status-error) .input__dropdown:hover {
    background-color: #1b1b1b;
  }

  .dropdown:not(.dropdown--disabled).dropdown--status-error .input__dropdown:hover {
    background-color: #1b1b1b;
  }

  .dropdown--disabled .input__dropdown {
    background-color: var(--telekom-color-background-canvas);
  }
}
```
as u fixed it for [data-mode='dark'] (#1059) 

And if u don't fix this than probably yes i'll try to use a new one .

**Comment by felix-ico** [comment]
hi @Fanky9, I'm sorry obviously I had misunderstood the issue. I added your code snippet (thanks for that) to my PR here https://github.com/telekom/scale/issues/1279, should be available in the next release.

**Comment by felix-ico** [comment]
@Fanky9 I'd still suggest using the new dropdown component if at all possible as that follows the new design guidelines and is more future-proof (we will eventually replace the old dropdown for the new one and deprecate the legacy version).
