### ISSUE TITLE
Scale link has no focus effect

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#1284]
**Scale Version**
3.0.0-beta.114

**Framework and version**
No framework

**Current Behavior**
When focusing a Scale link component(either with tab or just holding a click) no visual feedback is present.

**Expected Behavior**
I expect to have a visual feedback(a border for example) when focusing a Scale link component.

**Code Reproduction**
<scale-link href="#">Some link</scale-link>

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 106.0.5249.103

**Comment by goatfryed-holos** [comment]
Any news on this?

**Comment by georgwittberger-telekom-mms** [comment]
In Scale version 3.0.0-beta.136 there is an outline when links are focused. You can verify here: https://telekom.github.io/scale/?path=/docs/components-link--standard

**Comment by felix-ico** [comment]
thank you @georgwittberger-telekom-mms and sorry @goatfryed-holos for the long wait, i will close this issue
