### ISSUE TITLE
Radio Button Spacing indicates click-ability but has no affect

### ISSUE THREAD

**Issue by Lalaluka** [telekom/scale#1294]
**Scale Version**
Scale 3.0.0-beta.114

**Framework and version**
vue 3

**Current Behavior**
https://user-images.githubusercontent.com/26364692/196924003-e5f15986-8aaa-436c-97f2-f22818f3ee22.mov
If I click in between the radio button and the label the mouse cursor indicates a click area, but if I click nothing happens.

A clear description of what the bug is and how it manifests.

**Expected Behavior**
It would be expected that the full click area 

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

Can be reproduced in the [storybook](https://telekom.github.io/scale/?path=/docs/components-radio-button--standard). 

**Desktop (please complete the following information):**
 - OS: MacOs & Windows
 - Browser Chrome
 - Version 104.0.5112.79

**Comment by marvinLaubenstein** [comment]
Good morning Calvin. 
Thanks for pointing out this problem. I was able to reproduce it and will take care of it, asap.

**Comment by marvinLaubenstein** [comment]
Hi @Lalaluka, the solution for this problem should be included in the next releases. 
If there is still an issue, feel free to reopen the issue ticket.

**Comment by marvinLaubenstein** [comment]
Hi @Lalaluka,
Thank you for drawing attention to the problem again. Unfortunately it was not included in the version update to version `@3.0.0-beta.117` I'm sorry.

I just tested it with version `@3.0.0-beta.118`. Now it should work 🙂.
