### ISSUE TITLE
Scale heavily influences Memory Usage

### ISSUE THREAD

**Issue by telion2** [telekom/scale#1319]
**Scale Version**
3.0.0-beta.114

**Framework and version**
2 Projects in Vue 2: 
-  "vue": "^2.6.11",
- "vue": "^2.6.12",
We only recently (last week) introduced Scale to both Projects that already run in Production. 
We followed the documentation: 
```
import { defineCustomElements } from "@telekom/scale-components/loader";
import "@telekom/scale-components/dist/scale-components/scale-components.css";

defineCustomElements();
```

We currently were only using the footer like this: 
```
<template>
  <footer class="brand-footer-bar" role="contentinfo">
    <div class="container-fixed">
      <scale-app-footer id="footer" copyright="© 2022 Telekom Deutschland GmbH" variant="minimal">
      </scale-app-footer>
    </div>
  </footer>
</template>

<script>
import querify from "@/mixins/querify.js";

export default {
  name: "tele-footer",
  mixins: [querify],
  mounted() {
    const footer = document.getElementById('footer');
    footer.footerNavigation = [
      {
        name: this.$t("footerContact"),
        id: 'Contact',
        href: "https://geschaeftskunden.telekom.de/startseite/kontakt/288260/kontakt.html"
      },
      {
        name: this.$t("footerTermsOfUse"),
        id: 'Terms and conditions',
        href: "https://www.telekom.de/agb",
      },
      {
        name: this.$t("footerImprint"),
        id: 'Legal notice',
        href: "https://geschaeftskunden.telekom.de/impressum"
      },
      {
        name: this.$t("footerDataPrivacy"),
        id: 'Data privacy',
        href: this.dataPrivacyUrl,
        icon: 'alert-imprint-dataprivacy',
      },
    ];
  }
};
</script>
```

**Current Behavior**
We have been deploying our Vue-Apps as a Docker Image on Openshift 4 for ~2 years. 
We configured our Pods to use a 150mib memory limit. 
Since last week and the introduction of scale we have seen instabilities due to increased memory usage. 
Basically, our pods were "OOMkilled", which means, that the pods died because of exceeding the memory limit. 
We, therefore, increased the memory limit to investigate. 

Initially, we had memory usages up to 600mib, while simply opening the UI with multiple Browser Tabs. 
(We set the browser to not cache requests and we opened 15 Browser Tabs repeatedly to get 600mib)

However, that was not controlled enough so we made an experiment, where we compared our Production environment, which didn't receive the scale update yet, with the test Environment. 

Note that the pods have the exact same configuration, as the test environment. 
Note that we admit, that the experiment is a black-box A-B-Test, so it could also be the way we use scale or something entirely different. 

The result: 
The Memory in the Production Environment barely changed. It fluctuated between ~44mib to 90mib with a limit at 150mib. 
The Memory in the test environment that uses scale had big changes: 44mib to 250mib with a limit of 1000mib. 
But the pod would have died if the limit was 150mib.   

Now the quick fix would be increasing the memory limit, but that would greatly increase our costs. 
(We can of set that with autoscaling of course but still)

We also noted a very high increase in requests to the servers. In Production, a simple opening of the UI uses 27 Requests. With scale, it goes up to 286 Requests, with is more than a 10 times increase. However, this does not explain the increase in memory usage.  
This causes another Issue though: The WAF, the Telekom DDOS-Detection System flags that if you reload too often. 
I will create another ticket for that though. 

To sum it up: 
Since the use of scale, our memory usages have almost tripled (in a controlled experiment), which causes an increase in costs.

I already tried to analyze the code of scale to find out what happens but I can't find out what `defineCustomElements` exactly comes from and what it does. 

**Expected Behavior**
- Using scale does not influence memory usage that heavily. I think I would expect an average increase of 50mib in our case.  
- Using scale does not make the memory usage fluctuate so much. 
Especially if only one component is used.

**Comment by acstll** [comment]
Closing this one as resolved, as in https://github.com/telekom/scale/issues/1327 🙏
