### ISSUE TITLE
Scale Causes 10 Times more Requests when Loading the Page

### ISSUE THREAD

**Issue by telion2** [telekom/scale#1327]
See https://github.com/telekom/scale/issues/1319 for Code and Context.

**Current Behavior**
The UIs that use scale make up to 10 times more calls. 

This screenshot shows 280 requests when simply loading the page: 
![Screenshot from 2022-10-28 12-02-28](https://user-images.githubusercontent.com/30474592/198562556-81669ff6-829a-43f4-b39c-885dfc42899c.png)

Compared to the ~27 requests that are usually called without scale: 
![Screenshot from 2022-10-28 12-14-37](https://user-images.githubusercontent.com/30474592/198563758-73ee8b78-0d05-4983-b0c2-5f614d0567bd.png)

Here would be a sample Response of one of the requests: 
[ScaleSampleRequest.txt](https://github.com/telekom/scale/files/9887447/ScaleSampleRequest.txt)

**Expected Behavior**
I would accept an increase of ~10-20 requests but not ~255 more. The problem is that this causes DDOS Detection Systems to trigger. 
In particular the WAF (web application firewall) of Telekom. 
We build our vue apps with vue cli, so I would have expected for Scale to be part of the build and not loaded separately. 
Admittedly not the first load, but if you use multiple tabs on different web pages that use scale the chances are high that you get blocked as a normal user. 
It also could be the root cause of https://github.com/telekom/scale/issues/1319 however I have my doubts there.

**Comment by telion2** [comment]
I forgot to mention: 
The number of requests isn't necessarily fixed. 
This means sometimes, the number of requests can be lower, but I don't know yet, on what it depends.

**Comment by maomaoZH** [comment]
Hi @telion2 ,

Thanks for reporting this issue. I see there was a discussion between you and @acstll . Starting from version `3.0.0-beta.114`, we have mechanism that allow you to do the "code split" style, meaning you only import the components you need. see here: https://github.com/telekom/scale/pull/1202.
In your case, you use only footer component atm, therefore, you can try to do as following:
```
import { defineCustomElementScaleAppFooter } from '@telekom/scale-components';
defineCustomElementScaleAppFooter() // only `<scale-app-footer>` is loaded
```
Please let me know if this can reduce the massive number of requests and help you to resolve your issue. 

Regards,
Maomao

**Comment by telion2** [comment]
Hi, thank you for the reply. I will try that out. 

Since both Issues blocked our Production Deployment, I had to remove Scale to solve our change freeze. 
Meaning now I need to reintegrate Scale. But don't worry, I will do that but I need a bit of time.

**Comment by telion2** [comment]
Well, I was curious and I realized that I still had a branch with scale integrated.
I initially though it would take more time. 
So I made a little test, but I soon run into this: 
![Screenshot from 2022-10-31 11-12-38](https://user-images.githubusercontent.com/30474592/198985209-80352b10-d41b-4e49-bc7e-4238b8c6b248.png)
![Screenshot from 2022-10-31 11-13-01](https://user-images.githubusercontent.com/30474592/198985205-fe767c1b-5f70-423a-9647-6066c9fd09af.png)

=> defineCustomElementScaleAppFooter might be the wrong name. 
I couldn't find the correct name in the documentation though.

**Comment by maomaoZH** [comment]
Hi @telion2 , please don't import from `@telekom/scale-components/loader` but directly from `@telekom/scale-components`.  We have not. updated the documentation yet. This will come soon.

**Comment by maomaoZH** [comment]
Sure thing. Glad to help.

**Comment by acstll** [comment]
Thank you @maomaoZH for the awesome support 🙏 

> and it seems, that it also resolved the memory Issue of https://github.com/telekom/scale/issues/1319.

that would be actually great!

Regarding the 2 remarks:

> Having to call `defineCustomElementScaleAppFooter()` or similar functions can be a bit awkward. Basically, if I import a component I would expect the function `defineCustomElementScaleAppFooter()` to be called during the import if possible.

I completely agree. I do not know the reason why Stencil went this route. Some libraries offer both, they export the class, so you could define it yourself, plus an extra import that already defines the component. Sadly, this is not an option at this very moment.

> `defineCustomElements()` should only load what is necessary

this is how it actually works already, only the components used are loaded lazily… (see https://stencil.docschina.org/blog/how-lazy-loading-web-components-work), but for some reason on your environment (as well as on another project in which @maomaoZH works) all these way-too-many unexpected calls are happening. This I would like to further investigate…

Thanks again for taking the time to provide further feedback @telion2

**Comment by acstll** [comment]
I did some more testing and I would like to share the results.

In a Vue 2 app made with vue-cli (wepback), the production bundle outputs one JavaScript per component in the Scale library, that is roughly 250 files, including the ~200 icons.

The test app uses only the Scale Footer, as in #1319. It behaves as expected:
- the bundle includes ~250 JavaScript files
- only 2 of these are loaded initially
- 4 more files are loaded lazily (the actual footer and 3 dependencies including icons), for a total of 6

I deployed this test app to a static server and it behaves the same.

The only difference I can see with your setup, is that the requests in your case are [initiated by "other"](https://stackoverflow.com/a/35422293) and not the app itself (please see the Initiator column in DevTools).

@maomaoZH, @telion2 what do you think that could be, in your production environments, causing all these files to load unnecessarily?

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/851105/199755311-798b4d99-ddf8-475c-af15-450dc0e7c405.png">

**Comment by maomaoZH** [comment]
Hi @acstll , the test you did above, did you call `defineCustomElements()` ? And it loads only 6 files?

**Comment by telion2** [comment]
The scripts in your screenshot look similar to those of mine. In my case, they have different names in various environments. 
I have also seen them in this name format: 
1.js
...
270.js

but sometime the run under different names like the screenshots above. 

Also note the number of files loaded, was not always the same. I had instances where it loaded few files.

**Comment by acstll** [comment]
> Hi @acstll , the test you did above, did you call `defineCustomElements()` ? And it loads only 6 files?

Yep. That's the expected behavious. I'm pasting some code below:

```js
// entire main.js file
import Vue from 'vue'
import App from './App.vue'

import '@telekom/scale-components/dist/scale-components/scale-components.css'
import { defineCustomElements } from '@telekom/scale-components/loader'

defineCustomElements()

Vue.config.productionTip = false

new Vue({
  render: h => h(App),
}).$mount('#app')
```

```vue
<!-- App.vue -->
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
    <footer class="brand-footer-bar" role="contentinfo">
      <div class="container-fixed">
        <scale-app-footer id="footer" copyright="© 2022 Telekom Deutschland GmbH" variant="minimal">
        </scale-app-footer>
      </div>
    </footer>
  </div>
</template>
```

**Comment by maomaoZH** [comment]
It seems lots of requests are caused by vue prefetch. see more https://cli.vuejs.org/guide/html-and-static-assets.html#prefetch. When I disable prefetch in my project config file, the issue is gone. <br>
In summary, i can either: <br>
1 partially load the components with prefetch config
2 disable prefetch config and use `defineCustomElements()` method
