### ISSUE TITLE
Radio Button Group, Accessability Issue: Tabbing through the elements of the group doesn't work

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#1349]
**Scale Version**
3.0.0.-beta.116 (22-10-31)

**Framework and version**
N/A (it's possible to reproduce the problem in the Scale design system directly (https://telekom.github.io/scale/?path=/story/scale-design-system--page&globals=locale:en;colorMode:light)  

**Current Behavior**
Using the tab key for navigation you can't access the not selected elements of the radio button group.

**Expected Behavior**
Using the tab key for navigation it should be possible (as a matter of accessability) to reach all elements of the radio button group, the selected one as well as the non selected ones.

**Code Reproduction**
N/A 

**Desktop (please complete the following information):**
 - Windows]
 - Browser: Chrome
 - Version 106.0.5249.119

**Smartphone (please complete the following information):**
  N/A

**Additional context**
N/A

**Comment by felix-ico** [comment]
Hi @UBOrange thanks for reporting this and sorry for the late reply. 

As far as I understand it this is how radio button groups should behave in regard to accessibility: you can use the tab key to navigate between radio button _groups_ but to navigate between individual radio buttons you should use the arrow keys. 

I had a look at https://www.w3.org/wiki/RadioButton and https://www.w3.org/WAI/ARIA/apg/example-index/radio/radio-activedescendant.html which confirm this behavior. Please let me know if you know of conflicting specs in regard to radio-button accessibility.

**Comment by marvinLaubenstein** [comment]
Hi @UBOrange , I took a look at our Radio-Button-Group and could not find any functionality error. 

A Radio-Button-Group is always entered via Tab (Alt+Tab), within the group it is designed to navigate through it with the arrow keys. 
If no Radio-Button has been selected yet, the focus jumps to the first element of the group. However, if a Radio-Button is selected, the focus is placed directly on the selected Radio-Button. From there the other radio buttons can be reached by using the arrow keys. 

I hope I could help you a little bit. If you still notice something wrong, feel free to contact me/us again.

**Comment by felix-ico** [comment]
Closing as resolved, but please feel free to re-open
