### ISSUE TITLE
Add property "name" to DropdownSelect component

### ISSUE THREAD

**Issue by filipjnc** [telekom/scale#1360]
**Describe the feature request**
For the component DropdownSelect to be useful in a form, it has to have a form element with a name and the selected value. This could be e.g. a hidden input element, that takes the name from the name-property and contains the value of the selected option from the listbox.

**Comment by tommy-codez** [comment]
Hi- I second that. 
How it is supposed to be done when you want to access this field for example with event.target.?? - I was surprised that the name attribute is not there ...

Greetings
