### ISSUE TITLE
Localization not working for date picker calendar heading

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#1362]
**Scale Version**
3.0.0-beta.117

**Current Behavior**
When changing localization for date picker after it has loaded, all texts are changes beside the calendar heading(popup title).

**Expected Behavior**
I expect to be able to also change the calendar heading text. after the component has loaded.

**Code Reproduction**
https://codesandbox.io/s/scale-components-plain-html-template-forked-nvybqw

**Comment by maomaoZH** [comment]
Hi @pomoalex ,
Thanks for reporting this issue. I have looked into your code sample. You set timeout 1000ms. At the time when title is rendered, the new props title value is not assigned yet. Therefore it returns the default value which is expected. 
May i ask the reason why you set timeout 1000ms?

Regards,
Maomao

**Comment by pomoalex** [comment]
Hi,
I set the value just as an example. In my code I had some logic before setting the localization, time in which the component got loaded, and so I bumped into this issue. I moved the localization change before the other logic and it works, but I just wanted to let you know of this issue. If I needed to change the localization dynamically (let's say by a drop down where the user picks the desired language) then it would not work.

Best regards,
Alexandru Pomohaci    Pe miercuri, 16 noiembrie 2022, 11:03:29 EET, Maomao ***@***.***> a scris:  
 
 


Hi @pomoalex ,
Thanks for reporting this issue. I have looked into your code sample. You set timeout 1000ms. At the time when title is rendered, the new props title value is not assigned yet. Therefore it returns the default value which is expected.
May i ask the reason why you set timeout 1000ms?

Regards,
Maomao

**Comment by lukascorona** [comment]
For anyone having this issue:
when using an underlying framework, you could just assign the selected localization as a key of the date picker. So every change will force a rerender of that component.

**Comment by maomaoZH** [comment]
Hi, @pomoalex  i would suggest the same from @lukascorona . Assigning props to the component would make it dynamically.

**Comment by felix-ico** [comment]
Closing as resolved, but please feel free to re-open if needed
