### ISSUE TITLE
Configurable Screen Reader alt-text for "open profile menu"

### ISSUE THREAD

**Issue by maiktal** [telekom/scale#1371]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
The screen reader reads only the name displayed on profile menu. 

**Expected Behavior**
An alternative Text for the screen reader with the intention to open an profile menu for the user
can be configured at the component.

**Code Reproduction**
See the picture.

![image](https://user-images.githubusercontent.com/118713833/202983168-4e2f5009-393a-47de-b2ec-32364782367d.png)

**Desktop:**
 - OS: Windows 10
 - Browser CHROME
 - Version 107.0.5304.107 (Offizieller Build) (64-Bit)

**Additional context**
For us its a major problem because for SR users this feature is unusable! (we tested it with a blind person)

**Comment by felix-ico** [comment]
closing this issue as it refers to the deprecated brand header. As always feel free to reopen if it's still relevant to you
