### ISSUE TITLE
Persistent focus

### ISSUE THREAD

**Issue by nau12345** [telekom/scale#1374]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Any

**Current Behavior**
When a component is selected the focus border does not disappear.
This issue can be observed inside the scale website.
https://telekom.github.io/scale/?path=/docs/components-button--standard
![image](https://user-images.githubusercontent.com/118267635/203103487-c1073032-7eb0-4ef2-bd8d-806f762c6def.png)

**Expected Behavior**
The border focus should dissapear a few seconds after selecting a component.

Example https://material.angular.io/components/button/overview

**Comment by felix-ico** [comment]
hi @nau12345 I think that this is the desired behaviour for the focus outline, which only disappears if the user selects another element or clicks on an empty space. I could not find any specifications for the focus pseudo-class that mention that the focus outline should disappear after a certain amount of time, and the example from material ui does actually not show any focus outline for me (see screenshot).

<img width="247" alt="Screenshot 2022-11-24 at 11 52 04" src="https://user-images.githubusercontent.com/97440128/203767588-dd15354e-34d1-4134-988d-ceb049e29d69.png">

**Comment by felix-ico** [comment]
Closing as resolved, but please feel free to re-open
