### ISSUE TITLE
Max Length With Counter error handling

### ISSUE THREAD

**Issue by robertgebhard** [telekom/scale#1385]
Hey, I in the role of UX designer would like to offer users a text field with Max Length With Counter so that they know how many characters they can enter.

With a view to good UX, I noticed two things that you could perhaps integrate by default, instead of each project developer having to develop this individually.

**1. some users might not understand the display "0/10". Better would be a text like "10 characters left".**

Now:
<img width="1090" alt="Bildschirmfoto 2022-11-25 um 09 08 59" src="https://user-images.githubusercontent.com/95682620/203932773-6141c5ed-6bd7-4d46-9b23-a24c9cfa1cdc.png">

Better:
<img width="1084" alt="Bildschirmfoto 2022-11-25 um 09 09 16" src="https://user-images.githubusercontent.com/95682620/203932815-37833283-7e15-48e3-aae3-8b84396f42dc.png">

**2. users should be informed that they have written too much. Now, apart from "10/10", there is no other meaningful feddback, such as "15/10" or better "5 characters over".**

Now:
<img width="1091" alt="Bildschirmfoto 2022-11-25 um 09 15 24" src="https://user-images.githubusercontent.com/95682620/203933329-a453e35f-e768-4843-933a-1e144bed613b.png">

Better:
<img width="815" alt="Bildschirmfoto 2022-11-25 um 09 19 40" src="https://user-images.githubusercontent.com/95682620/203934072-919d6e46-cc56-48c2-98bb-ccec7dd5fb2f.png">

Thank you very much for your work.
Best regards

**Comment by felix-ico** [comment]
Hi @robertgebhard thanks for the feedback, we are looking into various improvements for the text-fields and will discuss this topic as well. I am closing the issue as it is linked in a new "aggregate" issue
