### ISSUE TITLE
Property "accessibilityTitle" is deprecated. Please use the "logoTitle" property!

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1386]
**Scale Version**

3.0.0-beta.117

**Framework and version**

any

**Current Behavior**

A lot of errors in web console:

```
 scale – 😵 Deprecation notice  

Property "accessibilityTitle" is deprecated. Please use the "logoTitle" property! 
```

**Expected Behavior**

no errors in console

**Code Reproduction**

The errors in console are visible also in live preview: https://telekom.github.io/scale/?path=/docs/components-logo--standard

**Additional context**

The problem is that the error is not coming from the user code - I have tried searching the whole project for string `"accessibilityTitle"`, but could not find any. Probably the error is coming from internal usage of scale-logo by some of the framework components.

**Comment by marvinLaubenstein** [comment]
Hi @mato-a, thanks for the info. I will have a look at it

**Comment by marvinLaubenstein** [comment]
This issue should be fixed by the next release, if not please reopen the ticket.
