### ISSUE TITLE
Mobile menu icon label + unnecessary 2nd level of navigation

### ISSUE THREAD

**Issue by wgmaik** [telekom/scale#1402]
Scale Version
3.0.0-beta.117

Framework and version
Angular 14

**Current Behavior**
Currently the menu icon label is fixed to the text "close". This should be conffigurable.
Unnecessary 2nd level of navigation in mobile menu even if only one is defined.

**Expected Behavior**
Should be possible to configure a label for the mobile menus' close icon.
There should be no second level of navigation in mobile menu when only on level exists.

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

**Desktop (please complete the following information):**

**Comment by wgmaik** [comment]
The label of the mobile menu "Menu" should be configurable via attrbute too.

**Comment by acstll** [comment]
@wgmaik for the issue with the 2nd level a PR with a fix is underway 🤓

Regarding the labels for the menu icon, I think this is possible to configure already. Please let me know in case I misunderstood…

You can include an object in the array for the `iconNavigation` prop with the keys `defaultName` for the idle state, and `openedName` for the open state, e.g.

```js
appHeader.iconNavigation = [
  {
    …
  },
  {
    id: 'menu',
    defaultName: 'Menü',
    openedName: 'Schließen',
  },
]
```

Does this solve the issue?

(We'll ping you again when the PR is merged and release together with a few others…)
