### ISSUE TITLE
Some css issues with notification banner

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#1418]
Hello! I know that component is wip, but my team asked me to report this, 'cause we may need this functionality soon.
Somehow I can't paste screenshot, pity/

**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
1. Strange large main text line hight --> if main text is long and got multilined, it looks bad
2. Link on separate line (if there are 'text' and 'link' slots) affects margin of the whole component --> multiple banners with and without link will have different bottom margins 

**Expected Behavior**
Thesw 2 are fixed

**Code Reproduction**
<div
    class="wrapper"
    style="width: 300px;"
>
    <div class="notification-wrapper">
        <scale-notification-banner
            variant="warning"
            dismissible
            opened
        > Notification text goes here. <p slot="text">Here you can add some more text. Here you can add some more text.
                Here you can add some more text. Here you can add some more text. Here you can add some more text. Here
                you can add some more text. Here you can add some more text. Here you can add some more text. Here you
                can add some more text. </p>
            <p slot="link">Link Text</p>
        </scale-notification-banner>
    </div>
    <div class="notification-wrapper">
        <scale-notification-banner
            dismissible
            opened
        > Notification text Notification text goes here. <p slot="text">Here you can add some more text. Here you can
                add some more text. Here you can add some more text.</p>
        </scale-notification-banner>
    </div>
    <div class="notification-wrapper">
        <scale-notification-banner
            dismissible
            opened
        > Notification text goes here. <p slot="text">Here you can add some more text.</p>
        </scale-notification-banner>
    </div>
    <div class="notification-wrapper">
        <scale-notification-banner
            dismissible
            opened
        > Notification text goes here. <p slot="link">Link Text</p>
        </scale-notification-banner>
    </div>
</div>

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 107.0.5304.122

**Smartphone (please complete the following information):**
х

**Additional context**
х

**Comment by marvinLaubenstein** [comment]
Hi @tshimber, I took a look and you are definitely right. I will fix this. 
Thanks for pointing this out.
