### ISSUE TITLE
Lighthouse findings - Wrong HTML

### ISSUE THREAD

**Issue by wgmaik** [telekom/scale#1421]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
Following things are criticized by lighthouse:

1. missing role="menuitem" in elements of app-navigation-user-menu:
![image](https://user-images.githubusercontent.com/10576372/208049233-12e87004-7732-4c5a-a01b-5e3f013c165a.png)

2. lists should only contain LI child elements:
![image](https://user-images.githubusercontent.com/10576372/208049350-824d6f65-02ca-41b8-ac1a-1a284daa602d.png)

**Expected Behavior**
Add role and fix HTML.

**Desktop (please complete the following information):**
OS: Windows 10
Browser CHROME
Version 107.0.5304.107 (Offizieller Build) (64-Bit)

**Comment by felix-ico** [comment]
closing this issue as it refers to the deprecated app-header, please use scale-telekom-header that has been reviewed for accessibility. 

feel free to reopen the issue if you think it's still relevant
