### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by wgmaik** [telekom/scale#1423]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
1. Label for Telekom logo is hard coded
2. Configurable IDs for NavMain elements
3. Remove horizontal padding in main menu (item is highlighted when padding is onHover, but not yet clickable):
![image](https://user-images.githubusercontent.com/10576372/208057875-34628d92-e33b-4232-b5f3-6480481437cd.png)

**Expected Behavior**
- Configurable label for telekom logo svg
- ID attribute for nav elements to support automated ui testing with e.g. selenium (ids should be possible for all elements!)
- Fix css of padding + clickable area in main nav

**Desktop (please complete the following information):**
OS: Windows 10
Browser CHROME
Version 107.0.5304.107 (Offizieller Build) (64-Bit)

**Comment by felix-ico** [comment]
Hi @wgmaik we just merged a PR to address some of these issues https://github.com/telekom/scale/pull/1614: 

1- I think this was already possible through the `logoTitle` prop in the brandHeader 
<img width="1141" alt="Screenshot 2023-02-23 at 12 17 46" src="https://user-images.githubusercontent.com/97440128/220891540-4fcfa0f6-b588-47f8-ac6d-1693b2580e20.png">

2- Nav Main elements should now have a unique ID (that is set through the mainNav array)
3- Fixed the padding issue

These should all be available in the next release

**Comment by felix-ico** [comment]
closing this as https://github.com/telekom/scale/pull/1614/files has been merged
