### ISSUE TITLE
Tooltips set on icons can not be activated via keyboard

### ISSUE THREAD

**Issue by wgmaik** [telekom/scale#1424]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
Tooltips set on icons can not be activated via keyboard

**Expected Behavior**
Tooltips set on icons can be activated via keyboard

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser CHROME
- Version 107.0.5304.107 (Offizieller Build) (64-Bit)

**Comment by VictoriaStefanikova** [comment]
Is there any progress with the solution to this issue? I am facing the same problem.

**Comment by felix-ico** [comment]
quick update: there is a [PR](https://github.com/telekom/scale/pull/1610) to add 
 `focusable` to the scale icon-library so this will be possible: 
 
```
<scale-tooltip content="Tooltip">
    <scale-icon-action-favorite  focusable/>
</scale-tooltip>
```

without need for the above workaround

**Comment by verdody** [comment]
Thank you @felix-ico for the fix. However, I think I am using the lower version of Scale, so the above fix is not working. Can you please send me the link where I can find information about releases and what was included in each release? Thank you.

**Comment by felix-ico** [comment]
Hi @verdody we normally release information here about the updates here https://telekom.github.io/scale/?path=/docs/update-history-development--page,  but that only contains major new features. For bugfixes we mainly communicate them through the github issues. 

If you would like to have the current `focusable` icon you should install the latest version [3.0.0-beta.126](https://www.npmjs.com/package/@telekom/scale-components/v/3.0.0-beta.126), and in general I would suggest always using the latest scale version unless there are some constraints that do not allow you to do so.
