### ISSUE TITLE
Focus should behave consistently on all elements

### ISSUE THREAD

**Issue by wgmaik** [telekom/scale#1425]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
In chrome currently different colors when hovering cards, scale-links, icons, ...

**Expected Behavior**
Consistent display of focus.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser CHROME
- Version 107.0.5304.107 (Offizieller Build) (64-Bit)

**Comment by felix-ico** [comment]
Hi @wgmaik thanks for opening the issue. Do you mean the outline on focus or the hover states? I think the focus outline is already pretty consistent across scale components, but the hover state may differ slightly.

**Comment by wgmaik** [comment]
Hi, the point is: navigation per keyboard tab - focus differs between elements! (Compare focus when tabbing through main-nav(black focus) vs. tab-nav(blue focus) )

**Comment by felix-ico** [comment]
Hi @wgmaik I'm still not sure I understand the issue, I'm adding some screenshots here, both focus outlines look the same to me:
<img width="539" alt="Screenshot 2023-01-18 at 15 28 49" src="https://user-images.githubusercontent.com/97440128/213197756-e572e6e0-9461-47f3-9685-68b067b80127.png">

<img width="693" alt="Screenshot 2023-01-18 at 15 28 38" src="https://user-images.githubusercontent.com/97440128/213197767-ccf13e16-6453-4b93-ac3a-9de82012aacc.png">

or did you mean something else?

**Comment by felix-ico** [comment]
this should be available from the next release

**Comment by sulyok-daniel** [comment]
Thank you, now (Scale 3.0.0.beta-130) almost all components we use behave consistently.
One remaining issue is with the close-button on dismissible notification banners, where no focus style is defined, so the browser's default style (`:focus-visible`) is used, see screenshot below:

![image](https://user-images.githubusercontent.com/2097315/232465448-70bf7749-35ea-404a-a878-b7b2f1c82a79.png)
