### ISSUE TITLE
Button disabled property doesn't work if the button is link

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1427]
**Scale Version**
v3.0.0-beta.117

**Framework and version**
any

**Current Behavior**
If the `href` attribute is set on scale button (button is link) the `disabled` attribute has no effect.

**Expected Behavior**
It should be possible to disable also button links.

**Code Reproduction**
Try setting `disabled` to `true`, and then set/unset `href`
https://telekom.github.io/scale/?path=/docs/components-button--standard

**Comment by felix-ico** [comment]
this should be fixed in the next release https://github.com/telekom/scale/pull/1430
