### ISSUE TITLE
Icons invisible in high contrast white mode

### ISSUE THREAD

**Issue by goatfryed-holos** [telekom/scale#1442]
**Scale Version**
3.0.0-beta.110

**Framework and version**
The bug happens framework independent

**Current Behavior**
If the users enables windows accessibility high contrast mode in light variant, the scale-button in icon only mode have no visible icon.

**Expected Behavior**
The icon is visible in black

**Code Reproduction**
[View the scale icon documentation after enabling high contrast mode in white design on windows](https://telekom.github.io/scale/?path=/docs/components-icon--standard)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 104

**Comment by marvinLaubenstein** [comment]
Hi @goatfryed-holos , thanks for noticing. I have tried to reproduce your issue but without success. For me the icons are visible (light mode + win10 + chrome + high-contrast). 
Could you possibly show me a picture before and after enabling the "Enable high contrast"? Thanks in advance

<img width="577" alt="high_contrast_test_chr_win10_light" src="https://user-images.githubusercontent.com/82942834/218070383-9ef36ef2-f33a-490e-94fe-e873e994c81f.png">
