### ISSUE TITLE
Text Field helperText id not unique

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#1449]
Scale Version
@telekom/scale-components 3.0.0-beta.113

Framework and version
@telekom/scale-components-react 3.0.0-beta.113

**Current Behavior**
If `ScaleTextField` is given `inputId` helper text `id` is not incremented so multiple elements receive same `id`

**Expected Behavior**
Each helper text receives unique `id`

**Code Reproduction**
https://codesandbox.io/s/heuristic-gagarin-osylzd?file=/src/App.js

![image](https://user-images.githubusercontent.com/98950408/210760704-5b5af5b9-b668-4768-bf62-2f68321e17d4.png)

**Comment by marvinLaubenstein** [comment]
Hi @nikolab-pn, thanks for reporting the issue. 
We have generally revised our helper text ids again with individual ids. This should be included in the next release.
