### ISSUE TITLE
Scale tag color styling issues after update

### ISSUE THREAD

**Issue by goatfryed-holos** [telekom/scale#1450]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Framework independent

**Previous Behavior**
Previously, it was quite easy to style scale-tag. We just had to provide --background and --color variable, if we had a non interactive simple tag that required custom colors not available in the color palette.

**Current Behavior**
After the update, if the color property is not provided the tag sets additional classes for grey color and displays itself as grey. This overrides most outside color variable configuration, because it has a quite specific selector.

**Expected Behavior**
I'd much appreciate to reintroduce the old behavior. That is, if no color property is set, no additional color classes should apply and the color variables should be set without selectors as defaults.
The current behaviour makes custom styling a real pain

**Comment by marvinLaubenstein** [comment]
Hi @goatfryed-holos, thanks for noticing the problem. Personally, I would also prefer this variant. I'll talk to our team and hopefully change it as soon as possible.
