### ISSUE TITLE
Whats the difference between notification-message and notification-banner?

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#1476]
**Scale Version**
beta-117

**Comment by marvinLaubenstein** [comment]
Hi @christopherGdynia

The distinction between the components is rather important with regard to the use case. 
 
Notifications banner communicate system messages. They are displayed above the page content. They do not require any direct action from the user and can be hidden after a certain time if desired. 

Notification message Inline notifications give users feedback on an action. They are located in the corresponding section of the page. In this case, an interaction of the user is expected or the user is told about the success of an action that has been taken as a result of his action.
