### ISSUE TITLE
ScaleIconAction show all with selected

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#1481]
Hello there,

I've noticed that `scale-icon-action-*` can be selected with `selected` prop.

This isn't well covered in the `storybook`.

Pls display these different states for the `icons`.

**Comment by marvinLaubenstein** [comment]
Hi @christopherGdynia, thanks for mentioning your issue. 

Unfortunately, it is not possible to cover/display two different component types (`scale-icon`/ `scale icon library`) with 100% of the possible use cases in the storybook. 
But of course, we want to inform the user about the possibilities of both components. You can find the possible properties for the icons of the `icon library` in the `Icon Library Example` part and the `Icon Library` option of the table (attached image).

Please be aware that there is a difference between our `scale-icon` and our `scale icon library` also in terms of the selectable properties. 

<img width="1287" alt="Bildschirm­foto 2023-02-13 um 19 52 43" src="https://user-images.githubusercontent.com/82942834/218548346-b914aefa-a986-4396-a629-14cd3aa90360.png">

**Comment by christopherGdynia** [comment]
Hello @marvinLaubenstein,

thanks for your help. This would be sufficient.

Whats the difference between these two anyway? :D

**Comment by marvinLaubenstein** [comment]
The difference between the two is simply that the scale icons can be freely chosen and the other ones are only the specific icons from our library, which are properly formatted.
