### ISSUE TITLE
Clicking on an icon in a scale-tab-nav doesn't switch the tab

### ISSUE THREAD

**Issue by Piotr-Dziekonski** [telekom/scale#1483]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Vue 3.2.45

**Current Behavior**
Nothing happens when clicking on an tab icon in the scale-tab-nav instead of the rest of the tab.

**Expected Behavior**
The tab should switch to the new one, just like when clicking on the rest of the tab.

**Comment by felix-ico** [comment]
Hi @Piotr-Dziekonski this should be fixed with this PR https://github.com/telekom/scale/pull/1594 (i can also not reproduce the issue on the latest version). Closing the issue, but feel free to reopen if it still buggy
