### ISSUE TITLE
Carousel active indicator class

### ISSUE THREAD

**Issue by marius-ionescu** [telekom/scale#150]
Hello,
Library looking really nice :)

Have just noticed a small issue on the carousel. It isn't setting the correct active class(or rather doesn't use classes to get the dynamic class) on the indicators and so the opacity it should show(1) isn't being applied.

I can raise a PR for this if that's ok, and perhaps a test for it as well.

**Comment by eeegor** [comment]
Hi @marius-ionescu, thanks for opening the issue! If you can raise a PR we would be very happy :)
