### ISSUE TITLE
Data Grid: small style fix in pagination

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#1528]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular 14

**Current Behavior**
div .info in pagination block is 54px high, while content is 44 px, not nice gap appearing

**Expected Behavior**
.info should be 44 as well

**Code Reproduction**
--

**Desktop (please complete the following information):**
Windows, Chrome

**Smartphone (please complete the following information):**
--

**Additional context**
Please find screenshot with problem by this link, it is secure: https://prnt.sc/soWxyb5gpuwO

**Comment by ayeshaa-m** [comment]
Need confirmation from designers for new height change. Though the changes are available in MR, I will update on this ticket once I get confirmation. - Thanks
