### ISSUE TITLE
Dropdown Select scrollbar is closing the dropdown instead of scrolling through the list of items

### ISSUE THREAD

**Issue by mwyrembl** [telekom/scale#1559]
**Scale Version**
3.0.0-beta.118

**Framework and version**
React 18.2.0

**Current Behavior**
Clicking on the scrollbar is closing the dropdown instead of scrolling through the available items.
Only the mouse wheel can be used for scrolling through the list.

**Expected Behavior**
Clicking on the scollbar should not close the list of items but perform the scroll operation through the list.

**Code Reproduction**
https://codesandbox.io/s/scale-components-react18-with-wrapper-forked-wo7hdj?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 109.0.5414.75

**Comment by tommy-codez** [comment]
This bug prevents us using the new component. So I second that. 
We would like to use the new component...

**Comment by ayeshaa-m** [comment]
@mwyrembl @tommy-codez fix will be coming in upcoming release. Thanks
