### ISSUE TITLE
Updating dependencies leads to UI changes

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#1566]
**Scale Version**
"@telekom/scale-components": "~3.0.0-beta.**101**"

**Framework and version**
Angular 14

**Desktop**
Windows, Chrome

**Additional context**

Hi! it's not the urgent one, but maybe you could comment here. I'm not really experienced with libs, maybe it's a proper behaviour, but seems strange to me. 

For our proj I started with Scale version 101, I've made a bunch of customizations. Later I already wanted to update to the latest version, but many changes were appearing, so I decided to stay with 101. Now I've made npm update to update inner dependancies for all the libs, and was surprised, that I've got all the UI of newest version, although in package.json it's still version 101. I guess the reason is that now for 101 inner libs version 120 are installed:

package.json: https://prnt.sc/GiHI9MFln8C9
prev package-lock: https://prnt.sc/V0bTJIfcOL2O
new package-lock: https://prnt.sc/pzapOaB-5zRK

how it looks like: https://prnt.sc/I5zFciDKi_j6

so maybe it's a good time to finally update, but it was kinda unexpected, that you are forced to do it without changing version in package.json. Is it a normal practice? I will be totally fine with 'yes'))

**Comment by mato-a** [comment]
Hi @tshimber 

If you want to stay on some fixed version you have to remove the caret `^` from your `package.json`:

```json
  "@telekom/scale-components": "3.0.0-beta.101",
```

Here is way: https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

**Comment by acstll** [comment]
Thank you @mato-a for your help and quick reply!

Here's another resource I find useful: https://devhints.io/semver

Regarding the changes in style for some components, around `3.0.0-beta.115` there was an update —one of a few more planned— aimed at optimising the library for "mobile". You can read a bit more about it here: https://telekom.github.io/scale/?path=/docs/update-history-development--page (27.10.2022)

@tshimber I'm closing the issue but feel free to keep posting here if you had any more questions.

**Comment by tshimber** [comment]
@mato-a  thanks a lot! I am nuuub///
@acstll yes, I remember, about enlarged elements) I'll check up the link, thanks!
yes, close it please, sorry/ I should google better//

**Comment by acstll** [comment]
No need to be sorry @tshimber we're here to help each other 🤓
