### ISSUE TITLE
scale-notification-banner outline is missing in high-contrast mode

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#1571]
**Scale Version**
3.0.0-beta.118

**Framework and version**
Vue 3.2.13

**Current Behavior**
During the acceptance of our application by an accessibility assessor, accessibility problems were discovered in Scale.
The `scale-notification-banner` outline is missing in high-contrast mode.

You can find the Screenshot here because I couldn't upload it: https://prnt.sc/0u6y6ipN1CDz

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: 109.0.5414.75

**Comment by marvinLaubenstein** [comment]
Hi @tomkroschwald, thanks for noticing. I'll take care of it and let you know as soon as it's fixed.
