### ISSUE TITLE
aria-describedby attribute points to the wrong element

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#1572]
**Scale Version**
3.0.0-beta.118

**Framework and version**
Vue 3.2.13

**Current Behavior**
When using the `helper-text` attribute, the `aria-describedby` attribute points to the wrong element.

You can find the screenshot here because I couldn't upload it: https://prnt.sc/aiO4lXFQjHw4

**Expected Behavior**
The `aria-describedby` attribute must be set to the `scale-helper-text` element and not to the empty `div`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 109.0.5414.75

**Comment by felix-ico** [comment]
hi @tomkroschwald thanks for pointing this out, there is already a fix PR open for this and it will be merged shortly. I Think you can expect this fix to be released next week.
