### ISSUE TITLE
Segemented Button is not default selected inside Scale Modal

### ISSUE THREAD

**Issue by niclas18** [telekom/scale#1580]
**Scale Version**
3.0.0-beta.122

**Framework and version**
Vue 3.2.47
Vite 4.1.1

**Current Behavior**
When adding a Segmented Button in a Modal, the field marked as `selected` is not selected.

**Expected Behavior**
The field marked as `selected` should also be marked as outside the modal.

**Code Reproduction**
[Stackblitz](https://stackblitz.com/edit/vitejs-vite-fcktqq?file=src%2FApp.vue)

**Desktop:**
- OS: Windows 10
- Browser: Chrome
- Version: 109.0.5414.75

**Additional context**
If you remove the superfluous `v-if` in line 13 of the code reproduction, the component is completely broken.

**Comment by jotabe87** [comment]
I've already commented on the pull request, but for documentation I can also confirm our dev team is facing the same bug. Do you guys have an idea, when the PR will be merged?

**Comment by felix-ico** [comment]
Hi @niclas18 @jotabe87, this issue is not forgotten! I had a look at it and i think it is ok to merge, I will ask another team member to review and hopefully we can get this released this week. 

Just a heads up, I am refactoring some of the segmented button code, but these changes will be included
