### ISSUE TITLE
scale-app-header uses wrong responsive breakpoint to switch from medium to large

### ISSUE THREAD

**Issue by sulyok-daniel** [telekom/scale#1625]
**Scale Version**
3.0.0-beta.126

**Framework and version**
Angular 14

**Current Behavior**
The documentation states that LARGE breakpoint's range is 1040px upwards.
But as seen in following screenshots the `scale-app-header` switches layout at 1024px already.

![image](https://user-images.githubusercontent.com/2097315/221831365-9447289a-afa9-4ead-a6b0-e97aa4048766.png)
![image](https://user-images.githubusercontent.com/2097315/221831450-185ff09a-8c21-48f5-9db9-6d0417b9b259.png)
![image](https://user-images.githubusercontent.com/2097315/221831507-bc4c54a6-6fe1-4e8e-950c-cefb1c77c7ad.png)

**Expected Behavior**
Switch to large breakpoint at 1040px width.

**Comment by marvinLaubenstein** [comment]
Hi @sulyok-daniel, sorry for the late reply. The inconsistency should be fixed in the next release, thanks for mentioning.
