### ISSUE TITLE
Add placeholder for datepicker (React)

### ISSUE THREAD

**Issue by gurpreetsingh2808** [telekom/scale#1638]
**Describe the feature request**
Addition of placeholder prop to DatePicker component 

**Describe the use case**
For setting up placeholder in datepicker, we need to provide a localization object which seems kind of an overkill. With a "placeholder" prop, it would be much easier to update placeholder text without messing with localization options

**Comment by ayeshaa-m** [comment]
@gurpreetsingh2808 we have provided support for "placeholder" prop in upcoming release. The localisation option is also there but "placeholder" prop will take the precedence.
