### ISSUE TITLE
Notification Toast: Attribute to customize ARIA label of close button

### ISSUE THREAD

**Issue by georgwittberger-t-systems-mms** [telekom/scale#1667]
## Description

The current implementation of the Notification Toast component sets the fixed ARIA label "close" for the close button. For better i18n support it would be useful if we could pass a custom label text via attribute, e.g. `closeButtonLabel`

## Use Case

Applications with support for multiple languages should be able to define a localized text for the ARIA label of the close button.

**Comment by marvinLaubenstein** [comment]
Hi @georgwittberger-t-systems-mms, you're definitely right about that. This is a very good improvement in accessibility. I will take care of it in a timely manner, thank you
