### ISSUE TITLE
scale-telekom-header (beta-component) doesn't change provided custom logo after scrolling down

### ISSUE THREAD

**Issue by Tireile** [telekom/scale#1688]
**Scale Version**
3.0.0-beta.128

**Framework and version**
Vue version 3.2.33

We should use <**scale-telekom-header**> (beta-component) on the demand brand design. Considering fact that we don't have possibility to set link on a logo I've provided slot="logo" with <**scale-logo**> component to the <**scale-telekom-header**> component. And scrolling down the page. 

**Current Behavior**
After scrolling down **<scale-logo>** component provided via slot="logo" doesn't change its size as it happening with the default logo.

**Expected Behavior**
The size of the **<scale-logo>** component should be changed like default logo in the <**scale-telekom-header**>

**Code Reproduction**
[Scale and Vue3 code example](https://codesandbox.io/s/confident-galois-97usmc?file=/src/App.vue)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 111.0.5563.110 (Official Build) (64-bit)

**Additional context**
For some reasons <**scale-telekom-header**> component doesn't change on scroll in the sandbox but there used the same code as in our project

**Demo**

![demo](https://user-images.githubusercontent.com/35307181/226982324-5b2f7ed6-1a6f-4a29-ac30-dd95b81e22de.gif)

**Comment by acstll** [comment]
Thanks for reporting this @Tireile 

> Considering fact that we don't have possibility to set link on a logo

I think this is the actual bug and one should be able to easily set a link for the logo.

We should try and solve this first, and then handle the resizing of a slotted logo on scroll… do you agree @Tireile?

**Comment by Tireile** [comment]
Hello, yeah it is good for me
