### ISSUE TITLE
Data Grid -> Graph Cell: Does not handle floating point number precision issues

### ISSUE THREAD

**Issue by benzac-de** [telekom/scale#1719]
**Scale Version**
3.0.0-beta.122

**Framework and version**
Vanilla JS

**Current Behavior**
The **Graph Cell** from the **Data Grid** does not handle floating point number precision issues. A value of `1.7` will be displayed as `1.7000000000000002`. Some examples showing the floating point number precision issue.

- `(1.1/100) * 100` -> `1.1`
- `(1.2/100) * 100` -> `1.2`
- `(1.3/100) * 100` -> `1.3`
- `(1.4/100) * 100` -> `1.4`
- `(1.5/100) * 100` -> `1.5`
- `(1.6/100) * 100` -> `1.6`
- `(1.7/100) * 100` -> `1.7000000000000002`
- `(1.8/100) * 100` -> `1.8000000000000003`
- `(1.9/100) * 100` -> `1.9`

**Expected Behavior**
A value of `1.7` should be displayed as `1.7`.

**Code Reproduction**
```
<content>
    <scale-data-grid id="graph-example" hide-menu></scale-data-grid>
    <script type="application/javascript">
    {
        const dataGrid = document.querySelector('#graph-example');
        dataGrid.fields = [
            {
                type: 'graph',
                label: 'Progress'
            }
        ];
        dataGrid.rows = [
            [1.1],
            [1.7]
        ];
    }
    </script>
</content>
```

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by ayeshaa-m** [comment]
@benzac-de I see this issue is occurring. Thanks for pointing out. We will come up with the solution asap. - Thanks

**Comment by ayeshaa-m** [comment]
@benzac-de  The issue fix will be coming in upcoming release. Thanks
