### ISSUE TITLE
scale-app-header: mobile menu items not focusable when activeRouteId is set

### ISSUE THREAD

**Issue by sulyok-daniel** [telekom/scale#1722]
**Scale Version**
3.0.0-beta.130

**current behaviour**

We are setting `activeRouteId` in `scale-app-header` to highlight the currently selected menu item (see "Übersicht" in attached screenshot).

![image](https://user-images.githubusercontent.com/2097315/231430820-f96f39ea-105d-4c1d-8065-81e308bb70e3.png)

When doing so, all mobile menu items get `tabindex="-1"`, so keyboard navigation is not possible anymore inside the mobile menu.

As soon as we set a non-existent `activeRouteId` all mobile menu items are focusable/reachable via keyboard:

![image](https://user-images.githubusercontent.com/2097315/231432627-aab05187-d01a-4c09-b0f0-a23cbfc359b1.png)

**expected behaviour**

Mobile menu items should be focusable via keyboard, even if an `activeRouteId` is defined in `scale-app-header`.

**Comment by felix-ico** [comment]
HI @sulyok-daniel, I apologize for the late reply. I think it is assumed that you should set the activeRouteId by yourself on click, you can see an example of this here https://github.com/telekom/scale/blob/main/packages/components/src/html/telekom/header.html . 

However the scale-app-header is now deprecated and has been replaced by scale-telekom-header so I'm not sure if this information is really needed anymore.

I will close this issue, but feel free to reopen it if you think it's still relevant.
