### ISSUE TITLE
scale-telekom-header-data-back-compat hides label in iconNavigation

### ISSUE THREAD

**Issue by sulyok-daniel** [telekom/scale#1745]
**Scale Version**
3.0.0-beta.131

**Current Behavior**
`scale-telekom-header-data-back-compat` sets the `label-visually-hidden` flag on all badges inside `iconNavigation` to true, so the label is visually hidden:

![image](https://user-images.githubusercontent.com/2097315/233327063-11f0e587-6a1b-4345-9e06-af7380bd1a53.png)

**Expected Behavior**
1. Allow to configure the `label-visually-hidden` flag, so a visible label can be set.
![image](https://user-images.githubusercontent.com/2097315/233328030-3f02e9dd-125f-47b0-8293-39ac965a0768.png)

2. Please add an additional property to be able to set an alternative label on the badges, so additional context/information can be set on badges for screen reader users, e. g.
- visual: "Help" / SR: "open Telekom help page"
- visual: <username> / SR: "open your profile menu"

**Comment by ayeshaa-m** [comment]
@sulyok-daniel , Fix is coming in upcoming release. we can provide the flag and text inside iconNavigation.
For example:
`export const iconNavigation = [
  { name: 'Search', id: 'Search35', href: '#search', icon: 'action-search' },
  { name: 'Cart', id: 'Cart36', href: '#cart', icon: 'action-shopping-cart' },
  { 
    name: 'Cart',
    id: 'Cart36',
    href: '#cart',
    icon: 'action-shopping-cart',
    badge: true,
    badgeLabel: 3,
    labelVisuallyHidden: false,
    badgeCount: 3,
    ariaLabelTranslation: '$badgeLabel - $badgeCount item'
  },
  { id: 'menu', defaultName: 'Menu', openedName: 'Close' },
];
`
