### ISSUE TITLE
scale-telekom-header's mobile menu behaves inconsistently 

### ISSUE THREAD

**Issue by sulyok-daniel** [telekom/scale#1747]
**Scale Version**
3.0.0-beta.131

**Current Behavior**
When opening the mobile menu in the [Scale storybook](https://telekom.github.io/scale/iframe.html?id=beta-components-telekom-brand-header-navigation--data-api&args=&globals=locale:en;colorMode:light&viewMode=story) the whole browser window is covered, hiding the default header bar:

![image](https://user-images.githubusercontent.com/2097315/233335151-d5936f6b-cc8b-446e-87fc-0e9357336e67.png)

When using `scale-telekom-header-data-back-compat` in our own code, the mobile menu opens right under the default header bar (1), also the page below is still visible (2) under the mobile menu:

![image](https://user-images.githubusercontent.com/2097315/233336375-e1756118-e3af-4206-bb39-d7fc5f6f924e.png)

**Please clarify**

- Which is the correct behaviour?
- Are we supposed to implement custom CSS to match the storybook's behaviour?

**Comment by acstll** [comment]
Thank you @sulyok-daniel for reporting this!

> Which is the correct behaviour?

option 1, covering the entire browser window…

> Are we supposed to implement custom CSS to match the storybook's behaviour?

nope. The data-compat version will handle this correctly.

Thanks again.

#1764 fixes this here https://github.com/telekom/scale/pull/1764/files#diff-a803ffe7e9b4f68af16a56760f3d652defe8822241d1c5e364698759378c0661

**Comment by acstll** [comment]
Fix will be included in an imminent release ☺️
