### ISSUE TITLE
Notification Toast: Header text overflowing close button

### ISSUE THREAD

**Issue by georgwittberger-telekom-mms** [telekom/scale#1748]
**Scale Version**

3.0.0-beta.116

**Framework and version**

React 18.2.0 with @telekom/scale-components-react

**Current Behavior**

Header text of Notification Toast overflows the close button.

![hw27PWLvGP](https://user-images.githubusercontent.com/64543811/233408283-9014b210-4e1e-458d-bee6-bfa63c5c5777.png)

**Expected Behavior**

Header text breaks line before it overflows the close button.

**Code Reproduction**

Just modify HTML of header paragraph in Storybook page: https://telekom.github.io/scale/?path=/docs/beta-components-notification-toast--standard

**Comment by ayeshaa-m** [comment]
@georgwittberger-telekom-mms Thanks for noticing this issue, The fix is coming in upcoming release.
