### ISSUE TITLE
Notification Toast: Telekom Brand Header is on top of toast messages

### ISSUE THREAD

**Issue by georgwittberger-telekom-mms** [telekom/scale#1749]
**Scale Version**

3.0.0-beta.116

**Framework and version**

React 18.2.0 with @telekom/scale-components-react

**Current Behavior**

New Telekom brand header is on top of Notification Toast messages.

![bv3GAOpDSD](https://user-images.githubusercontent.com/64543811/233412844-7b010ff5-d202-4be6-9823-24660d37d4d8.png)

**Expected Behavior**

Notification Toast is on top of the Telekom brand header because it must be visible even when header is present.

**Code Reproduction**

Modify HTML of Telekom Brand Header page in Storybook: https://telekom.github.io/scale/?path=/docs/beta-components-telekom-brand-header-navigation--standard-header

```html
<div class="wrapper">
  <scale-telekom-app-shell>
    <scale-telekom-header slot="header" scrolled-back>
      ...
    </scale-telekom-header>
    <scale-notification-toast opened>
      <p slot="header">Informational toast headline</p>
    </scale-notification-toast>
  </scale-telekom-app-shell>
</div>
```

**Comment by ayeshaa-m** [comment]
@georgwittberger-telekom-mms Fix will be coming in upcoming release. -- Thanks
