### ISSUE TITLE
scale-text-field helper-text disapears

### ISSUE THREAD

**Issue by TsysSreina** [telekom/scale#1757]
**Scale Version**
3.0.0-beta.129

**Framework and version**
angular 14

**Current Behavior**
If we put in the html the next code:

<scale-text-field label="{{'GENERAL.REQUEST_ID' | translate}}" formControlName="requestId"
helper-text="{{'GENERAL.REQUEST_ID_HELPER' | translate}}"></scale-text-field>

the helper text not appears in the screen.

**Expected Behavior**
We want to use the translate service inside the helper-text.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  111.0.5563.111

**Comment by ayeshaa-m** [comment]
Hi @TsysSreina . Thank you for noticing this. Could you please provide small piece of code snippet to understand the issue better?

**Comment by TsysSreina** [comment]
Sorry the code it wasn't copied in my last message:
< scale-text-field label="Id" formControlName="id"
			[invalid]="isGeneralFormSubmitted && generalFields['id'].errors" [attr.readonly]="isEditMode"
			helper-text="{{ID_REQUIRED | translate}}" ></ scale-text-field >

The same issue occurs in accessibility-tilte:
< scale-icon-user-file-user accessibility-title="{{userName}}" ></ scale-icon-user-file-user >

In the two cases if you put something inside {{}} the component doesn't write anything in the helper-text or in the accessibility-tile.

**Comment by ayeshaa-m** [comment]
@TsysSreina  We will check this and update on this. Thanks

**Comment by felix-ico** [comment]
hi @TsysSreina can you please try to set the attribute as helperText (camelCase) rather than helper-text (kebab-case). I just did a quick test on a small angular project and it seemed to solve the issue for me. 

I will close the issue, but please feel free to reopen if my workaround doesn't work for your case.
