### ISSUE TITLE
State of checkbox group not consistent with its checkboxes

### ISSUE THREAD

**Issue by marcel-radermacher-tng** [telekom/scale#1774]
**Scale Version**
3.0.0-beta.129

**Framework and version**
vue 3.2.37

**Current Behavior**
When programatically adding new checkboxes to a checkbox group, the state of the checkbox group is not consistent with the state of its checkboxes. For example, consider the following two scenarios:

- The checkbox group contains a selected checkbox and after a short delay a second unselected checkbox is added. Then the checkbox group remains in the 'all checkboxes selected' state.
- Similar, when initially the checkbox group does not contain any checkbox, the checkbox group is disabled and keeps this status even when new checkboxes are added.
 
![image](https://user-images.githubusercontent.com/95904429/235640991-4db871ea-b113-492f-abc1-47c954c4abcf.png)

**Expected Behavior**
The state of the checkbox group is always consistent with its checkboxes. Thus, in both previous examples, the checkbox groups should be in the 'partially selected' state.

![image](https://user-images.githubusercontent.com/95904429/235642381-7b5a0d1c-a620-421c-bbc3-60729f8ebb33.png)
**Code Reproduction**

https://codesandbox.io/p/sandbox/magical-microservice-31i1wz?&file=%2Fsrc%2Fcomponents%2FDynamicCheckboxes.vue1

```javascript
<template>
  <div>
    <scale-checkbox-group
    label="Many Items"
    name="many-items"
    >
      <template v-for="item in items" :key="item">
        <scale-checkbox
        :value="item[1]"
        :checked="item[0]"
        >
         {{ item[1]}}
        </scale-checkbox>
      </template>
    </scale-checkbox-group>
  </div>
</template>

<script>
export default {
  name: "DynamicCheckboxes",
  props: {
    initialWait: Boolean
  },
  data() {
    return {
      items:[] 
    }
  },
  async mounted() {
    
    function sleep(ms) {
      return new Promise(resolve => setTimeout(resolve, ms));
    }

    if (this.initialWait) {
      await sleep(100)
    }
     
    this.items.push([true, 'first item']);
    await sleep(1000)
    this.items.push([false, 'second item']);
  }
};
</script>
```

**Comment by felix-ico** [comment]
this will be available on the next release, beta.143
