### ISSUE TITLE
the mobile-main-nav is not displayed correctly 

### ISSUE THREAD

**Issue by KNUGER** [telekom/scale#1788]
in the mobile version, the navigation is only shown LINK blue!  Why???

Version:3.0.0-beta.131 
Plain HTML

Code: 
```html
<scale-telekom-mobile-menu slot="mobile-main-nav"  >
					<scale-telekom-mobile-menu-item level="0" current-level="0"  ><a href="index.php">HOME</a>
				</scale-telekom-mobile-menu-item>
				<scale-telekom-mobile-menu-item level="0" current-level="0"  ><a href="index1.php">Seite 1</a>
				</scale-telekom-mobile-menu-item> 
				<scale-telekom-mobile-menu-item level="0" current-level="0"  ><a href="index2.php">Seite 2</a>
				</scale-telekom-mobile-menu-item> 
</scale-telekom-mobile-menu> 

``` 
![mobile-main-nav](https://user-images.githubusercontent.com/96534141/236387250-d5384409-ff54-43a7-84cd-6619791adc9e.png)

thx for help ;-)

**Comment by felix-ico** [comment]
Hi @KNUGER, I have created a minimal reproduction sample here https://codesandbox.io/s/scale-components-plain-html-template-forked-4qie2z?file=/index.html and, as you can see, the links are displayed with the expected styles. Unfortunately I could not reproduce your issue, is it possible that there is some custom styling in your app that is overwriting the scale styles?

**Comment by acstll** [comment]
Thank you @felix-ico for the repro!

@KNUGER with "custom styling in your app", we mean some global CSS that is affecting _all_ links on the page.

For some more context: the `<a>` tags in the navigation have no "shadow DOM protection" like most Scale components do, they're in the light DOM, so they can suffer this kind of style leaks when there is global CSS.

In case you cannot remove or scope your global CSS, you can try and use the [`:not()` pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) to keep these styles from leaking into the mobile menu.

What might be happening:
```css
/* element selector affecting all links on the page */
a {
  color: blue;
  text-decoration: underline;
}
```

The suggestion using `:not()`:
```css
a:not(scale-telekom-mobile-menu a) {
  color: blue;
  text-decoration: underline;
}
```

**Comment by KNUGER** [comment]
the bug is a problem from my scabling of my scale components. 

You can close the problem  

THX Knut

**Comment by KNUGER** [comment]
Thanks for the support
