### ISSUE TITLE
Dropdown Select: Text overflows boundaries of element

### ISSUE THREAD

**Issue by georgwittberger-telekom-mms** [telekom/scale#1789]
**Scale Version**

3.0.0-beta.131

**Framework and version**

React with @telekom/scale-components-react

**Current Behavior**

If text of selected item is very long it overflows the boundaries of the dropdown element.

![dropdown-text-overflow](https://user-images.githubusercontent.com/64543811/236241919-33681241-2400-441a-ba85-35c8e2e0b0a7.png)

**Expected Behavior**

Text of selected item should be capped at the boundary of the dropdown element. Possibly, it should be abbreviated with an ellipsis "..."

**Code Reproduction**

Modify HTML of Scale demo page and insert long text into dropdown item.

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome/Edge
 - Version: 112

**Comment by marvinLaubenstein** [comment]
Hi @georgwittberger-telekom-mms thanks for noticing. We will take care of this issue asap.
