### ISSUE TITLE
Scale button --width in %

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#1836]
**Scale Version**
3.0.0-beta.134

**Framework and version**
Angular 14

**Additional context**
Hi! I've updated Scale and have the issue with scale-btn width. I want it to be 100%, and previously "scale-button { --width: 100%; }" in css worked. Now only value in px works, and I can't put 100% neither as var, nor via :host .button, nor via [styles] attr. Maybe you have some advice here? I guess I'm doing smth wrong/

![image](https://github.com/telekom/scale/assets/110041439/3634e3db-d813-4244-a1f8-a396fe8f6445)

![image](https://github.com/telekom/scale/assets/110041439/9c1f5559-6fe7-4112-bcce-19a76070b2c9)

**Comment by ayeshaa-m** [comment]
@tshimber  We will check this issue and update you soon. Thanks

**Comment by ayeshaa-m** [comment]
@tshimber width:100% works relative to its nearest container. I tried this and its working. Can you please try like this below?

`<div style="width: 500px; height: 200px; background-color: blue;">
      <scale-button style="--width:100%; width: 100%;" id="choose-dario">choose Dario</scale-button>
    </div>`

**Comment by tshimber** [comment]
@ayeshaa-m  thank you!! yes, it works this way: 
        --width: 100%;
        width: 100%;

So the issue can be closed I guess) sorry for the late answer!

**Comment by amir-ba** [comment]
Will close this as  it is resolved
