### ISSUE TITLE
Data grid-falsy data structure

### ISSUE THREAD

**Issue by BarboraUngerova** [telekom/scale#1861]
**Scale Version**
^3.0.0-beta.56

**Framework and version**
framework: react^17.0.2 
auto-generated scale wrapper packages-react

**Current Behavior**
When I use Data Grid and I try to change data which are already displayed in Data Grid, I get error in console: `not valid JSON`.

**Expected Behavior**
When I use Data Grid and I try to change data which are already displayed in Data Grid, I get NO error in console.

**Code Reproduction**
https://codesandbox.io/s/wispy-flower-bm8gu4?file=/src/index.js

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 20

**Additional context**
![image](https://github.com/telekom/scale/assets/84072142/9dcb9b0b-42fd-4d3c-8bc0-e1c136f1829f)

**Comment by felix-ico** [comment]
I am closing this issue as it seems to be fixed with newer versions of scale. Please feel free to reopen it if you are still experiencing the issue.
