### ISSUE TITLE
Dropdown Select: Closes when grabbing scrollbar in listbox

### ISSUE THREAD

**Issue by georgwittberger-telekom-mms** [telekom/scale#1873]
**Scale Version**

3.0.0-beta.131

**Framework and version**

React 18.2.0 with @telekom/scale-components-react

**Current Behavior**

Listbox of the dropdown closes unexpectedly when trying to grab the scrollbar with the mouse pointer.

![chrome_sBRGRja7F9](https://github.com/telekom/scale/assets/64543811/1652098c-1fc8-4377-8ebe-527c2b0b837b)

**Expected Behavior**

Listbox stays open while dragging the scrollbar with the mouse pointer.

**Code Reproduction**

This was not reproducible within the Scale demo page. However, it consistently occurs in our React application using @telekom/scale-components-react.

**Additional context**

My assumption is that the dropdown is closed due to the combobox losing focus, thus executing this `handleBlur` function: https://github.com/telekom/scale/blob/e79a37e81cb54a4803a104b3c0a230c619b32754/packages/components/src/components/dropdown-select/dropdown-select.tsx#L358

For clicks on options there is already a "trick" which sets `this.ignoreBlur = true` to prevent the default closing behavior: https://github.com/telekom/scale/blob/e79a37e81cb54a4803a104b3c0a230c619b32754/packages/components/src/components/dropdown-select/dropdown-select.tsx#L449

Maybe this "ignoreBlur" logic must be added to the `[part="listbox-pad"]` element as well?

**Comment by marvinLaubenstein** [comment]
Hey @georgwittberger-telekom-mms, thank you for noticing. 
Of course, it should not be like that. I'll take a look at it and fix it.

**Comment by marvinLaubenstein** [comment]
Good morning @georgwittberger-telekom-mms, 
I had a look at the issue and indeed it does not occur anymore in the latest version of scale (`3.0.0-beta.134`). I would ask you to update your version. 

If you still have this issue in the updated version, please feel free to contact us again 🙂. 


https://github.com/telekom/scale/assets/82942834/b6a67a15-a054-4c8e-bcf2-48736ea68dbe

**Comment by georgwittberger-telekom-mms** [comment]
@marvinLaubenstein , we've recently upgraded to version `3.0.0-beta.134` and the problem still exists in our application.

I assume that there is a difference between Safari on Mac (that you are using) and Chrome/Firefox on Windows (our environment). Maybe the browsers handle clicks on the scrollbar differently, while Chrome/Firefox "click through" the scrollbar and therefore the combobox loses focus.

**Comment by georgwittberger-telekom-mms** [comment]
@marvinLaubenstein , any news regarding this issue? We still have this problem in our project as stated above.

**Comment by marvinLaubenstein** [comment]
Hi, I tested it again today and unfortunately I can't reproduce it. Windows 10 in conjunction with chrome and firefox.

**Comment by georgwittberger-telekom-mms** [comment]
Maybe it only happens in conjunction with the React bindings, i.e. using @telekom/scale-components-react?

If you need further info, please reach out to me. I can demo it in our application if you want.

**Comment by tommy-codez** [comment]
for reference the same bug is mentioned here https://github.com/telekom/scale/issues/1559

**Comment by marvinLaubenstein** [comment]
Hi @georgwittberger-telekom-mms, unfortunately I am leaving the project today. @acstll and @felix-ico will help you with the problem 🙂.

**Comment by georgwittberger-telekom-mms** [comment]
This scrollbar issue is reproducible when using `<scale-dropdown-select>` inside a `<scale-tab-panel>`. See this video:

https://github.com/telekom/scale/assets/64543811/9fe84d30-7192-4b6e-9f8f-aee23c697628

HTML Code:

```html
<scale-tab-nav>
  <scale-tab-header slot="tab">
    <scale-icon-home-home></scale-icon-home-home> General
  </scale-tab-header>
  <scale-tab-panel slot="panel">
    <scale-dropdown-select label="Select a name">
      <scale-dropdown-select-item value="arthur"
        >Arthur</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="alice"
        >Alice</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="ben"
        >Ben</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="caspar"
        >Caspar</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="cedric"
        >Cedric</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="david"
        >David</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="fritz"
        >Fritz</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="grace"
        >Grace</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="hans"
        >Hans</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="ines"
        >Ines</scale-dropdown-select-item
      >
      <scale-dropdown-select-item value="jake"
        >Jake</scale-dropdown-select-item
      >
    </scale-dropdown-select>
  </scale-tab-panel>
  <scale-tab-header slot="tab">
    <scale-icon-user-file-analytics></scale-icon-user-file-analytics>
    Usage
  </scale-tab-header>
  <scale-tab-panel slot="panel">
    Bespoke austin pork belly yuccie pop-up. Before they sold out…
  </scale-tab-panel>
</scale-tab-nav>
```

Please mind the hint I have written in "Additional context" section in the original issue description.

**Comment by felix-ico** [comment]
hi @georgwittberger-telekom-mms, I just had a look at this and it seems that the combination of tab-nav + dropdown-select is broken because the tab-panel has a tabindex and hijacks the dropdown-select focus. I added an exception for this when the dropdown-select is placed within a tab-panel... I could not however figure out what you meant by " Closes when grabbing scrollbar in listbox", are there other components that cause a similar behavior?

**Comment by georgwittberger-telekom-mms** [comment]
Thanks for the update and fix, @felix-ico .

I suppose the confusion is about the word "listbox". I meant this list of items which drops down when you click the "Dropdown Select" component. So the issue applies only to this component and only the interaction with its scrollbar.

**Comment by georgwittberger-telekom-mms** [comment]
Now with version 3.0.0-beta.139 the issue seems to be fixed at first but it appears again for certain interaction. See the following video:

https://github.com/telekom/scale/assets/64543811/1b75bb6c-a86d-4747-9e47-9f807f9062c6

1. After initial rendering the dropdown seems to work as expected. You can grab the scrollbar and move it up and down.
2. First new issue: Dropdown listbox does not close anymore when clicking outside the dropdown area.
3. Second issue: After closing the dropdown by clicking on the field again the scrollbar issue appears again when opening the dropdown a second time.

**Comment by UBOrange** [comment]
@felix-ico: Any idea by when this could be fixed? Thanks!

**Comment by felix-ico** [comment]
@UBOrange sorry for the delay, I am picking up this issue now
