### ISSUE TITLE
Scale-Dropdown-Select: hide empty label

### ISSUE THREAD

**Issue by Pho3njx** [telekom/scale#1890]
Dear Scale team,

**Describe the feature request**
As already realized for **_text-field_** and **_dropdown_** (#827 `hideLabelVisually` property) - I would like to ask you to implement this property/feature for the new **_scale-dropdown-select_** too.

**Describe the use case**
When trying to use a **_scale-dropdown-select_** without a label, the text does not fill the empty space above. The space for the label stays empty:
![scale-select-item_noLabel](https://github.com/telekom/scale/assets/95290235/9d96cdd5-db10-433e-8a4a-972716003634)

**Alternatives**
Feel free to realize it in another way.

Thank you and best regards!

**Comment by ayeshaa-m** [comment]
Hi @Pho3njx This feature has been incorporated in upcoming release. Thanks you!

**Comment by Pho3njx** [comment]
Awesome, thank you so much @ayeshaa-m!
