### ISSUE TITLE
missing Server for Sketch generator

### ISSUE THREAD

**Issue by volkerchartier** [telekom/scale#198]
Are you missing to implement a tiny http server to the sketch generator package?
something like:
`"serve": "http-server sketch-render -p 3334" `
to serve the files + port for puppeteer inside the inject.js file?

**Comment by eeegor** [comment]
@volkerchartier thanks for opening this issue! 

You're right, currently we have no in-build server inside `sketch-generator` would you be open to create a pull request for that?

One problem might be that `http-server` is not available for all platforms...

**Comment by volkerchartier** [comment]
Here you go #201
