### ISSUE TITLE
Opening Flyout Menu in Modal causing closing of Modal Window

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#2021]
**Scale Version**
Tested on sandbox with current scale version 134

**Framework and version**
react 17

**Current Behavior**
If I have a flyout menu in a modal , when I open the flyout menu and choose an option or click outside the menu to close the flyout - the modal window also closes automatically.

**Expected Behavior**
modal should stay open when I choose or close the menu.

**Code Reproduction**

https://codesandbox.io/s/flyoutmenu-modal-n5v2zv

**Desktop (please complete the following information):**
tested with different browsers on windows

**Comment by felix-ico** [comment]
Hi @tommy-codez, I would add an `event.stopPropagation()` to the scale-close method of the flyout-menu. I forked your codesandbox here with a working sample: https://codesandbox.io/s/flyoutmenu-modal-forked-pkdwwx?file=/src/SomeComponent.tsx.

Please feel free to reopen the issue if this workaround did not solve your problem.
