### ISSUE TITLE
Bad positioning of Flyout menu inside modal in combination with transform css

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#2035]
**Scale Version**
Tested with current version 134

**Framework and version**
React (17)

**Current Behavior**
Flyout menu List appears with random offset to the button. 

**Expected Behavior**
Flyout menu should appear on the button which triggered the list.

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

sandbox
https://codesandbox.io/s/flyoutmenu-modal-transform-zwywpv

**Desktop (please complete the following information):**
independent

**Smartphone (please complete the following information):**

**Additional context**
Related? bug 
https://github.com/telekom/scale/issues/986

Because of other bugs with date fields inside a modal we use the transform css directive (see sandbox styles.css)

**Comment by felix-ico** [comment]
Hey sorry for the delay, i just tested this with the last version beta.142 and it seems fixed - please feel free to reopen the issue if you think the bug persists
