### ISSUE TITLE
How to define a scale-icon programmatically for a scale-button (e.g. in a scale-data-grid 'actions' column)?

### ISSUE THREAD

**Issue by Pho3njx** [telekom/scale#2054]
**Scale Version**
3.0.0-beta.136

**Framework and version**
Angular: 15.2.9, Typescript: 4.9.5

**Question**
Hello Dear Scale team,
how can I add a scale-icon programmatically to a scale-button? So that I can use an icon-only scale-button in a data-grids 'actions' column e.g.

Description:
In HTML,  you just include the scale-icon tag into the scale-button tag:
```html
<scale-button icon-only>
  <scale-icon-content-heart accessibility-title="like" />
</scale-button>
``` 

In a data-grid you can define an 'actions' column where you can setup scale-buttons. So, you can also set the button property iconOnly=true. The button is shown in the data-grids column. But, of course, without any label or icon.

Example:

`HTML part of the component`
```html
      <scale-data-grid
        [fields]="cols"
        [rows]="rows"
      ></scale-data-grid>
``` 

`TypeScript part of the component`
```typescript

  // Columns defintion
  public cols = [
    {
      label: 'ID', 
      sortable: true 
    },
    {
      label: 'Actions',
      type: 'actions',
    },
  ];

  // Rows definition
  public rows = [
    [
      // ID
      '1111',
      // ACTIONS buttons
      [
        {
          type: 'button',
          iconOnly: true,
          variant: 'secondary',
          size: 'small',
          onClick: () => {
            console.log('click aa');
          },
        },
        {
          type: 'button',
          iconOnly: true,
          variant: 'secondary',
          size: 'small',
          onClick: () => {
            console.log('click ab');
          },
        },
      ],
    ],
  ];
``` 
Result:
![scale-data-grid](https://github.com/telekom/scale/assets/95290235/81610153-e579-43c2-acc8-e66c377444ed)

Thank you so much for your help!

**Comment by acstll** [comment]
Thank you @Pho3njx for getting in touch.

To do that you can pass an object to the `label` key with the markup as `__html`, like this:

```js
{
  type: 'button',
  iconOnly: true,
  label: {
    __html: '<scale-icon-action-more accessibility-title="More"></scale-icon-action-more>'
  },
  variant: 'secondary',
  size: 'small',
  onClick: () => {
    console.log('click aa');
  },
}
```

I hope this helps.
