### ISSUE TITLE
IDE | Autocomplete for web-components and their prop names and types

### ISSUE THREAD

**Issue by Darkavid** [telekom/scale#2056]
**Scale Version**
3.0.0-beta.56

**Framework and version**
Web-components with Vue3 and Vite.

**Additional context**
Hi!

The documentation says:
![image](https://github.com/telekom/scale/assets/28023185/e5d3e73d-d1b1-4c8a-a96f-089b98494056)

That is true, however, I think we can all agree that developer experience is not only about how cool something under the hood.
Proxy packages were really great because they provided the autocomplete suggestions for components and props in the IDE (e.g.: WebStorm). Without them, all I have is custom web-components added run-time, totally unknown by the IDE. Meaning, I have to rely only on basically pure text when using your components, which makes the frontend code hard to maintain and to refactor.

Please, help me, if you remove the proxy packages, what alternatives do I have to avoid losing autocomplete functionality for your package? How am I going to have type-check and autocomplete for components & props?

Maybe I'm just missing something here 😃

Many thanks!
Dave

**Comment by christopherGdynia** [comment]
Hello @Darkavid, 

honestly I've never used vue yet,

I can give you an solution which worked for react and solid, 
maybe you can find a solution based on this one [here](https://github.com/telekom/scale/issues/615#issuecomment-1011919428)

If you need more help, you can reach out to me :)


Christopher

**Comment by Darkavid** [comment]
Hello team, Hi @christopherGdynia,

I have found it:
https://stenciljs.com/docs/docs-vscode

This is what *you* need to provide.
We can use this output in VSCode to get autocompletion for your custom webelements.
Otherwise, I'm just typing from the top of my head which is hardly considered to be a good DX in 2024.

Thanks in advance!

**Comment by Darkavid** [comment]
An investigation with @christopherGdynia lead us to the following conclusions:
- the configuration I mentioned earlier is [already added to your `stencil.config.ts` file](https://github.com/telekom/scale/blob/main/packages/components/stencil.config.ts#L80)
- the necessary `custom-elements.json` file is [added to your `.gitignore` file](https://github.com/telekom/scale/blob/main/packages/components/.gitignore#L34)
- based on the path specified there, the `custom-elements.json` should be in the root folder of your distributed package
- the distributed package does not contain the `custom-elements.json`
![image](https://github.com/telekom/scale/assets/28023185/71e7f7a9-9bc5-4db3-be8e-2d7e35df3798)

This makes this issue rather a bug then a support ticket.

Can you please fix this issue in your next release?
