### ISSUE TITLE
scale-switch not well perceptible

### ISSUE THREAD

**Issue by tk-network** [telekom/scale#2078]
**Scale Version**
3.0.0-beta.137

**Framework and version**
vue 3.2.45

**Current Behavior**
When testing the accessibility of our application, there were problems with the ```scale-switch```. This is not well perceivable in high contrast mode.

![image](https://github.com/telekom/scale/assets/93334942/f400b84d-2297-4bdc-89ea-01545e9b2eda)

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser chrome
 - Version 112.0.5615.137

**Comment by felix-ico** [comment]
this bugfix should be available as of beta.139
