### ISSUE TITLE
scale-text-field border ist missing in high contrast mode

### ISSUE THREAD

**Issue by tk-network** [telekom/scale#2079]
**Scale Version**
3.0.0-beta.137

**Framework and version**
vue 3.2.45

**Current Behavior**
If the ```scale-text-field``` has the attribute "readonly", it is not well perceivable in high contrast mode. According to our accessibility expert opinion, the border attribute is missing here.

![Bildschirmfoto 2023-07-31 um 09 56 57](https://github.com/telekom/scale/assets/93334942/ebc5a57a-1f43-4487-861a-e6033f7fbffa)

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser chrome
 - Version 112.0.5615.137

**Comment by felix-ico** [comment]
this bugfix should be available as of beta.139
