### ISSUE TITLE
Invalid hint in data-grid header

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#2097]
**Scale Version**
3.0.0-beta.134

**Framework and version**
Angular14

**Current Behavior**
In data-grid in header there;s hint about sorting even if column is not sortable

**Expected Behavior**
Hint should be removed for non-sortable columns

![image](https://github.com/telekom/scale/assets/110041439/316d4513-f1a2-4892-9f41-961bdf53a2a5)

**Comment by tshimber** [comment]
@felix-ico hi!) thanks for fixing! could you please tell, when it will be available? i've changed version to 141 (seems latest), but issue is still there, although fix seems to be merged//
![image](https://github.com/telekom/scale/assets/110041439/5bdc9898-61c7-40ec-bb41-11c0c555176e)

![image](https://github.com/telekom/scale/assets/110041439/f87799ba-1473-443d-8f23-cbc054b27ba4)

**Comment by felix-ico** [comment]
hi @tshimber, the bugfix is now available on beta.142

**Comment by tshimber** [comment]
it works, thank you:)
