### ISSUE TITLE
 Deprecation notice in console

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#2102]
**Scale Version**
3.0.0-beta.137

**Framework and version**
VUE 3.3.4

**Current Behavior**
Disturbing noticies:
![image](https://github.com/telekom/scale/assets/110041439/7f1e8198-1705-49b0-93fc-388c6daad25c)

**Expected Behavior**
No noticies

**Code Reproduction**
These are my first tries in vue, maybe it's all incorrect. But I don't use any lang props
![image](https://github.com/telekom/scale/assets/110041439/a22238db-3295-472e-b4ba-7c903e5e6dbd)

**Comment by felix-ico** [comment]
Hi @tshimber, sorry for the late reply. I understand these deprecation warnings can be annoying and i opened a PR to remove the default language that is set on the logo component (causing the deprecation warning even when the end user doesn't set any language).

By the way I notice that you are using scale-app-shell and scale-app-footer, just FYI these components have been deprecated, and replaced by scale-telekom-app-shell, scale-telekom-footer and scale-telekom-header.

**Comment by tshimber** [comment]
Hi @felix-ico 
no so late honestly) thanks for answering!!
thank you, will be good not to have those notifications, but it's not critical of course.
considering deprecated components - we just use them in lots of templates for diff frameworks, need to make a task to update everywhere🙃

**Comment by tshimber** [comment]
@felix-ico Felix, hi! sorry to bother you again, maybe you can tell: how can I get, if thing is or isn't fixed without bothering you? I've updated Scale to latest 3.0.0-beta.142, but I still see the warning. I use deprecated scale-app-shell, as you correctly noticed, but your comment looked like it will be fixed for old ones as well. 
It's not critical, but just for me to understand if it will be fixed for deprecated scale-app-shell and to move or don't move it from my list)

Thanks!!

**Comment by felix-ico** [comment]
hey @tshimber, looks like i forgot to remove the language from the footer, so that's why you were getting the warnings. The header should not throw any warnings though. Normally we wouldn't push updates to deprecated components but this was simple enough to do https://github.com/telekom/scale/pull/2183

**Comment by tshimber** [comment]
☺☺☺ so nice from you:) thanks a lot!!
