### ISSUE TITLE
A11y Support - aria-labels not attached to button itself in data-grid component fields with type=html

### ISSUE THREAD

**Issue by matthias85** [telekom/scale#2110]
Hi Scale-Dev-Team,
we had an A11y-Audit and there is an issue for blind users to get informed about the expand-button in data-grid-component. It is only read out when focussing a button itself but not in table-navigation.

**Scale Version**
tested in 3.0.0-beta.134 / 3.0.0-beta.137

**Framework and version**
within React 18 with Wrapper

**Current Behavior**
Data-grid-component field with type="html" render expand button with aria-label at "scale-button" tag, but not at button itself. 

Side Note: At button-component with prop "innerAriaLabel" this will be attached also to button-tag itself. This would be correct.

**Expected Behavior**
Possible solution: attach aria-label to "button" element, not to the surrounding element (scale-button) 

**Code Reproduction**
https://codesandbox.io/s/scale-components-react18-with-wrapper-forked-xk4j8l?file=/src/App.js

**Desktop (please complete the following information):**
 - Chrome (Version 116.0.5845.110)

**Comment by felix-ico** [comment]
HI @matthias85 I just merged this PR and the fix will be available on the next release

**Comment by matthias85** [comment]
Thanks a lot.
