### ISSUE TITLE
Add disabled property to dropdown-select-item

### ISSUE THREAD

**Issue by marcuskrahl** [telekom/scale#2114]
**Describe the feature request**
The Dropdown Select component currently lacks the ability to disable individual Dropdown Select Items.
It is supposed to replace native `<select>` elements and it is possible for `<option>` elements inside a `<select>` or `<scale-dropdown>` element to be disabled.

**Describe the use case**
It is sometimes necessary to show options to a user which are currently unavailable, but might be available under different circumstances. When showing these disabled options we can also provide a reason for the user why these options are unavailable.

**Describe alternatives you've considered**
- using `<scale-dropdown>`, but it is deprecated
- using checkboxes, but sometimes a dropdown is the most appropriate control

**Additional context**
We might also want to consider other features of native selects, lke `<optgroup>`, etc.

**Comment by dadadcko** [comment]
Hey @felix-ico, I have dig through source-code and see that `dropdown-select-item` only acts as placeholder for data but all styles and logic is actually implemented in `dropdown-select`. 
Regarding the styles, should be `disabled` implemented the same way? E.g. disabled text color should be set from (by) `dropdown-select`, or directly in `dropdown-select-item` ? 

The above also makes problem for implementing _disabled reason message_. Currently, when any option is selected, the whole element is rendered. This makes problem when we only want to display reason message in list-pad box, not when the element is already actually selected. Should displaying the reason message be part of (and responsibility of) parent - `dropdown-select` ? 

I have already experimented with both solutions, but I want to get clarification from you before I commit the final implementation :)
