### ISSUE TITLE
Ensure that text stays visible on webfont load

### ISSUE THREAD

**Issue by SebastianGode** [telekom/scale#2118]
**Scale Version**
```
"@telekom/scale-components": "^3.0.0-beta.134",
"@telekom/scale-components-react": "^3.0.0-beta.134"
```

**Framework and version**
NextJS 
`"next": "^13.4.4",`

**Current Behavior**
Google Lighthouse Performance score is negatively impacted by the following:
https://developer.chrome.com/docs/lighthouse/performance/font-display/?utm_source=lighthouse&utm_medium=devtools
![image](https://github.com/telekom/scale/assets/70581801/b32749c9-24df-4465-9efc-b77dfb0daae5)

As fonts are loaded by scale this should be fixed.

**Expected Behavior**
This error should not be listed in any lighthouse report when using scale's own fonts.

**Code Reproduction**
Any scale page, even the own documentation portal.

**Comment by tischrei** [comment]
We also need this improvement.
