### ISSUE TITLE
Provide a ZIP file or single file for using Scale without NodeJS

### ISSUE THREAD

**Issue by SebastianGode** [telekom/scale#2136]
**Describe the feature request**
Currently it's hard to use Scale without NodeJS as compared to e.g. React there are no static UMD builds from scale available. This means a user either would need to manually compile the whole project and then copy the dist folder to it's target project or he would need to use the slow UNPKG CDN from here: https://unpkg.com/browse/@telekom/scale-components@3.0.0-beta.140/dist/
It would be great to have a ZIP file on each tag with the dist output of the build.

**Describe the use case**
Not every website is using NodeJS as environment. In some cases it's not even possible to use NodeJS. Scale should however be also usable in those websites.

**Describe alternatives you've considered**
The alternative of providing a ZIP file would be to instead provide a UMD build consisting only of a single JavaScript and CSS file which you can copy to the destination project. That would make using it even easier and less complex. This already has been discussed in this issue: https://github.com/telekom/scale/issues/642#issuecomment-1604429622
With the current state of the project the resulting two files however will be extremely large. While it would be the better solution and other projeccts like e.g. React do this as well (see https://unpkg.com/browse/react@18.2.0/umd/) it would need some sort of optimization to get the files smaller.

**Comment by tischrei** [comment]
Really needed for our (Python based) Sphinx projects.

**Comment by acstll** [comment]
> It would be great to have a ZIP file on each tag with the dist output of the build.

Let's do this 👍 

Thanks for opening this @SebastianGode

**Comment by acstll** [comment]
@SebastianGode @tischrei here's a first test, done manually, so you can try it out and make it is what we need.

https://github.com/telekom/scale/releases/tag/v3.0.0-beta.141

We'll automate this next.

**Comment by tischrei** [comment]
Hi @acstll ,
this is what we need. It works very well. 😄 
I would be happy to see this as an automated release.

Thanks in advance
