### ISSUE TITLE
text-field variant succes - icon positioning is off next to helper-text

### ISSUE THREAD

**Issue by RWaelen** [telekom/scale#2146]
**Scale Version**
3.0.0-beta.138

**Framework and version**
Vue 2.6.14 using @telekom/scale-components

**Current Behavior**
scale-text-field variant success has a displaced icon next to the helpertext. This is due to the usage of the wrong icon (no styling is applied to this icon).
currently it uses `scale-icon-action-success` instead of `scale-icon-alert-success`. The correct styling is applied to scale-icon-alert-success, other variants also use the 'scale-icon-alert-*' icons.
![image](https://github.com/telekom/scale/assets/129839179/08bc7628-d137-48bb-9418-b2efb31dd928)

**Expected Behavior**
margins and positioning are inline with other variants (see code reproduction)

**Code Reproduction**
https://codesandbox.io/s/scale-components-vue3-forked-586k3q?file=/src/App.vue

It is also visible in scale's storybook
https://telekom.github.io/scale/?path=/docs/components-text-field--with-success

**Comment by felix-ico** [comment]
this had been fixed and released with beta.142
