### ISSUE TITLE
Footer logo-href not working

### ISSUE THREAD

**Issue by EDR1EN** [telekom/scale#2158]
**Scale Version**
3.0.0-beta.139

**Framework and version**
webcomponents/vite

**Code Reproduction**
If needed, a minimal reproduction case to be used as a basis for discussion. You may fork one of the available sandboxes as a base: 

```
<scale-telekom-footer logo-href="/">
  <scale-telekom-footer-content>
    <span slot="notice"> AEM Communication GmbH & Co. KG Schwalmstadt </span>
    <ul slot="navigation">
      <li>
        <a href="https://schwalmstadt.bstaging.de/impressum/"> Impressum </a>
      </li>
      <li>
        <a href="https://schwalmstadt.bstaging.de/agb/"> AGB </a>
      </li>
      <li>
        <a href="https://schwalmstadt.bstaging.de/datenschutz/"> Datenschutz </a>
      </li>
      <li>
        <a href="https://schwalmstadt.bstaging.de/hinweis-zur-batterieentsorgung/">
          Hinweise zur Batterie- und Elektrogeräteentsorgung
        </a>
      </li>
    </ul>
  </scale-telekom-footer-content>
</scale-telekom-footer>
```

https://dwpc8h-5000.csb.app/

**Additional context**
The logo-href attribute doesn't seem to work. It keeps the default javascript:void() behaviour.

**Comment by TFLXX** [comment]
Did you tried to restart your computer?

Without the code I can give you alot of other advices.

Provide some code and people will be able to help you.

**Comment by felix-ico** [comment]
hi @EDR1EN the `logo-href` is actually a prop for the `telekom-footer-content` component, not `telekom-footer`. Try setting it there and it should work (this is documented here https://telekom.github.io/scale/?path=/docs/components-telekom-footer--standard but you need to click on "telekom footer content" subcomponent on the prop list table).

Please feel free to reopen the issue if this does not solve it.

**Comment by EDR1EN** [comment]
Hey @felix-ico I tried it but it gives me the same outcome, still doesn't work unfortunately.

` <scale-telekom-footer>
      <scale-telekom-footer-content logo-href="/">
        <span slot="notice"> AEM Communication GmbH & Co. KG Schwalmstadt </span>
        <ul slot="navigation">
          <li>
            <a href="https://schwalmstadt.bstaging.de/impressum/"> Impressum </a>
          </li>
          <li>
            <a href="https://schwalmstadt.bstaging.de/agb/"> AGB </a>
          </li>
          <li>
            <a href="https://schwalmstadt.bstaging.de/datenschutz/"> Datenschutz </a>
          </li>
          <li>
            <a href="https://schwalmstadt.bstaging.de/hinweis-zur-batterieentsorgung/">
              Hinweise zur Batterie- und Elektrogeräteentsorgung
            </a>
          </li>
        </ul>
      </scale-telekom-footer-content>
    </scale-telekom-footer>`
