### ISSUE TITLE
The requested module '@telekom/scale-components/loader/index.js' is a CommonJS module, which may not support all module.exports as named exports

### ISSUE THREAD

**Issue by unmeshdusane20** [telekom/scale#2176]
**Scale Version**
^3.0.0-beta.131

**Framework and version**
I am using Vue3 with Vitepress (for documentation) 

**Current Behavior**
on running VitePress npm run docs:dev working fine, but on creating build using npm run docs:build its giving error
SyntaxError: Named export 'applyPolyfills' not found. The requested module '@telekom/scale-components/loader/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@telekom/scale-components/loader/index.js';
const { applyPolyfills, defineCustomElements } = pkg;

**Expected Behavior**
In latest version of node its should expect type = module 

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

[Scale and Plain HTML](https://codesandbox.io/s/scale-components-plain-html-template-qfi9mp)
[Scale and React18](https://codesandbox.io/s/scale-components-react18-75ci1x)
[Scale and React18 with Wrapper Package](https://codesandbox.io/s/scale-components-react18-with-wrapper-xqqkrv)
[Scale and Angular13](https://codesandbox.io/s/scale-components-angular13-kxzv2k)
[Scale and Vue3](https://codesandbox.io/s/scale-components-vue3-b14993)

**Desktop (please complete the following information):**
 - OS: iOS
 - Node: 18.12.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by felix-ico** [comment]
hi @unmeshdusane20 i tried reproducing the issue using our examples/vue-3-boilerplate and adding vitepress and it worked fine, but I am running node 16 locally. When using node 18 a bunch of errors pop up, but they seem to point to vue-cli rather than anything scale specific. 

Could you try running your app using node 16 and see if that works?

**Comment by unmeshdusane20** [comment]
@felix-ico I tried with multiple version of node , please try to add custom theme file in .vitepress -> theme -> index.ts file 
so that you see the error during VitePress build yarn docs:build
```
import DefaultTheme from 'vitepress/theme';
import { applyPolyfills, defineCustomElements } from '@telekom/scale-components/loader';
import "@telekom/scale-components/dist/scale-components/scale-components.css";

applyPolyfills().then(() => {
  // eslint-disable-next-line @typescript-eslint/no-floating-promises
  defineCustomElements(window);
});

export default {
  ...DefaultTheme,
}
```

**Comment by felix-ico** [comment]
I copy pasted your code to the specified location and got no errors on `docs:build`, could you provide a minimal reproducible example? (btw the latest scale version is beta.142)

**Comment by unmeshdusane20** [comment]
@felix-ico this is my packages.json file

{
  "name": "vite-project",
  "private": false,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview",
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:serve": "vitepress serve docs"
  },
  "dependencies": {
    "@telekom/scale-components": "^3.0.0-beta.142",
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vitepress": "^1.0.0-rc.24",
    "vue-tsc": "^1.8.5"
  }
}

**Comment by felix-ico** [comment]
@unmeshdusane20 I am still unable to reproduce, please have a look at this sample repo https://github.com/felix-ico/scale-vitepress

**Comment by unmeshdusane20** [comment]
@felix-ico please see the below repo for your reference  and execute `npm run docs:build`
https://github.com/unmeshdusane20/vite-test/tree/main/vite-project

**Comment by felix-ico** [comment]
@unmeshdusane20 i added a vitepress config as suggested here https://github.com/vuejs/vitepress/issues/2411 and could then run the `docs:build` successfully. Have you tried that already?
