### ISSUE TITLE
scale-dropdown-select not available as React proxy

### ISSUE THREAD

**Issue by luispflamminger** [telekom/scale#2182]
**Scale Version**
```json
"@telekom/scale-components": "^3.0.0-beta.142",
"@telekom/scale-components-react": "^3.0.0-beta.56",
```

**Current Behavior**
I can use the `scale-dropdown-select` web component, but there is no `ScaleDropdownSelect` React proxy available.

**Expected Behavior**
I would expect a React proxy for this component to be available 🙂 

**Code Reproduction**
`npm install @telekom/scale-components@next @telekom/scale-components-react@next`

**Comment by felix-ico** [comment]
hi @luispflamminger the telekom/scale-components and telekom/scale-components-react should be set to the same version. Please set @telekom/scale-components-react to beta.142 and the proxy package should work

**Comment by luispflamminger** [comment]
Thank you @felix-ico!  
Seems like I accidentally installed `@telekom/scale-components-react@latest` instead of `@telekom/scale-components-react@next`. A bit confusing but fixed now. 😄
