### ISSUE TITLE
Data Grid incorrectly line break when vertical scrollbar is active

### ISSUE THREAD

**Issue by K0NZ1** [telekom/scale#2196]
**Scale Version**
v3.0.0-beta.142

**Framework and version**
React: 17.0.2
scale-components-react": "^3.0.0-beta.142",

**Current Behavior**
The problem with the data grid is that when the vertical scrollbar is active (always in Windows), an incorrect line break occurs because the column width is calculated incorrectly. The column width calculation using the properties "width", "stretchWeight", "minWidth" and "maxWidth" does not work as I would understand it.

**Expected Behavior**
When the vertical scrollbar is active (always in Windows), an correct line break occurs because the column width is calculated correctly.

**Code Reproduction**
https://codesandbox.io/s/scale-components-plain-html-template-forked-8qsswc?file=/index.html

**Desktop (please complete the following information):**
 - OS: macOs Monterey Version 12.6
 - Browser: Chrome Version 118.0.5993.117 (Offizieller Build) (arm64)

**Comment by felix-ico** [comment]
Hi @K0NZ1, when i open the sandbox on win10 I get some different results. I can only see a horizontal scrollbar on firefox, and the line break seems fine to me:
![test](https://github.com/telekom/scale/assets/97440128/4d38191f-7f91-4469-bf88-862af0ad3c8a)
