### ISSUE TITLE
Deactivate console outputs

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#2229]
**Scale Version**
3.0.0-beta.143

**Framework and version**
vue 3.3.4

How can I deactivate the console outputs of Scale?
These are extremely annoying when developing. I can't see my own developer outputs properly.
If this is not possible, can you please implement it?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 119.0.6045.199

**Additional context**
![image](https://github.com/telekom/scale/assets/73475493/c1a6e953-4882-4cc4-b9c2-7b5467a23f97)

**Comment by felix-ico** [comment]
Hi @tomkroschwald, at the moment we don't have the option to deactivate those logs for beta components. As a workaround you could use the filtering function in the browser you use for development:

![Screenshot 2023-12-04 at 15 31 52](https://github.com/telekom/scale/assets/97440128/1a4a45ea-7802-4a6d-8c41-4535d4d978f7)

(a hackier workaround could be to redefine `window.console.info = () => {}` on DEV in your project to suppress those, but you would possibly miss out on `console.info()` called by some other library...)

**Comment by tomkroschwald** [comment]
Thanks for the idea. This is now my solution:
```js
const info = window.console.info;
window.console.info = function () {
    const args = Array.from(arguments);
    if (args[0] == "%c scale – β ") return;
    info(...args);
};
```
