### ISSUE TITLE
Tooltip option on action cells (buttons) in Datagrid

### ISSUE THREAD

**Issue by TheSamabo** [telekom/scale#2236]
Hello 
Our idea is to have an option in action (button) to include settings/paramters to enable tooltip on specific action cell (button) in Datagrid

**Describe the use case**
When we woud like to disable specific action on a data row and let user know why it is disabled with a proper tooltip

**Describe alternatives you've considered**
There are no alternatives to do this as far as we know

**Comment by amir-ba** [comment]
I will close this as it is implemented in the new version
