### ISSUE TITLE
scale-dropdown-select: scale-change-event not working

### ISSUE THREAD

**Issue by s-schmitz** [telekom/scale#2238]
**Scale Version**
3.0.0-beta.144

**Framework and version**
React 18.2.0

**Code Reproduction**
```javascript
          <scale-dropdown-select label="select" scale-change={openBookmark}>
            {Array.from(personalBookmarks.entries()).map(([key, bookmark], index) => (
              <scale-dropdown-select-item key={key} value={key}>{bookmark.displayName}</scale-dropdown-select-item>
            ))}
          </scale-dropdown-select>}
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 119

**Additional context**
The 'scale-change' event is not triggered when the value in the dropdown is changed.

Is it a bug or am I doing something wrong?

**Comment by felix-ico** [comment]
hi @s-schmitz in react you should use `onScaleChange`, you can check out the react example here https://github.com/telekom/scale/blob/main/examples/react-form/src/App.tsx

Are you using the web components directly in react, without the wrapper package?

**Comment by s-schmitz** [comment]
Thanks for your advice. That solves my problem. Thanks.
