### ISSUE TITLE
Text Field inner colors remain inverted after autofill

### ISSUE THREAD

**Issue by pgyoerfi** [telekom/scale#2245]
**Scale Version**
3.0.0-beta.142

**Framework and version**
Angular CLI: 17.0.8

**Current Behavior**
When autofill suggestions come up inner color go inverted, however, it remaines inverted even if one of the suggestions is accepted.

**Expected Behavior**
Should exit inverted color style when a suggestion is picked by the user.

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

[Scale and Plain HTML](https://codesandbox.io/s/scale-components-plain-html-template-qfi9mp)
[Scale and React18](https://codesandbox.io/s/scale-components-react18-75ci1x)
[Scale and React18 with Wrapper Package](https://codesandbox.io/s/scale-components-react18-with-wrapper-xqqkrv)
[Scale and Angular13](https://codesandbox.io/s/scale-components-angular13-kxzv2k)
[Scale and Vue3](https://codesandbox.io/s/scale-components-vue3-b14993)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: chrome
 - Version 120
![TextField1](https://github.com/telekom/scale/assets/146071389/b01c8fc9-54e7-46a8-b3ed-d3624dcfe02e)
![TextField2](https://github.com/telekom/scale/assets/146071389/0a1f2b46-e777-4810-9ad7-e670a0fc5c85)
![TextField3](https://github.com/telekom/scale/assets/146071389/41538613-2ecc-444f-98f0-d80969c0356a)

**Additional context**

**Comment by felix-ico** [comment]
this should be fixed in [3.0.0-beta.147](https://www.npmjs.com/package/@telekom/scale-components/v/3.0.0-beta.147), thanks for opening the issue
