### ISSUE TITLE
Error in light mode

### ISSUE THREAD

**Issue by tk-network** [telekom/scale#2262]
**Scale Version**
3.0.0-beta.147

**Framework and version**
plain html/js

**Current Behavior**
If I have activated the dark mode in the system, but force the light mode in the application with ```<body data-mode="light">```, the text color is still white.
If I remove the ```data-mode``` attribute and use the system settings, everything works fine.
The error only occurs with plain html/js, with vue js everything works as usual.
![Bildschirmfoto 2024-01-22 um 07 58 59](https://github.com/telekom/scale/assets/93334942/057cc904-162e-4331-b53c-c6ae234658aa)

**Expected Behavior**
If I force the light mode, the light mode should also be used completely.

**Desktop (please complete the following information):**
 - OS: MacOS or Windows 11
 - Browser: chrome
 - Version: 120.0.6099.234

**Comment by Pravesh-mansharamani** [comment]
I think I can fix this, Can you please assign me this issue!

**Comment by felix-ico** [comment]
hi @tk-network I just tested this and could not reproduce the issue. Just to make sure, do you have 

`
body {
  background-color: var(--telekom-color-background-canvas);
  // this is needed to overwrite standard html elements text color
  color: var(--telekom-color-text-and-icon-standard);
}
`

set in your css?

**Comment by tk-network** [comment]
Yes, that was my mistake. Reading the documentation helps. :D
Thanks for the support!
