### ISSUE TITLE
Scale Telekom Header doesn't close when not hovering above it anymore

### ISSUE THREAD

**Issue by SebastianGode** [telekom/scale#2276]
**Scale Version**
3.0.0-beta.147

**Framework and version**
No Framework.

**Current Behavior**
If you hover over a category in the Slim Header and you go down with your mouse the header won't close automatically.

**Expected Behavior**
The header should close.

**Code Reproduction**
You can use the canvas on the Scale Documentation: https://telekom.github.io/scale/?path=/docs/components-telekom-brand-header-navigation--slim-header
Click on Canvas on the top, then close the menu on the bottom and hover over e.g. "Topic Two". Then go down with the mouse and it won't close automatically after the actual header.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 121

**Comment by tischrei** [comment]
...but it closes when the mouse is moved in the header bar again which feels a bit inconsistent.
