### ISSUE TITLE
scale-text-field not focus when invalid

### ISSUE THREAD

**Issue by huydau91** [telekom/scale#2288]
**Scale Version**
3.0.0-beta.148

**Framework and version**
nextjs 12.1.0

**Current Behavior**
If a `scale-text-field` has the attribute "invalid", so I want to focus on the field to let the user know the field error, but it doesn't. This should not be the case.
![Screenshot 2024-02-27 at 09 48 15](https://github.com/telekom/scale/assets/26104324/e5eca7f5-b1bc-4267-824d-35e56bb1f019)

**Expected Behavior**
I want to focus on the field with the mouse pointer.
![Screenshot 2024-02-27 at 09 49 29](https://github.com/telekom/scale/assets/26104324/f5cd4103-b326-4fd4-954f-cc08ea35e18e)

**Desktop (please complete the following information):**
 - OS: MacOs Ventura 13.4.1
 - Browser: Chrome
 - Version: 121.0.6167.184

**Comment by tshimber** [comment]
hi @huydau91 ! 
could you please clarify where you think the bug is? the input has focused state, at least in the latest version this seem to work fine:
![image](https://github.com/user-attachments/assets/4c0003df-fcd0-4205-b224-43581fa7f88e)

**Comment by amir-ba** [comment]
Will close due to inactivity. Please create an issue with detailed description if required.
