### ISSUE TITLE
Test automation limitations related to data-qa and hydrated classes

### ISSUE THREAD

**Issue by tkolomiets12** [telekom/scale#2290]
**Scale Version**
3.0.0-beta.136

**Framework and version**
react v18.2.0; Auto-generated scale wrapper package: @telekom/scale-components-react package (built for react)

**Code Reproduction**
Example of issue in DOM

![Screenshot 2024-02-29 at 12 07 29](https://github.com/telekom/scale/assets/161712250/f9f72044-0820-4672-b901-5b12a79ff58e)

**Desktop
 - OS: Mac  
 - Browser: Firefox
 - Version: 122.01

**Additional context**
We have the following limitations regarding test automation:

Scale elements which are hydrated are not interactable together with our test automation framework (Playwright + TypeScript)
To interact with elements we need standard element tag with id or data-qa. Within given code example we need to put id or data-qa for button element to interact with it together wit playwright.  Scale components library has some limitations for putting data-qa for button element for example. 

Questions:
1. Is there any known workarounds for E2E FE test automation when we have FE developed with scale component library? 
2. Or some options how to put data-qa or id on each needed element easily (without additional pull requests)?

**Comment by amir-ba** [comment]
can you provide more info about what exactly is your issue with the `data-qa` tag with scale. Because you can add them to the `scale` elements (here to `scale-button` just like you did here) and in your Playwright tests you can treat this like a button component for example for clicking, and you don't necessary need to dig the shadowDOM for the actual button element.

**Comment by amir-ba** [comment]
@tkolomiets12 I will close this, and you can create followup ticket based on your current experience and issues.
