### ISSUE TITLE
Telekom header language switcher not visible

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#2293]
**Scale Version**
beta 150

**Framework and version**
React

**Current Behavior**
Language switcher buttons are moved outside of viewport

**Expected Behavior**
Buttons should be visible

**Code Reproduction**
.scale-telekom-nav-item > button in telekom-profile-menu.css should be scoped so it doen't change language switcher button padding

**Comment by tshimber** [comment]
hi @nikolab-pn ! 
could you please clearify, what component is affected as there are deprecated and new headers. and maybe add screenshot?
in the new header lang swither seem to look ok for me:
![image](https://github.com/user-attachments/assets/c1ee73aa-a016-4a8b-a998-82e1ff6f3434)
![image](https://github.com/user-attachments/assets/a693da80-e86e-4a30-ad5b-23d3d122aa64)

 -- it's here also with profile menu, it disappears on scroll

**Comment by nikolab-pn** [comment]
The issue is visible if inside `scale-telekom-nav-item` instead of `a` element `button` element is used. It's not a big issue, but it's also easy fix

How it looks
<img width="167" alt="image" src="https://github.com/user-attachments/assets/cb234e1b-2bae-4dd4-815b-65c4526f0c7e">


How it should look
<img width="170" alt="image" src="https://github.com/user-attachments/assets/138aceeb-d9a4-42e2-8524-96fac3327cc8">

**Comment by tshimber** [comment]
@nikolab-pn thank you for clarification! we'll fix it
