### ISSUE TITLE
Unexpected blue box around close icon in Scale Modal

### ISSUE THREAD

**Issue by tischrei** [telekom/scale#2304]
**Scale Version**
from your github pages site: 3.0.0-beta.150

**Current Behavior**
Modals are opening and right after there is a blue outlined box around the closing cross / icon of the modal.

**Expected Behavior**
I would expect that the blue rectangular is there while clicking on the closing icon, but at least not all the time.

**Desktop (please complete the following information):**
 - OS: windows 
 - Browser chrome
 - Version Version 123.0.6312.59 (Offizieller Build) (64-Bit)

**Additional context**
![image](https://github.com/telekom/scale/assets/26574398/6c9a056a-a478-40d4-93b3-6df37c07db70)

**Comment by Aloento** [comment]
In Modal, the default focus element is this close button (variant = ghost).
So it's normal for this border to appear.

To fix it, just set the focus to any other element while the Modal is open.

**Comment by amir-ba** [comment]
I will close this as no action would be needed from our side.
