### ISSUE TITLE
[Segmented Button] Collapses in on itself when placed inside a scale-collapsible

### ISSUE THREAD

**Issue by ledex** [telekom/scale#2314]
**Scale Version**
3.0.0-beta.151

**Framework and version**
React 17.0.2 
React 18.2.0

**Current Behavior**
From time to time the segmented button 'collapses' in on itself as seen below when placed inside a scale-collapsible.
![grafik](https://github.com/telekom/scale/assets/39191120/bf2085b1-868b-45ce-a7c1-c555e141483d)

The `scale-segmented-button` spans the entire width, but the individual `scale-segment`s are way to narrow for the text. With `fullWidth={true}` the issue still persists.

**Expected Behavior**
Segmented button should look normal as seen below.
![grafik](https://github.com/telekom/scale/assets/39191120/53aaf41a-5cfc-4b84-be36-da2b8f6371b0)

**Code Reproduction**
https://codesandbox.io/p/sandbox/scale-components-react18-forked-vgwsvy

**Desktop (please complete the following information):**
 - OS: Win11 10.0.22621 Build 22621
 - Browser: Firefox 125.0.3

**Comment by amir-ba** [comment]
this is resolved with https://github.com/telekom/scale/pull/2358 and will be included in the next release
