### ISSUE TITLE
Slim header does not display language switcher on desktop

### ISSUE THREAD

**Issue by haarhoff-frs** [telekom/scale#2323]
**Scale Version**
3.0.0-beta.130

**Framework and version**
Vue 3.4.21 with vite, but the behaviour is also visible in the slim header example in this repo

**Current Behavior**
The language switcher is not displayed on the desktop, even though it is present in the examples HTML

**Expected Behavior**
The language switcher should be accessible on the desktop

**Code Reproduction**
The slim header example in this repo shows the problem

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 125.0.2535.92

**Additional context**
We need to develop a minimal page using the scale header and footer. The page needs to be available in German and English. As we do not have any items in the main navigation (minimal one pager), we want to use the slim header, to avoid all the empty space and have the app name somewhat more prominently displayed. As the language switcher is not visible on the slim header, the visitors will not know that they can switch the language.

**Comment by tshimber** [comment]
hi @haarhoff-frs ! 
I've reviewed the current implementation, and unfortunately, the slim header wasn't designed to include a language switcher. Adding it would require much changes and complications to the component, and we currently don't have capacity for that. By now I can only suggest adding a custom switcher after the profile menu
![image](https://github.com/user-attachments/assets/65c5da5d-5880-47be-ae15-54795cf8dde5)

**Comment by amir-ba** [comment]
This is a design decision, Therefore if needed you can extend  `slot=functions` section of the component child or use the non-slim version . If you need help, you can create another issue, we will try to help you.
