### ISSUE TITLE
Allow access to `<scale-card/>` link attributes/properties

### ISSUE THREAD

**Issue by jwueller** [telekom/scale#2325]
**Describe the feature request**

Allow more direct access to the `<a/>` tag within a `<scale-card/>`.

Currently, only these attributes can be supplied:
* `href`
* `rel`
* `target`
* `aria-label`

Especially when dealing with links, there might be a lot of customized behavior, like attaching various event handlers.

**Describe the use case**

Some examples of attributes that might often be used on links specifically and are currently inaccessible/missing:

* `data-*` - very common for things like analytics, social media and CMS integrations
* `title`
* `download`
* `media`
* `integrity`
* `accesskey`
* `tabindex`
* `hreflang`
* `prefetch`

Not to mention that custom event handlers will always be useful for dealing with exceptional cases, likee having to `preventDefault` to maintain the ability to open in a new tab, while providing button behavior on the current page.

**Describe alternatives you've considered**

Manually manipulating the internal component DOM, but that's a very fragile workaround, especially within a React environment.

**Comment by tshimber** [comment]
@jwueller hi!
we are now out of capacity for nice-to-have features, mostly focused on bug fixing. please specify, if you need some of these attributes for your current project, and we will decide whether to take the issue into our workflow in the near future

**Comment by amir-ba** [comment]
I will close this and if needed please create a ticket/PR later on.
