### ISSUE TITLE
Accessibility | Chip component - only selected chip is availble for keyboard navigation

### ISSUE THREAD

**Issue by kolianovich** [telekom/scale#2328]
Scale Version
"@telekom/scale-components": "3.0.0-beta.152",

Framework and version
"react": "^18.2.0" - without wrapper

**Current Behavior**
Chip component is not availble for keyboard navigation while it is not selected.

![image](https://github.com/telekom/scale/assets/25793946/86718d85-8575-4441-8d68-7a6021318b8b)
 

**Expected Behavior**
Chip must always be availble for keyboard navigation.

**Additional context**
We kindly request to fix it asap because of this issue has 3 thumbs down in accessibility report what considered as critical accessibility issue.

**Comment by amir-ba** [comment]
Dynamic Selection Standard version seems to stlil not be focusable
