### ISSUE TITLE
Accordion component headingLevel property isn't working

### ISSUE THREAD

**Issue by kulabuha** [telekom/scale#2340]
**Scale Version**
3.0.0-beta.152

**Framework and version**
vue 2.7.0  

**Current Behavior**
When I change the heading-level="3" property in the template, there are no visible changes in the browser. The same behavior is observed in the [playground](https://telekom.github.io/scale/?path=/docs/components-accordion--heading-level); adjusting the heading-level does not produce any noticeable effect.

**Expected Behavior**
The font size of the heading section in the collapsible items should change accordingly when the heading-level property is adjusted

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 
[Scale and Vue3](https://codesandbox.io/p/sandbox/scale-components-vue3-b14993?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm06gun4n00063o6kdwyqgnn6%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm06gun4n00023o6kjk555hp2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm06gun4n00033o6kglguom9i%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm06gun4n00053o6k28rq26ce%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm06gun4n00023o6kjk555hp2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm06gun4n00013o6kuoawhh5p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm06gvys200133o6khz5gn3vg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A52%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm06gun4n00023o6kjk555hp2%2522%252C%2522activeTabId%2522%253A%2522cm06gvys200133o6khz5gn3vg%2522%257D%252C%2522cm06gun4n00053o6k28rq26ce%2522%253A%257B%2522id%2522%253A%2522cm06gun4n00053o6k28rq26ce%2522%252C%2522activeTabId%2522%253A%2522cm06h14py000q3o6kjna67uwj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm06gun4n00043o6k3a5zmzot%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm06h14py000q3o6kjna67uwj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm06gun4n00033o6kglguom9i%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm06gun4n00033o6kglguom9i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Desktop (please complete the following information):**
 - windows
 - chrome, edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tshimber** [comment]
hi @kulabuha ! I guess it's described in storybook not clear enough, but this prop isn't supposed to change how element looks, it's the accessibility prop, which influences aria-level value. It is also used in other components with same logic. 
![image](https://github.com/user-attachments/assets/9acd44a6-75a3-43de-92e3-3b23f7edd961)

If different "looks" of accordion are needed, it's a feature request. We don't have UI designer available now, so I don't think we can take that one in nearest future.

**Comment by kulabuha** [comment]
Hi @tshimber! Thanks for the explanation! I'll go ahead and close the bug ticket.
