### ISSUE TITLE
Collect data from text inputs

### ISSUE THREAD

**Issue by MishaYanen** [telekom/scale#2350]
**Scale Version**
scale-components 3.0.0-beta.152

**Framework and version**
Angular 15

**Documentation Request**
Text field
There is no way and no examples in documentation to collect data from inputs and pass it to component

**Comment by tshimber** [comment]
hi @MishaYanen ! 
you can collect data with 'value' prop which is available for all types of scale inputs.

these are different ways to get the value, e.g:

1)` (document.getElementById('input') as HTMLInputElement).value;`

2) ```
@ViewChild('input') private input!: ElementRef;
this.input.nativeElement.value
```

3) ```
<scale-text-field
      #input
      [value]="value"
      (scale-change)="onValueChange(input.value)"
    ></scale-text-field>
    
onValueChange(newValue: string | number | null | undefined): void {
    console.log(newValue);
}
```
i will discuss with colleagues if we should put it everywhere to docs

**Comment by amir-ba** [comment]
@MishaYanen, I will close this as the suggested method will work. And we are also planning to give our docs an overhaul. So it will also be more clear in the future.  You can also open another issue if you have a more specific problem or question.
