### ISSUE TITLE
Problems with integrating into React

### ISSUE THREAD

**Issue by hermano** [telekom/scale#247]
I tried to integrate @Scaleds into my React App, but it failed to compile.

> Failed to compile
./node_modules/@scaleds/components-react/dist/components.js
Module not found: Can't resolve '@scaleds/components/loader' in '/Users/hermann/git-repos/telekom-test/node_modules/@scaleds/components-react/dist'
This error occurred during the build time and cannot be dismissed.

Unfortunately I am not sure whether the fault is on my side or it's because there is a conflict with the React Version (or something else).

Kind regards

**Comment by acstll** [comment]
Do you have `@scaleds/components` installed as a dependency in your project?

**Comment by hermano** [comment]
Yes I had, but following was necessary within scale clone:

```bash
yarn clean
yarn build
yarn build:components
yarn bootstrap
```

and afterwards within my react app repo:

```bash
yarn add @scaleds/components
````

I think the problem was, that the components haven't been build correctly. Looking forward for some testing and adopting now. 👍
