### ISSUE TITLE
Open Modal Dialog - how?

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#314]
Hi there,
First of all, thank you for this great project. We will use these components in our project and it will save us alot of time. We use react as JS-Framework combined with Tailwind CSS for styling.

I tried most of the components, but I have a problem with the modal dialog. How are they opened , with the buttons - with id? I have no Idea and there are no examples. Sure its trivial if you know how ;) Thanks for the help..

**Comment by acstll** [comment]
Thank you @tommy-codez for your question and your kind words.

For opening you need to set the `opened` attribute to `true`. e.g.:

```jsx
const [isOpen, setIsOpen] = useState(false)
/* ... */
<ScaleModal opened={isOpen} />
```

If the modal is closed from within itself (with the X on the top right corner), you can listen for the `scaleClose` event (I believe it's `onScaleClose={...}` in JSX) so you can set reset your state (e.g. `isOpen`) to `false`.

We will try and improve the documentation in this regard.

Let me know if this helps.

---

Also, there is room for improvement in the logic, like for instance, adding an event previous to `scaleClose` that would prevent the modal from closing if `event.preventDefault()`ed.

**Comment by tommy-codez** [comment]
Cool, it worked :) Thank you for your fast help...
Saved me some hours :) have a nice weekend.
