### ISSUE TITLE
Styles interfere with other npm modules

### ISSUE THREAD

**Issue by jamie-magenta** [telekom/scale#340]
Hello,
I am currently trying to implement [NgxCharts](https://github.com/swimlane/ngx-charts) in a project that contains Scale.
For some reason all the charts are black instead of the color they should be.
After some research in the chrome DevTools, it seems that the style of [app-navigation-main-mobile.css](https://github.com/telekom/scale/blob/f8dfb535bdd0be05c951819ad0a07fffb204a47d/packages/components/src/components/telekom/app-navigation-main-mobile/app-navigation-main-mobile.css) is causing these problems:
```css
svg path {
  fill: inherit;
}
```
The styles are applied globally and therefore affect other components as well, but I'm not sure if just removing this would break something else.
Is it possible to change this behavior?

**Comment by nowseemee** [comment]
hi Jamie, this should be scoped indeed - I'll ship a patch today. Sorry for the inconvenience!

**Comment by jamie-magenta** [comment]
Hi Daniel,
no problem, thank you! 😃

**Comment by nowseemee** [comment]
The fix is released `3.0.0-beta.9` - thanks for bringing this to my attention!
