### ISSUE TITLE
Scale and VUE 3

### ISSUE THREAD

**Issue by Chrisprie** [telekom/scale#351]
Hi,
Unfortunately, I have some issues using Scale… Is VUE 3 already supported? If not: Is Scale planned to support Vue 3 in the future and how long does it probably take?

For example:
import { ScaleButton } from '@telekom/scale-components-vue';
causes in a warning: "export 'default' (imported as 'Vue') was not found in 'vue'
But when loading the Website, it does not show anything anymore.

When using other components some are working just as expected others don’t.

Thank you for your support

**Comment by acstll** [comment]
Thanks @Chrisprie for opening this issue.

The generated `@telekom/scale-components-vue` package is built specifically for Vue 2, so indeed and unfortunately Vue 3 is currently unsupported.

You can still use the components without the Vue specific package. If you load the core library as the documentation suggests:

```js
import Vue from 'vue';
import {
  applyPolyfills,
  defineCustomElements,
} from '@telekom/scale-components/loader';
import '@telekom/scale-components/dist/scale-components/scale-components.css';

Vue.config.productionTip = false;
Vue.config.ignoredElements = [/scale-\w*/];

applyPolyfills().then(() => {
  defineCustomElements(window);
});
```

you can use them without importing them, so no need to do `import { ScaleButton } from '@telekom/scale-components-vue';`, rather just use the component directly with the native custom element syntax: `<scale-button></scale-button>`.

I hope this helps.
