### ISSUE TITLE
React: Footers icon not displayed

### ISSUE THREAD

**Issue by alzalabany** [telekom/scale#354]
Introduction

footer component has `footerNavigation` prop that accept an array to show links list. those links can have a `icon` prop. that display icon by its name to the right side of link

## Current Behavior

not all icons works with `footerNavigation` icon prop, some icons appears correctly while others/most appear empty

**example:** https://codesandbox.io/s/reactscaleplayground-footer-icons-spzod?file=/src/App.js

```
<ScaleAppFooter
  footerNavigation={[
					{
						name: "User Profile",
						id: "User Profile",
						href: "/profile",
						icon: "user-file-user",
					},
					{
						name: "Legal notice",
						id: "Legal notice",
						href: "#legal-notice",
						icon: "alert-add",
					},
					{
						name: "Data privacy",
						id: "Data privacy",
						href: "#data-privacy",
						icon: "alert-imprint-dataprivacy",
					},
				]}
			/>
```

following snipper, only 3rd link "alert-imprint-dataprivary" will show icon, other 2 icons will appear empty

## Expected Behavior

- [ ] all supported icons should work, otherwise documentation should tell us available icons
- [ ] strong typing for `variant` & `footerNavigation` props

```ts
type ScaleIconName = "alert-imprint-dataprivacy" | "user-file-user" // | .... all available icons

type ScaleAppFooterNavigation  = {
  name: string;
  id?: string;
  href?: #string
  icon?: ScaleIconName
}

interface footerNavigation {
  variant?: 'minimal' | 'angular' | 'normal'
  footerNavigation: ScaleAppFooterNavigation[]
}
```

**Comment by nowseemee** [comment]
Hi @alzalabany, thanks for reporting this issue - the patch is shipped with the latest version: `3.0.0-beta.10`.
