### ISSUE TITLE
Footer component does not look nice if parent background is not white

### ISSUE THREAD

**Issue by alzalabany** [telekom/scale#358]
[Example playground:](https://codesandbox.io/s/reactscaleplayground-footer-icons-spzod?file=/src/App.js)

## Introduction:

Footer has 2 spikes at the top on right and left that give cool semi-circule effect, this effect is created by overlaying a white band with curved border-radius;

## Current Problem

- space between those spikes is currently set to `var(--background-mask);`"white"  so they look very odd on pages with image background. [Example playground]

- even if we override `.footer-mask` class inside its shadow dom using `::shadow .footer-mask` -which has its browser limitation- to match solid colors, this is still a problem when background of parent is an image, or is dynamic (carousel of images directly above footer for example).

## Proposal

change structure of footer mask a little to allow transparent background instead of solid color.

**Comment by nowseemee** [comment]
Hi @alzalabany,

you can easily override the background color: 

```
:root {
  --scl-color-background-standard: #444;
}
```

Unfortunately,  image backgrounds are not supported. You can try setting the `variant` attribute to `angular` to get rid of the rounded corners altogether when necessary.
