### ISSUE TITLE
Icons not visible at http://localhost:3333

### ISSUE THREAD

**Issue by ChrisPaj** [telekom/scale#382]
When starting the scale project preview I can not see any icons on index.html at http://localhost:3333/

**Comment by acstll** [comment]
@ChrisPaj can you post a screenshot? I see some icons, but others are not showing because of out-dated syntax.

We should definitely clean up this index.html file.

**Comment by Lalaluka** [comment]
I guess you mean the Buttons?

![Bildschirmfoto 2021-06-04 um 15 34 56](https://user-images.githubusercontent.com/26364692/120809543-766c6880-c54a-11eb-9b9d-391ae5564470.png)

Index-html Line 585
```html
<h3>Button icon Before</h3>
<scale-button
  icon-before="M10 2a8 8 0 016.472 12.703l4.912 4.913.06.065a1.25 1.25 0 01-1.726 1.794l-.102-.091-4.913-4.912A8 8 0 1110 2zm0 1.5A6.508 6.508 0 003.5 10c0 3.584 2.916 6.5 6.5 6.5s6.5-2.916 6.5-6.5-2.916-6.5-6.5-6.5z">
  Hello
</scale-button>

<h3>Button icon only</h3>
<scale-button
  icon="M10 2a8 8 0 016.472 12.703l4.912 4.913.06.065a1.25 1.25 0 01-1.726 1.794l-.102-.091-4.913-4.912A8 8 0 1110 2zm0 1.5A6.508 6.508 0 003.5 10c0 3.584 2.916 6.5 6.5 6.5s6.5-2.916 6.5-6.5-2.916-6.5-6.5-6.5z">
</scale-button>
```
The Syntax is outed and the button doesn't use the icon Prop anymore but should use Icons in the `slot` e.g.
```
<scale-button icon-only="true">
  <scale-icon-navigation-external-link accessibility-title="External link, opens in new tab"></scale-icon-navigation-external-link>
</scale-button>
```

I can write a quick PR for the Button Icons. I could not find any other occurrences of missing icons personaly.

**Comment by acstll** [comment]
thank you @Lalaluka 🙏
