### ISSUE TITLE
The Main Navigation links refreshes entire page in a React Application. 

### ISSUE THREAD

**Issue by gaurishkamat** [telekom/scale#387]
I am using version `3.0.0-beta.12` and have added few links in the main navigation as follows:

```
<ScaleAppShell
            className='scale-app-shell'
            claimLang='en'
            portalName='TV Recommendations'
            mainNavigation={[{
                name: 'User Testing',
                id: 'user_testing',
                children: [
                {
                    name: 'Testing',
                    id: 'testing',
                    href: '/usertesting',
                },
                ],
            }]>
</ScaleAppShell> 
```
On click of "Testing" I am rendering a new component. However, the entire page is refreshed when I route to different links.
Is it the correct way I am using the ScaleAppShell or I need to change the code.

**Comment by eeegor** [comment]
Hi @gaurishkamat, thanks for opening this up. We provide a `onClick` event for children elements which should work for your usecase. 

Best,
Egor

**Comment by christopherGdynia** [comment]
See #362, there is an example how to solve routing in react.

**Comment by gaurishkamat** [comment]
Hi @eeegor and @christopherGdynia that helped me getting the job done. Thanks a lot!!
