### ISSUE TITLE
V-Model is not working as expected with scale fields

### ISSUE THREAD

**Issue by vvichare** [telekom/scale#402]
I have added  scale components in app.vue as below,

Vue.extend({
  name: 'app',
  components: { ScaleTextField, ScaleTextarea }
});

and in one of my .vue component I am using this as,
<scale-text-field label="Name"
    v-model="jobTitle"
    autofocus="autofocus"
    :helperText="duplicateTitleError === 'error' ? 'Duplicate name' : invalidError === 'error' ? 'Special characters are not allowed!' : 'Max.25 Characters'"
    maxLength=25  
    :disabled="isTitleDisabled" 
    @scaleChange="checkNameDuplicacy()"
    :status="duplicateTitleError || invalidError"
></scale-text-field>

but v-model value return me length of value even though I have declared it as 'string'. I am using typescript.

**Comment by vvichare** [comment]
Hi, 
Any updates on this? can we use v-model on scale components by any chance? Actually we are in process of upgrading scale version and in our project and we have used v-model at lot of places since it was supported earliar in 1.x versions of scale (with proxy usage). now our builds are failing since @scaleds is deprecated. So its bit urgent.
@acstll

**Comment by acstll** [comment]
Hey @vvichare thank you for opening this.

You can manually do the bindings. It should also be possible to "configure" the v-model behaviour. I would like to try something out first so I can provide some good examples for you, I couldn't find the time today. I will do this tomorrow first thing.

I'm guessing you're using Vue 2, is that correct?

**Comment by vvichare** [comment]
Thank you @acstll for reply! Yes We are using vue 2.6.10

**Comment by acstll** [comment]
Hello @vvichare, thanks for your patience.

Here's the example I wanted to provide for how you can replace the `v-model` directive, with an extra line.

`v-model` is sugar for 2-way binding on native inputs. I'm copy/pasting from the [Vue docs](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components), so you don't have to go there now. (I'm pasting the links below for reference.)

> Remember that:

```html
<input v-model="searchText">
```

> does the same thing as:

```html
<input
  v-bind:value="searchText"
  v-on:input="searchText = $event.target.value"
>
```

## Example

So the example looks like this:

```vue
<template>
  <div>
    <scale-text-field 
      label="Name"
      :value="jobTitle"
      @scaleChange="jobTitle = $event.target.value"
    >
    </scale-text-field>

    <p>{{ jobTitle }}</p>
  </div>
</template>

<script>
import Vue from "vue";
 
export default Vue.extend({
  components: { /* no components imported, not needed */,
  data: () => ({
    jobTitle: "Lorem ipsum",
  }),
  watch: {
    jobTitle: function () {
      this.checkNameDuplicacy()
    }
  },
  methods: {
    checkNameDuplicacy: function () {
      // ...
      console.log(this.jobTitle)
    },
  },
});
</script>
```

You bind the component's `value` to your `jobTitle` prop, and listen for changes to update `jobTitle`.

In summary, this is the change:

```diff
-v-model="jobTitle"
+v-bind:value="jobTitle"
+v-on:scaleChange="jobTitle = $event.target.value"
```

In the example above I'm using the shorter syntax:

```diff
-v-model="jobTitle"
+:value="jobTitle"
+@scaleChange="jobTitle = $event.target.value"
```

I also suggest using a watcher to track changes directly on the prop for running any validation checks.

---

We're going to be deprecating the proxy packages in the near future, for many reasons, the most important one being lack of Vue 3 support.

That's the reason why I'm not using them in the example.

---

## Links for reference

What `v-model` does:
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

How to configure `v-model` if you wanted to create wrapper components for your inputs:
https://vuejs.org/v2/api/#model

`v-model` changes in Vue 3:
https://v3.vuejs.org/guide/migration/v-model.html#overview

**Comment by vvichare** [comment]
@acstll Thank you very much for the examples and clarifications. I have already thought of this approach and trying to fix components. But we are already in advanched development step and we have to manually go and fix lot of components it means touch almost every functionality in our application and so lot of re-testing is required. so was trying to find out with you that is there any way if we can make the scale library accept v-model as directive on components so that we can avoid overall turnaround for this.

**Comment by acstll** [comment]
@vvichare you're very welcome.

It's definitely possible to fix the "v-model" for the current `@telekom/scale-components-vue` package. I will get in touch with by email if I need more details.

Like I mentioned earlier, we do have plans to deprecate the proxy package, so in the long run (and in my humble opinion) avoiding `v-model` is a better option because it's way more resilient, and would even allow you to easily upgrade to Vue 3.

However, I perfectly understand your situation, so let's work in that direction.

**Comment by vvichare** [comment]
@acstll Thank you very much for understanding and quick turnarounds. Waiting for the realese. (y)

**Comment by acstll** [comment]
[v3.0.0-beta.14](https://github.com/telekom/scale/releases/tag/) is out with `v-model` working for the following components:

- `scale-input`
- `scale-text-field`
- `scale-text-area`
- `scale-dropdown`
- `scale-slider`
- `scale-switch`

It was not possible to do it for `scale-checkbox` and `scale-radio-button` (but those weren't supported in the previous version anyways). If you needed some help with these, I could also provide some examples. We're happy to help.

@vvichare please try it out when you get a chance and let us know how it goes.

**Comment by vvichare** [comment]
@acstll Awesome! you are super quick! Sorry for late reply. I was doing some testing on application and v-model is working perfectly fine on most of the components now. for others had to do some minor tweaks. Thank you very much! You saved our lot of time!

**Comment by acstll** [comment]
Perfect. I'm super glad to hear it's working with only some minor tweaks.

Feel free to get in touch 👍
