### ISSUE TITLE
TextFieldElements KeyDown Enter doesnt trigger Form Submit

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#404]
Hi,

I am trying Formik in React with ScaleTextField-Elements, when I am pressing the enter key inside a Form it should submit the Form.
I logged every keyDownEvent, but when I am pressing Enter the eventlistener isn't triggered.

**Comment by tommy-codez** [comment]
Hi there , I did something similar with
```
 const onKey = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      onSubmitHandler(e);
    }
  };
```

dunno if it helps :)

best wishes

**Comment by acstll** [comment]
Thank you @tommy-codez! That is definitely one way to handle it.

Pressing Enter while the focus is on an input element inside a form will submit the form. This is native browser behaviour as you already know. The input being inside the Shadow DOM breaks this, which is very unfortunate but we have to work around it.

I'm thinking it would be possible to add such logic to all form control components: listen for the Enter key being pressed, and if the component lives inside a form (using `closest()` on the host), we call `submit` on it.

Do you see any down sides to this idea?

Thanks for opening this @christopherGdynia

**Comment by christopherGdynia** [comment]
Hello there,

Will this be implemented out of the box in the future?

**Comment by W1ckh3ad** [comment]
Hello guys I have a nice solution,

I am putting an `Eventlistener` on a `Form`, the sandbox is [here](https://codesandbox.io/s/clever-matsumoto-6ozeji?file=/src/App.tsx)

```tsx
import "./styles.css";
import { Formik, Form } from "formik";
import { ScaleTextField } from "@telekom/scale-components-react";
import { FC, useEffect, useRef } from "react";

const NewForm: FC = ({ children }) => {
  const ref = useRef<HTMLFormElement>(null);
  useEffect(() => {
    const elem = ref.current;
    if (!elem) return;
    const listener = (e: Event) => {
      if (
        e.key === "Enter" &&
        e.target.classList.contains("text-field__control")
      ) {
        (e.target as any).closest("form").submit();
      }
    };
    elem.addEventListener("keydown", listener);
    return () => {
      console.log(elem.removeEventListener("keydown", listener));
    };
  }, []);
  return <Form ref={ref}>{children}</Form>;
};

export default function App() {
  return (
    <>
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Formik
          initialValues={{ name: "hello" }}
          onSubmit={() => alert("hello")}
        >
          {() => (
            <NewForm>
              <div>test</div>
              <ScaleTextField label="Test" />
            </NewForm>
          )}
        </Formik>
      </div>
    </>
  );
}


```
