### ISSUE TITLE
Scale radio button throws max call stack error

### ISSUE THREAD

**Issue by vvichare** [telekom/scale#406]
Getting below error in browser console when trying to use scale radio box,

[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1893
globalHandleError @ vue.runtime.esm.js?2b0e:1888
handleError @ vue.runtime.esm.js?2b0e:1848
eval @ vue.runtime.esm.js?2b0e:1991
flushCallbacks @ vue.runtime.esm.js?2b0e:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1942
nextTick @ vue.runtime.esm.js?2b0e:1999
queueWatcher @ vue.runtime.esm.js?2b0e:4418
update @ vue.runtime.esm.js?2b0e:4560
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
eval @ vue-router.esm.js?8c4f:2508
eval @ vue-router.esm.js?8c4f:2507
updateRoute @ vue-router.esm.js?8c4f:1997
eval @ vue-router.esm.js?8c4f:1875
eval @ vue-router.esm.js?8c4f:1984
step @ vue-router.esm.js?8c4f:1714
step @ vue-router.esm.js?8c4f:1721
runQueue @ vue-router.esm.js?8c4f:1725
eval @ vue-router.esm.js?8c4f:1979
step @ vue-router.esm.js?8c4f:1714
eval @ vue-router.esm.js?8c4f:1718
eval @ vue-router.esm.js?8c4f:1964
eval @ vue-router.esm.js?8c4f:1792
iterator @ vue-router.esm.js?8c4f:1943
step @ vue-router.esm.js?8c4f:1717
eval @ vue-router.esm.js?8c4f:1718
eval @ vue-router.esm.js?8c4f:1964
eval @ routes.ts?80b0:27
Promise.then (async)
profileProtectedRouteGuard @ routes.ts?80b0:25
iterator @ vue-router.esm.js?8c4f:1943
step @ vue-router.esm.js?8c4f:1717
step @ vue-router.esm.js?8c4f:1721
eval @ vue-router.esm.js?8c4f:1718
eval @ vue-router.esm.js?8c4f:1964
eval @ router.ts?5f86:26
iterator @ vue-router.esm.js?8c4f:1943
step @ vue-router.esm.js?8c4f:1717
eval @ vue-router.esm.js?8c4f:1718
eval @ vue-router.esm.js?8c4f:1964
beforeRouteLeave @ JobCatalog.vue?54ee:679
boundRouteGuard @ vue-router.esm.js?8c4f:2080
iterator @ vue-router.esm.js?8c4f:1943
step @ vue-router.esm.js?8c4f:1717
runQueue @ vue-router.esm.js?8c4f:1725
confirmTransition @ vue-router.esm.js?8c4f:1972
transitionTo @ vue-router.esm.js?8c4f:1874
push @ vue-router.esm.js?8c4f:2181
push @ vue-router.esm.js?8c4f:2534
navigateToRoute @ App.vue?94b1:221
onClick @ App.vue?94b1:154
clickLink @ scale-app-header.entry.js?03bb:106
vue.runtime.esm.js?2b0e:1897 RangeError: Maximum call stack size exceeded
    at new Watcher (vue.runtime.esm.js?2b0e:4465)
    at mountComponent (vue.runtime.esm.js?2b0e:4088)
    at VueComponent.Vue.$mount (vue.runtime.esm.js?2b0e:8459)
    at init (vue.runtime.esm.js?2b0e:3137)
    at createComponent (vue.runtime.esm.js?2b0e:6022)
    at createElm (vue.runtime.esm.js?2b0e:5969)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6521)
    at VueComponent.Vue._update (vue.runtime.esm.js?2b0e:3960)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4081)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495)

my code:

<template>
<scale-radio-button></scale-radio-button>
</template>

import {Component, Vue} from 'vue-property-decorator';
    import {STATIC_DATA} from '@/store/modules/staticdata/getters/getter-types';
    import { SEND_SUPPORT_QUERY } from '@/store/modules/Support/actions/action-types';
    import { CONSTANTS } from '@/common/constants';
    import { ScaleRadioButton } from '@telekom/scale-components-vue';

    Vue.extend({
      name: 'Support',
      components: { ScaleRadioButton }
    });

**Comment by acstll** [comment]
thank you @vvichare I'm taking a look…

**Comment by acstll** [comment]
I couldn't reproduce this bug unfortunately. I was able to import it and use it without issues.

I'm gonna give it a second try today. Could you share the code related to the radio button, or you get the error only by importing it?

Thank again.

<img width="1440" alt="Captura de Pantalla 2021-06-15 a les 13 40 08" src="https://user-images.githubusercontent.com/851105/122168010-06c87880-ce7c-11eb-86fe-bd72060b0513.png">

**Comment by acstll** [comment]
I'm closing this in lack of feedback, but feel free to open back again :)
