### ISSUE TITLE
Notifications are missing

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#409]
Hello dear community,

could not find any Notifications bar or similar that we can use to inform users when something is going on. Currently everybody using own style and looks not so cool.

You can specify kind of notifications bar below main menu, or as e.g. chat similar popup on the side of the page.

Main point is to give UI possibility to notify user about something important.

Cheers,
Georgiy.

**Comment by christopherGdynia** [comment]
Hi @GAS85, 

I totally agree with you and wanted to ask same question, 
When I have looked up the source code yesterday, there already exists a branch building it, thus it is work in progress

Additionally it would be really nice to have some popperjs like tooltips

**Comment by GAS85** [comment]
Hey, is there any update here? Could you please bump Version where it's being solved? Or may be reopen Ticket till it being solved? Thanks :)

**Comment by acstll** [comment]
Hey @GAS85 

definitely, I will post it here when this component is out.

Thank you!
