### ISSUE TITLE
Second LvL on main Navigation is moving across the bars

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#411]
Hello dear community,

Not sure if it is only an example is wrong, or it is common issue. But second LvL navigation is slightly moving across the page: 
![grafik](https://user-images.githubusercontent.com/6813635/122207845-e1029a00-cea2-11eb-9fdd-8f2fa6adf0ff.png)

Could you please check, possible that example in brand design needs to be updated.

Cheers,
Georgiy.

**Comment by nowseemee** [comment]
Hi Georgiy, thanks for opening this issue.

I had a closer look and the width of each column in the mega-menu is determined dynamically based on the number of columns and the length of the text in each column.

In the storybook example, `Topic One` has four columns but `Topic Two` has five - hence the difference in the position of columns in the grid template.

Everything under 5 columns should not have any jumps.

Does this help?

Cheers,
Daniel

**Comment by GAS85** [comment]
Hi Daniel,

I see, thanks for explanation. One question left: there is a plenty of space left even with 5 columns:
![grafik](https://user-images.githubusercontent.com/6813635/123805953-c858a200-d8ee-11eb-9154-6325fbc44344.png)

should we improve here?

Cheers,
Georgiy.

**Comment by nowseemee** [comment]
Hi Georgiy, this depends on the screen resolution used - we need to consider all screen sizes matching the desktop breakpoint. If you have any ideas on how to improve this, please let us know. Many thanks.
