### ISSUE TITLE
How to properly use AppFooter

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#413]
Hello there,

How should I place the AppFooter, inside or outside of the AppShell. If I am using it inside the AppShell, it gets padding like any other element inside AppShell.

**Comment by nowseemee** [comment]
Hi @christopherGdynia, currently you should place it outside of the shell. We might revisit the idea of including the footer in the app shell similar to how the header is done.

**Comment by christopherGdynia** [comment]
Ok, thank you, have a nice day :D
