### ISSUE TITLE
Overlay badge for Icons/IconButtons/Avatars

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#416]
Hi,

I hope it's ok that I bomb you with ideas about new components :D 

I am missing a badge that can show some extra info to the user, like 5 messages are unread or there are messages unread.

Down below is a git repo which shows an example about how you could implement it. 

[git repos](https://github.com/frontend-joe/react-perfect-badge)

Thanks a lot for your work 👍

**Comment by acstll** [comment]
Ideas, feedback(, bug reports and contributions) always welcome!

Thank you @christopherGdynia 

I can't tell you when it will be ready, but such component is currently in the works https://github.com/telekom/scale/pull/394 :)
