### ISSUE TITLE
styles prop in Checkbox having no function

### ISSUE THREAD

**Issue by Lalaluka** [telekom/scale#427]
Hi ✌️,
the prop `styles` defined in Line 49 of the checkbox.tsx has no function.
At least I cant identify any.
I don't know if it should be removed or should have the same Styling functionality as other styles props.

**Comment by acstll** [comment]
hey @Lalaluka :) 

this `styles` prop is an "undocumented" feature, and it's meant to be a "last resort" option for adding some custom styles to components with Shadow DOM enabled.

All form control type of components, including Checkbox, have no Shadow DOM so this prop is rather useless. But we keep it there —for now— for a couple of reasons: that we might end up enabling Shadow DOM for this components, consistency and legacy.

Does that make sense to you?

**Comment by Lalaluka** [comment]
Jup makes sense.

The `styles` prop without shadow Dom doesn't benefit anyone and would lead to confusion that's true.

Leaving a prop without any functionality in the documentation (for checkboxes at least they are in the Storybook) confuses me a bit tho. Because it suggests the same functionality as components with a working `styles` prop.

**Comment by acstll** [comment]
The _cleanest_ imo would be:

- component has Shadow DOM: it has the `styles` prop
- component has no Shadow DOM: no `styles` prop

Thinking about removing this `styles` prop: removing a prop is considered a breaking change, but since these don't do anything, it shouldn't be problem, right?

**Comment by Lalaluka** [comment]
Yeah I would agree.

Removing an HTML/Webcomponent prop that doesn't do anything leads to the attribute just sitting there not being pulled by any JS. So it wouldn't lead to any Errors or changed behaviors for users.

**Comment by nowseemee** [comment]
So styles prop is here to stay 🤝
