### ISSUE TITLE
Let's add an Actions field cell type to DataGrid

### ISSUE THREAD

**Issue by darnel-T** [telekom/scale#433]
In our application at Telekom we need to eidit, and destroy an object represented by a row in a table.
We really like how the DataGrid operates, but it lacts the capability to add these kind of actions for each row.
We would like to implement something like this:

![image](https://user-images.githubusercontent.com/86777417/124110834-eba75c80-da68-11eb-888c-09ea044ab700.png)

We in our team think that this is a general idea which is very common among applications.
We are more than ready to implement this (with my college @sagi-T), I hope you welcome this contribution! :)

**Comment by acstll** [comment]
Hey @darnel-T thanks for opening this!

This sounds good to me :) Please let us discuss it internally with the Scale team —we'll do it asap—, and get back to you.

Do you have an idea already of how you would implement this?

**Comment by sagi-T** [comment]
After defining the column action as a field type we would let the rows array accept a `HTMLElement` objects.
Just as in the HTML field type without the accordion scale-button. 



```
const fields = [
  {
    type: 'text',
    label: 'Name',
  },
  {
    type: 'actions',
    label: 'Actions',
  },
]; 



const rows = [
"john",
document.createElement("scale-button"),
]
```
It would be up to the developer to implement the actions part as needed something like this
![image](https://user-images.githubusercontent.com/86777428/124118743-f31f3380-da71-11eb-927b-ccc636aa657a.png)

**Comment by acstll** [comment]
Perfect. We have to check with design too but we need to wait until next week for that.

Let's keep in touch. Thanks again!

**Comment by darnel-T** [comment]
Thanks, cat wait! :)

**Comment by acstll** [comment]
Hello @darnel-T @sagi-T :)

We are currently having a discussion with the design team regarding whether we should limit what one would be able to put into this new Actions cell type. So instead of having a space where you put could anything —like the current HTML type—, accept something more structured, like an array of items that would represent an action (like an icon and a callback, for instance). The whole point would be making sure we maintain the design language of the system by enforcing only certain elements. Does that make sense?

The implementation would change a bit, but not that much, no?

(I wanted to share also that it seemed clear to us that this addition is aligned with the idea of serving common use cases!)

**Comment by darnel-T** [comment]
It is a perfect proposition.
Let's do it in a more structured way.
Like this?

```
const fields = [
  {
    type: 'text',
    label: 'Name',
  },
  {
    type: 'actions',
    label: 'Actions',
  },
]; 



const rows = [
"john",
[
   {
       label: 'Edit',
       icon: 'scale-icon',
       onClick: handleEditClick
    },
    {
       label: 'Edit',
       icon: 'scale-icon',
       onClick: handleEditClick
    }
]
```

**Comment by acstll** [comment]
That looks good.

We're thankful and pretty much looking forward to your contribution and collaborating together.

**Comment by darnel-T** [comment]
Cool! Can we start implementing this?
Can we do this the with the structure above?
If so, we will start the implementation!

**Comment by acstll** [comment]
> Cool! Can we start implementing this?
> Can we do this the with the structure above?
> If so, we will start the implementation!

yes, please!

Once you have a PR up, we'll review it and we'll work together until it's good to merge.

Again, looking forward to it. Thank you!

**Comment by darnel-T** [comment]
#444 @sagi-T has finished to PR. Please check it, looking forward to your feedbacks.

Actions field type looks like this:

![image](https://user-images.githubusercontent.com/86777417/125088425-acfb4d00-e0cd-11eb-87ad-cf23e4528077.png)

**Comment by acstll** [comment]
Thank you very much @sagi-T! :)

I will check it out today (I was off yesterday)

**Comment by darnel-T** [comment]
Cool, we are looking forward to your feedback!

**Comment by darnel-T** [comment]
Hey @acstll!
Thanks for merging our pull request.
Any estimation when will it be released?
We are looking forward to use this changes in our project :)
Thanks for your help!

**Comment by acstll** [comment]
Hey @darnel-T 

We couldn't do the release yesterday. Unfortunately there is an issue with a package that makes the release pipeline fail. But we're trying to fix it now and the new beta release will be out right after.

I'll let you know :)

**Comment by acstll** [comment]
@darnel-T `3.0.0-beta.16` is out.

I hope it works as expected, let me know if it doesn't.

Thanks for the patience, but mostly for the amazing contribution!

**Comment by darnel-T** [comment]
Pretty amazing!
Thanks for this quick journey together.
I hope we can contribute again in the future!
