### ISSUE TITLE
Multiselect/Dropdown

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#439]
Hi there,

a multiselect option for dropdown or similiar component would be nice to have :)

Something like this
![grafik](https://user-images.githubusercontent.com/66920189/124888160-21eb5b80-dfd6-11eb-921d-8955c649dbd5.png)

I am not sure about accessible for this, though...

Greetings

**Comment by Lalaluka** [comment]
I'm not a maintainer, but I might take a look. That looks pretty cool and extremely useful.

IIRC there are specific ARIA Labels for such a use case. So it might be complicated but not imposible.

**Comment by acstll** [comment]
Thank you @tommy-codez for the suggestion and thank you @Lalaluka for chiming in.

It would be useful indeed.

I'm wondering whether this should be a variant of the Dropdown or a totally different component…

The Dropdown, as currently implemented, has a few known issues (specially with React), so we have this idea of refactoring it (without the `select` tag), sometime in the future. But the accessibility implications won't be minor: we would have to have the component fully tested again to (re)validate the AA certification.

**Comment by Lalaluka** [comment]
Not sure if it should be part of Dropdown either.
For one I know such functionality for text fields too. For example:
![Bildschirmfoto 2021-07-09 um 14 55 39](https://user-images.githubusercontent.com/26364692/125080991-c7312d00-e0c5-11eb-850a-e328e234254f.png)

So maybe a MultiSelect Component could cut it.
Or add it to both Textfield and Dropdown with something like this:

`<scale-dropdown multiple>`

Like Material for Bootstrap does it: https://mdbootstrap.com/docs/standard/extended/multiselect/
But I'm not sure if this fits the Components design.

**Comment by filipjnc** [comment]
Here's two headless (neutral) ui libraries that provide this component with a11y:
https://github.com/downshift-js/downshift
https://headlessui.com/react/combobox

**Comment by felix-ico** [comment]
this is related https://github.com/telekom/scale/issues/1058
