### ISSUE TITLE
Transitions for Accordion

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#443]
Hi there,

do you plan to add transitions to the accordion component?

Best wishes

**Comment by acstll** [comment]
hi @christopherGdynia :)

Not currently, but we do have plans for "motion" in general to the system: what would be a more broader scope, with the idea of being able to add transitions to more components in a consistent manner.

I'm not sure a 100% it would be possible to add some CSS transitions with some custom CSS (and ::part), have you tried?

**Comment by christopherGdynia** [comment]
hi @acstll, 

that sounds great

I didn't tried it, I don't know much about webcomponents or css ::part

**Comment by acstll** [comment]
No worries. I'll let you know as we make progress on the motion topic :)

**Comment by acstll** [comment]
To keep things tidy, I'm going to close this one as we currently do with all labeled `question` issues. But we can use this same issue to keep in touch.

You can find all `question`-labeled issues in here: https://github.com/telekom/scale/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion
