### ISSUE TITLE
package bundling/webpack for production (react-script)

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#452]
Hi there,

the production build with 'npm run build' delivers alot of small files(1-10k) in the build/static folder. (>200 files)
Is there a way to make bundling work (in one file) ?

Doing the scale import as described in index file of the project like this
```
import {
  applyPolyfills,
  defineCustomElements,
} from "@telekom/scale-components/loader";

import "@telekom/scale-components/dist/scale-components/scale-components.css";

applyPolyfills().then(() => {
  defineCustomElements(window);
});

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
```
 I am not sure if I can do this in a configuration file or if it has something to do with the scale/import? 

Cheers

**Comment by Lalaluka** [comment]
Hi,
this is not a Scale specific thing. But you are probably using react-scripts which automatically creates chunks.
If there is more data (like the Scale Package used) there are more chunks.
You can work around that with a Webpack config for example explained here:
facebook/create-react-app#3365

I'm not sure why you want to disable chunks. But in most applications, they are pretty useful since your bundle.js can get pretty large. And chunks enable dynamic lazy loading of the needed chunks.

Hope this helps ✌️

**Comment by acstll** [comment]
Hey @tommy-codez

this might be out of the scope of Scale, like @Lalaluka was kindly suggesting.

However, it might help you to know that Stencil —the framework we use to build the components— implements some lazy-loading mechanism by default. So there is a JavaScript file for every component, including the ~180 icons so it's roughly 220 in total. The good news is that Stencil only loads the components you're actually using.

You can read more about this in [the Stencil docs](https://stenciljs.com/docs/faq#why-does-stencil-allow-components-to-be-lazy-loaded).

If you really wanted to have all components loaded and skip the lazy-loading, there is an alternative ES bundle under `@telekom/scale-components/dist/custom-elements`, so you can do (thou I wouldn't recommend it):

```js
import { defineCustomElements } from '@telekom/scale-components/dist/custom-elements'
defineCustomElements() // loads everything! almost 1 MB
```

Alternatively, you can load individual components from that bundle, but you have to register them yourself, which could be tedious. You'll need a bundler like Webpack (I think react-scripts uses it?). And probably tree-shaking will work there, but I'm not 100% sure.

```js
import { ScaleButton, ScaleCard } from '@telekom/scale-components'

customElements.define('scale-button', ScaleButton)
customElements.define('scale-card', ScaleCard)
```

Quoting @Lalaluka… (thank you!)

> Hope this helps ✌️

**Comment by tommy-codez** [comment]
Thank you both for your support . I am fine with chunks and the lazy loading. I was just wondering about why there are so many files...
