### ISSUE TITLE
Slots for overlay-badges at icons

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#457]
Hello there,

I want to implement a notifications system in the app-header component. I plan to use the slot "menu-icon" and want to give the icon a badge that there are some messages unread or the specific number 

Like in the following example
![image](https://user-images.githubusercontent.com/84845536/126126815-7bc14f79-3c95-48fd-8237-577f40c905e7.png)

Thanks for your help.

**Comment by christopherGdynia** [comment]
![image](https://user-images.githubusercontent.com/84845536/126140405-a541b46b-b477-458d-a94f-4c5fc56bee74.png)
![image](https://user-images.githubusercontent.com/84845536/126140441-079fa7bb-3261-4c6b-884b-1dba6df47c30.png)

As support, that you might understand my ideas better, I provided two extra pictures from the previous version

**Comment by acstll** [comment]
Thank you @christopherGdynia for bringing this up.

You would need to implement the "badge" element yourself for now, as it is still under development.

Regarding how to put it in the header's  `menu-icon` slot, maybe @nowseemee can shed some light?

I will also take a look at this tomorrow.

**Comment by acstll** [comment]
Hello @FlorianLautenschlager 

thank you for your kind words! And sorry for my late reply.

We have plans for the following 4 components regarding "notifications":

– Notification Message Beta (out in `beta.22`)
– Notification Badge Beta
– Notification Banner Beta
– Notification Toast Beta

The Notification Message is out (Storybook will be updated imminently). And we started working on the Notification Badge (the little red dot) last week. The other 2 will follow!

---

Regarding your feedback, I will kindly ask you to provide some clarification if possible:

> A) a custom icon which is not included in the library OR

with this you would want to add a custom icon to the Notification Message, right the on the left of the box, is that so?

![image](https://user-images.githubusercontent.com/851105/137715982-dd168cb2-de4e-4fe0-9e74-1f0ec74f47dc.png)

> B) set a badge option to indicate that something has changed OR

is this the little red dot in the corner of other elements including a number for example? (what we call the "Notification Badge")

> C) add icons to the icon library for notifications and one for new-notifications (including the badge, without a number in the badge)

I understand this is adding the little red dot to the existing icons in the icon library, correct?

Thank you very much in advance!

**Comment by christopherGdynia** [comment]
Hello there,

I have seen your updates and I will document it here: [storybook entry](https://www.brand-design.telekom.com/scale/?path=/docs/beta-components-notification-badge--standard)

**Comment by christopherGdynia** [comment]
It's usable in Beta State

**Comment by FlorianLautenschlager** [comment]
Jep. We are already use it :-)
