### ISSUE TITLE
User Feedback Tabnavigation

### ISSUE THREAD

**Issue by Lalaluka** [telekom/scale#467]
Hi,
in the landline diagnosis of Deutsche Telekom we worked with Tagnavigation and decided to not use the Scale Implementation (for now). But we would like to give you some feedback on what the issues for us were. And we would be happy to maybe implement one or two new features around the issues.

## 1. Linewrapping
If you have a lot of entries in the Tab Navigation it wraps into a new line like this:
<img width="575" alt="Bildschirmfoto 2021-07-21 um 10 44 41" src="https://user-images.githubusercontent.com/26364692/126459567-f632528e-0a37-4565-9b05-967c97dde053.png">
While that might look nice for some applications it's not usable for us.

Also, I've gotten reports about some weird glitchy behavior when selecting and unselecting tabs in Linewrapped Tab Navigations. But I can't provide any reproducible code.

We would prefer the possibility to disable Linewrapping and use Navigation buttons instead (including a soft scroll on click).
Our own implementation looks like this now:
![tabnav](https://user-images.githubusercontent.com/26364692/126460554-8c0c7692-7eb9-4306-abc6-1d07fc3dd25e.gif)

With Navigation IconOnly Buttons on the Left and Right.

## 2. Disabling Tabs
The first issue wasn't that big of a dealbreaker. But the current Tab Navigations doesn't provide a possibility to diable Tabs. Such functionality is pretty useful for use in Diagnosis Software. 
I think such a functionality would be pretty easy to add too. You can see our approach in the gif too, with the "Reservierung der IP Adresse" being disabled.

**Comment by acstll** [comment]
Thank you @Lalaluka for taking the time to provide this valuable feedback.

I definitely see these as features that could be added to the library. We will discuss them with the rest of the team.

Regarding disabling tabs, you basically `disable` the button inside the header (and make sure the panel is also unreachable by keyboard), or is there something else to it?

Thanks again!

**Comment by Lalaluka** [comment]
Just let me know whats fine to add :)
I will gladly help to implement it.

Exactly we are adding `disabled` to it and it's unreachable through clicks and keyboard Navigation.

**Comment by Lalaluka** [comment]
Hey @acstll ,
do you have any updates on this topic? ✌️

**Comment by acstll** [comment]
Hey, not yet 😬 (we're a little low on resources at the moment ☀️)

Thanks for asking. I will get back to you next week. 🙏

**Comment by timheiler-ico** [comment]
Hi you 2!

@Lalaluka Very happy to see you're so engaged! Thank you for all the work you've contributed already!

Let me give some input from the design side on this:

For the simple part of "disabled", we even have a design, but seems not implemented the feature fully... 
![tab_navigation_disabled](https://user-images.githubusercontent.com/61275996/127490326-4c5647fb-4d48-4bee-897b-3918c877634c.png)
It's all --scl-color-background-disabled so please feel free to implement this :)

If we can get a scrolling feature to work, that's also fantastic. Maybe you can look at the pagination (currently beta) component and use / adapt those same arrows.? @Lalaluka do you have a designer on your team who could help with aligning the visual side of this before coding?

**Comment by Lalaluka** [comment]
Hi @timheiler-ico ,

1) Cool will start implementing it this evening :)

2) I can ask my Designers if they have some resources for this, but I'm not sure if they have sufficient time at the moment. I can also take a look myself. I got Sketch installed and it would be good training for me, before handing it over. Should I just attach a Sketch file with the proposed design to the issue, once my designers and I are happy with our proposal? Pagination also sounds like a good starting point to align the control elements.

**Comment by timheiler-ico** [comment]
Visual Preview must not be made by designers, just let's discuss design before implementation. That's usually faster/cheaper. 
Attaching a Sketchfile with a proposal seems good.

**Comment by Kaawo** [comment]
Greetings everyone, 
here is a draft of the design with a short description. I hope you like it. :)
![Measurements Large](https://user-images.githubusercontent.com/88150166/129223031-02ac7e9f-141b-4156-ac99-1ebed5faa0ec.png)
![Measurements Small](https://user-images.githubusercontent.com/88150166/129223055-b456c77f-249f-44d2-b081-0d0bb8aec0d2.png)
![States Chart](https://user-images.githubusercontent.com/88150166/129223057-7638e12e-83d1-4ae4-90a3-3c2e34f343dd.png)

**Comment by Kaawo** [comment]
If needed, I also have a sketch file for it. ;)

**Comment by timheiler-ico** [comment]
Hi @Kaawo thanks for the design contribution :)
I think its very straight forward. 
@Lalaluka it would be great to see this as a prototype in the next step. 
Then we can see how it feels to use the overflow this way.
Definitely going in a great direction here.

**Comment by Lalaluka** [comment]
I'll open a branch in my fork soon :)
Will open a PR Draft once it's ready

**Comment by Lalaluka** [comment]
Just a short update for Maintainance purposes.
This Issue is not forgotten. I had to shift my attention to some other issues the last few weeks.

I will continue to take a look at this improvement now.

**Comment by nowseemee** [comment]
Feel free to reopen the issue whenever you cycle back to this topic.
