### ISSUE TITLE
Option to colorize every second rows in tables

### ISSUE THREAD

**Issue by Kaawo** [telekom/scale#483]
Greetings everyone,

it would be great if you could a colorize of every second row in the component "table" (like in your beta Data Grid). We received feedback from various users on this. :)
If needed @Lalaluka can implement it.

Here is an example for a design: 
![04_53_53](https://user-images.githubusercontent.com/88150166/127514748-1cbecf34-1dd7-40ca-a0d7-59ca4ee5135b.jpg)

Thanks!

**Comment by acstll** [comment]
Hello @Kaawo 

This sounds great, please go ahead 👍 

Thank you 🙏

**Comment by acstll** [comment]
Implemented in #489 🎉 

Thanks a lot, once more.

We should be publishing a new beta release soon.
