### ISSUE TITLE
vue testing of input fields

### ISSUE THREAD

**Issue by kathavili** [telekom/scale#501]
When testing a vue component which contains also scale-text-fields, there seems to be no possibility to get access to the scale-text-field input element. After calling the Mount method, only the top level information of scale components is rendered, but the containing input element is "missing".

How do I ensure that all html elements of a scale component are rendered durng the test? How do I get access especially to the containing input element, as only the parent (scale-text-field) can be identified after adding an "id" attribute. Below you'll find an example - the html output of the wrapper:

` <scale-card class="search" label="Id Search">

      <h3>Suche nach Nummer</h3>
      <scale-divider></scale-divider>
      <form id="idSearch">
        <scale-dropdown id="optionGp" label="Option 'nur GP'">
          <option disabled="">Bitte wählen</option>
          <option>A</option>
          <option>B</option>
          <option>C</option>
        </scale-dropdown><br>
        <scale-text-field id="gpId" label="GP-Nummer" modelvalue=""></scale-text-field><br>
        <scale-text-field id="dtagId" label="DTAG-Nummer" modelvalue=""></scale-text-field><br>
        <scale-button type="submit">
          <scale-icon-action-search></scale-icon-action-search> Suche
        </scale-button>
      </form>
    </scale-card>`

**Comment by acstll** [comment]
Hi @kathavili, thank your for question.

I'm guessing the Scale components are not being upgraded (like "mounted" in web component terminology) in your tests.

There is a way to define the components without relying on the lazy-loading mechanism, which is using the `custom-elements` build. Calling the exported `defineCustomElements` function from `@telekom/scale-components/dist/custom-elements` will define the entire library.

Would it be possible to run this code before the test suite runs?

```ts
import { defineCustomElements } from '@telekom/scale-components/dist/custom-elements'
defineCustomElements()
```

Also, if you could be so kind and share your testing setup, I could help and so some testing as well.

**Comment by kathavili** [comment]
Hi @acstll , thank you for your reply.

I added the first line at the top of the test specification:
`import { mount, shallowMount } from "@vue/test-utils";
import IdSearch from "../components/IdSearch";
import { defineCustomElements } from '@telekom/scale-components/dist/custom-elements'

describe("IdSearch.vue", () => {

  beforeEach(() => {
    jest.resetAllMocks();
  });

  it("search method called - id set - empty result", async () => {
    let spyOnAlert = jest.spyOn(window, "alert").mockImplementation(() => {
      return "no data";
    });

    const wrapper = shallowMount(IdSearch);
    let str = wrapper.find("[id='gpId']");
    str.element.value = "12345678";
    wrapper.find("[id='idSearch']").trigger("submit");
    await wrapper.vm.$nextTick();
    expect(spyOnAlert).toHaveReturnedWith("no data");
  });

});`

... but got the following result:

`SyntaxError: Cannot use import statement outside a module

      2 | import { mount, shallowMount } from "@vue/test-utils";
      3 | import IdSearch from "../components/IdSearch";
    > 4 | import { defineCustomElements } from '@telekom/scale-components/dist/custom-elements';
        | ^`

Below you'll find the used jest.config:

`module.exports = {
  preset: "@vue/cli-plugin-unit-jest",
  moduleFileExtensions: ["js", "jsx", "json", "vue"],
  transform: {
    "^.+\\.vue$": "vue-jest",
    ".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$":
      "jest-transform-stub",
    "^.+\\.jsx?$": "babel-jest",
    "^.+\\.js?$": "babel-jest",
  },
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  snapshotSerializers: ["jest-serializer-vue"],
  testMatch: ["**/__tests__/**/*.spec.(js|jsx|ts|tsx)"],
  testURL: "http://localhost/",
  collectCoverage: true,
  collectCoverageFrom: [
    "src/**/*.{vue,}",
    "!**/*storybook/**/*.{vue,}",
    "src/{scripts,}/*.{js,}",
  ],
  coverageReporters: ["json", "lcov", "text", "clover", "cobertura"],
};
`

**Comment by acstll** [comment]
Thank you @kathavili 

I wonder why, since you're code is already ESM and `@telekom/scale-components/dist/custom-elements` also is. But looks like a transpiling problem.

According to your Jest config all .js files are going through `babel-jest`, maybe `@telekom/scale-components/dist/custom-elements` can be ignored?

Maybe this could be of help: https://stackoverflow.com/a/61785012?

I will try and reproduce it if you cannot make it work adjusting the config.

**Comment by kathavili** [comment]
Hi @acstll ,

I added the lines as suggested in your comment - not sure if I did it correctly:

`module.exports = {
  preset: "@vue/cli-plugin-unit-jest",
  moduleFileExtensions: ["js", "jsx", "json", "vue"],
  transform: {
    "^.+\\.vue$": "vue-jest",
    ".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$":
      "jest-transform-stub",
    "^.+\\.jsx?$": "babel-jest",
    "^.+\\.js?$": "babel-jest",
    "node_modules/@telekom/scale-components/dist/custom-elements/.+\\.(j|t)sx?$":
      "babel-jest",
  },
  transformIgnorePatterns: [
    "node_modules/(?!@telekom/scale-components/dist/custom-elements/.*)",
  ],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  snapshotSerializers: ["jest-serializer-vue"],
  testMatch: ["**/__tests__/**/*.spec.(js|jsx|ts|tsx)"],
  testURL: "http://localhost/",
  collectCoverage: true,
  collectCoverageFrom: [
    "src/**/*.{vue,}",
    "!**/*storybook/**/*.{vue,}",
    "src/{scripts,}/*.{js,}",
  ],
  coverageReporters: ["json", "lcov", "text", "clover", "cobertura"],
};
`

After restarting the test I got a different error message:

`  ● Test suite failed to run

    C:\Daten\CDI\workspace\frontend\cdi-central-search\node_modules\@stencil\core\internal\client\index.js:16
    import { BUILD, NAMESPACE } from '@stencil/core/internal/app-data';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@telekom/scale-components/dist/custom-elements/index.js:1:1)`

Then I tried to solve this by adding also the mentioned library @stencil/core/internal/app-data to the jest config:

`module.exports = {
  preset: "@vue/cli-plugin-unit-jest",
  moduleFileExtensions: ["js", "jsx", "json", "vue"],
  transform: {
    "^.+\\.vue$": "vue-jest",
    ".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$":
      "jest-transform-stub",
    "^.+\\.jsx?$": "babel-jest",
    "^.+\\.js?$": "babel-jest",
    "node_modules/@telekom/scale-components/dist/custom-elements/.+\\.(j|t)sx?$":
      "babel-jest",
    "node_modules/@stencil/core/internal/app-data/.+\\.(j|t)sx?$": "babel-jest",
    "node_modules/@stencil/core/internal/client/.+\\.(j|t)sx?$": "babel-jest",
  },
  transformIgnorePatterns: [
    "node_modules/(?!@telekom/scale-components/dist/custom-elements/.*)",
    "node_modules/(?!@stencil/core/internal/app-data/.*)",
    "node_modules/(?!@stencil/core/internal/client/.*)",
  ],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  snapshotSerializers: ["jest-serializer-vue"],
  testMatch: ["**/__tests__/**/*.spec.(js|jsx|ts|tsx)"],
  testURL: "http://localhost/",
  collectCoverage: true,
  collectCoverageFrom: [
    "src/**/*.{vue,}",
    "!**/*storybook/**/*.{vue,}",
    "src/{scripts,}/*.{js,}",
  ],
  coverageReporters: ["json", "lcov", "text", "clover", "cobertura"],
};
` 

But again, this didn't work:

`  ● Test suite failed to run

    C:\Daten\CDI\workspace\frontend\cdi-central-search\node_modules\@telekom\scale-components\dist\custom-elements\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { h, createEvent, Host, attachShadow, proxyCustomElement } from '@stencil/core/internal/client';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import Vuex from "vuex";
      3 | import IdSearch from "../components/IdSearch";
    > 4 | import { defineCustomElements } from '@telekom/scale-components/dist/custom-elements';
        | ^`

Do you have any additional idea?

**Comment by acstll** [comment]
> Do you have any additional idea?

not now, but I can try and reproduce the error and see what we can find out, ok?

What version of Vue are you using, and what "build" tool (like `vue-cli`)?

Thanks for trying out :)

**Comment by acstll** [comment]
Hello @kathavili 

I was able to get it working.

The key to fixing the compile/esm errors were:

- installing the `babel-core` package
- adding an empty `transformIgnorePatterns` option to the Jest config

I also use the `beforeAll` hook to call `defineCustomElements()`.

Here's the setup:

## Installed packages

- `@vue/test-utils@next` (^2.0.0-rc.11)
- `vue-jest@next` (^5.0.0-alpha.10)
- `babel-core@bridge` (7.0.0-bridge.0)

The [`vue-jest` docs](https://github.com/vuejs/vue-jest) recommend installing `babel-core` with the `@bridge` tag, but v6 (^6.26.3) also works for me.

## `jest.config.js`

```js
module.exports = {
  moduleFileExtensions: [
    "js",
    "vue"
  ],
  modulePaths: [
    "<rootDir>/src",
    "<rootDir>/node_modules"
  ],
  transform: {
    "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
    ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
  },
  // ! This is needed, with an empty array ¯\_(ツ)_/¯ 
  transformIgnorePatterns: [],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1"
  },
  // ! I added this according to the `vue-jest` docs to remove the `[Vue warn]: Failed to resolve component` warning
  // but it doesn't work
  globals: {
    "vue-jest": {
      templateCompiler: {
        compilerOptions: {
          isCustomElement: (tag) => tag.startsWith('scale-')
        }
      }
    }
  }
}
```

## Test file example

Using almost the same code from your "search id" component snippet above.

```js
import { shallowMount } from '@vue/test-utils'
import { defineCustomElements } from '@telekom/scale-components/dist/custom-elements'
import Search from '@/components/Search'

beforeAll(() => {
  defineCustomElements()
})

describe('Search', () => {
  it('example', async () => {
    const wrapper = shallowMount(Search)
    const dtagInput = wrapper.find('#dtagId')
    const button = wrapper.find('scale-button')

    await button.element.click()
    expect(dtagInput.element.value).toBe('testing')
    expect(wrapper.emitted()).toHaveProperty('click')
  })
})
```

--- 

## "Failed to resolve component" warnings

I haven't been able to remove the warnings in the console regarding the custom elements (remember `compilerOptions = { isCustomElement: (tag) => tag.startsWith('scale-') }`?).

```
 [Vue warn]: Failed to resolve component: scale-button
```

I'm guessing that the `vue-jest` docs are for version 4, but we need v5 (in alpha) for Vue 3, and from looking at the code seems like those options might have changed.

https://github.com/vuejs/vue-jest

---

If you cannot make it work, I'll be glad to jump in a call.
