### ISSUE TITLE
Hover ScaleNavSegment (bootstrap override)

### ISSUE THREAD

**Issue by ChristianAtWork** [telekom/scale#509]
![image](https://user-images.githubusercontent.com/43496354/128464339-60a2d8d2-6a6e-4fb9-8a1b-4af755ab738e.png)

Bootstrap has a hover effect on 
```
a:hover {
    color: #0056b3;
    text-decoration: underline;
}
```
ScaleNavSegment doesn't have a style on hover

My Suggestion would be something like this:
[scale-nav-segment](https://github.com/telekom/scale/blob/main/packages/components/src/components/telekom/nav-segment/nav-segment.css
)
```
.segment-navigation__item-link:hover,
.segment-navigation__item-link.active {
  color: var(--color);
  border-bottom: var(--border-bottom);
  transition: var(--transition);
}
```

**Comment by acstll** [comment]
Thanks @ChristianAtWork for opening this.

If I understand correctly, you would like to add `color` also to the properties affected by hover, is this so?

**Comment by acstll** [comment]
@nowseemee this should be possible to do, right?

**Comment by nowseemee** [comment]
Hi @ChristianAtWork - is this the above ⬆ linked pull request covering your needs?
