### ISSUE TITLE
Improve Documentation for React Events

### ISSUE THREAD

**Issue by SebastianGode** [telekom/scale#513]
Currently in the documentation there's only a small section which describes the handling of events in React. An example for that would be appreciated as the documentation of e.g. a textfield does not touch the interaction with Frameworks, just through plain-JS.

**Comment by acstll** [comment]
Thanks for opening this @SebastianGode 

We have a work-in-progress version of the React docs, here: https://github.com/telekom/scale/blob/d16e6d80b0fcdb7ac1ee79811995647774ec4e95/packages/storybook-vue/stories/2_for_developers/04.ScaleAndReact_en.md

Do you think that would be enough?

**Comment by SebastianGode** [comment]
@acstll 
That's wonderful :)
Looking forward to seeing it in the official docs!
