### ISSUE TITLE
Sketch: Insert Sidebar Example Component causes crash

### ISSUE THREAD

**Issue by magenta-powermax90** [telekom/scale#517]
MacOS: 11.5.1 (20G80)
Sketch: Version 75 (129697)
Scale Library: build 556
Computer new start: yes
Reproducable: yes

After clicking on the component "Sidebar Navigation" > "01 Example" Sketch crashes completely. 
![insert_component_crash](https://user-images.githubusercontent.com/88722952/128893895-ed82ffa9-b523-42f5-ac26-bd9b933f5eb1.png)

**Comment by timheiler-ico** [comment]
We'll look into it :)

**Comment by Lalaluka** [comment]
<img width="364" alt="Bildschirmfoto 2021-08-10 um 18 27 25" src="https://user-images.githubusercontent.com/26364692/128896873-e85ed2da-fe49-47f5-b6de-bb51e6546213.png">

Seems to be two files generating Sidebar Navigations.
`packages/components-sketch/views/sidebar-nav.hbs`
and
`packages/components-sketch/views/sidebar-nav-components.hbs`

Here is the Applications error Stack trace.
[error.txt](https://github.com/telekom/scale/files/6963043/error.txt)

It probably is `packages/components-sketch/views/sidebar-nav.hbs` its generating the component selected.

I can take a closer look tomorrow @timheiler-ico if it's not extremely urgent for the core team

**Comment by oddcelot** [comment]
@magenta-powermax90 seems to be fixed in version `565` (will be released soon)
but this feels weird, so i'll take another look 😄

**Comment by Lalaluka** [comment]
+1 @oddcelot 

I can't reproduce it on local builds either.

**Comment by timheiler-ico** [comment]
@magenta-powermax90 please check the latest update to "build 569". it was just released. 
please let us know if there are still problems.?

**Comment by magenta-powermax90** [comment]
Hey @timheiler-ico @acstll seems fixed for me with build 569! Thank you very much
