### ISSUE TITLE
Scale logo

### ISSUE THREAD

**Issue by Kaawo** [telekom/scale#527]
Greetings everyone, 
it's not a real issue, more a suggestion: Could you design a logo for Scale? Or maybe you already have one?

Background: We carry this topic (Scale) in our hub/canvas/tribe. It would be nice to have something like that for presentations.  :) Thanks!

**Comment by acstll** [comment]
Hello @Kaawo 

this is a fantastic idea, we don't have one but we could indeed design it. In fact the subject came up as well within the team not long ago. I've added it to our backlog.

Thank you!

**Comment by Kaawo** [comment]
Hello @acstll ,

that would be nice. If i can support you, let me know. ;)

**Comment by timheiler-ico** [comment]
@Kaawo I'm inviting you to a private repo with presentation material. Maybe there's something in it.

**Comment by Kaawo** [comment]
Good, now I also have time to take care of the task. :) Have you ever thought about the topic? If so, I would be interested in your results ;)
The thoughts that I have made so far are all moving around the topic / word "design system". From my point of view this includes creativity as well as standardization. So a combination of these points would be ideal. What do you think?

**Comment by Kaawo** [comment]
Greetings everyone,

here are some ideas/drafts for a logo.

Regards
Kay

![image](https://user-images.githubusercontent.com/88150166/132844698-c0bed8a3-ffcc-41bd-8a15-4e48ee52243f.png)

**Comment by Kaawo** [comment]
Additional
![image](https://user-images.githubusercontent.com/88150166/132850704-97b99607-7cde-4619-820b-65dffcd18952.png)

**Comment by timheiler-ico** [comment]
Hi Kay! 

Thank you for your contribution!

I will talk to the team about your proposals.

**Comment by timheiler-ico** [comment]
Hi Kay!

Sadly, the team has already checked with Brand and we are generally not allowed to design/use a Logo other that the "T". The name "Scale", written in TeleNeo Font must suffice.

Thanks for your work and creative input anyways. We were really happy you were inspired to create these proposals!
