### ISSUE TITLE
ScaleDropdown (React) Cannot remove dynamically an item from select (DOM Exception removeChild())

### ISSUE THREAD

**Issue by js31415** [telekom/scale#535]
I want to remove an item from select dynamically but I've got an **Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node** :(

Here's some code 

`export default function App() {
  const [list, setList] = useState(data);
  const [name, setName] = useState(data[0].name);

  const handleDelete = () => setList(list.filter((item) => item.name !== name));

  const handleSelectChange = (e: any) => setName(e.detail.value);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <ScaleButton onClick={() => handleDelete()}>Click</ScaleButton>
      <ScaleDropdown
        onScaleChange={(e) => handleSelectChange(e)}
        label="Dropdown list"
        value={name}
        controlled
      >
        {list.map((item) => (
          <option key={item.id} value={item.name}>
            {item.name}
          </option>
        ))}
      </ScaleDropdown>
    </div>
  );
}
` 

code sandbox for repro 
[https://codesandbox.io/s/scale-tests-tk1eq?file=/src/App.tsx:329-1073](url)

I tried this with a simple html select and it worked very well. May I missed something? 
So much thank you for your help guys!

**Comment by acstll** [comment]
Thank you @js31415 for opening this!

This is known bug (#508). It has to do with Stencil's virtual DOM implementation and it's very specific to React. Thus very hard to fix.

I had recently created a React-only version of the ScaleDropdown component —for another team facing the same problem. We're still figuring out how to (and when, if at all) to publish it, so I'm sharing it with you here in a gist so you could include it in your project?:

https://gist.github.com/acstll/07f3146c61e6f0c72471cf4d7f627fee

There is also another workaround, which is to wrap the ScaleDropdown to make sure it re-renders completely on every change. Something like this below, but you probably know better :)

```jsx
const Wrapper = ({ children }) => <>{children}</>
const dropdown = <ScaleDropdown>{/* ... */}</ScaleDropdown>

return (
  <>
    <Wrapper>{dropdown}</Wrapper>
  </>
)
```

Let me know if this helps.

**Comment by js31415** [comment]
Thank you so much 😊 @acstll 
The gist is more better for us!  So big thanks and I appreciate your super fast response :)

**Comment by acstll** [comment]
You're very welcome!

(Any feedback on the code will be welcomed.)
