### ISSUE TITLE
Datepicker-Flyout placement

### ISSUE THREAD

**Issue by asexte** [telekom/scale#539]
On using the scale-datepicker in a modal window we noticed that it creates a scrollbar
to reserve the space for the flyout below the text-input.
This make it look ugly.
We solved it by overwriting the css:
.duet-date__dialog-content { 
  position: absolute;
  left: 50%;
  transform: translate(-50%, -80%);
}

A configuration option or the 'styles' parameter would be better here.

![StornoDateBad](https://user-images.githubusercontent.com/89449962/130587192-8580ba30-f0b0-443a-a9fd-47353a40d8dc.png)

![StornoDateGood](https://user-images.githubusercontent.com/89449962/130586677-99a070c8-4e96-417d-a9be-25f9aa65e0ee.png)

**Comment by asexte** [comment]
Hi Arturo,

Should be ok for this case.
Having the ‘styles’ parameter that’s available on other elements
might be more consistent.
There are some other cases where the flyout opens at least partially outside the viewing area,
but I don’t see how a general solution for this could look like.

Thanks
--Axel--

**Comment by nowseemee** [comment]
Hi @asexte - I've added the missing styles prop to the date-picker and published version `3.0.0-beta.19`.
