### ISSUE TITLE
scaleClose event tag/modal

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#541]
Hi,
when I trigger the scaleClose event of a tag in a modal, the scaleClose event is triggered by the modal at the same time.

![image](https://user-images.githubusercontent.com/73475493/130626712-89771730-4db2-4243-b6bf-ced7978e14cf.png)
---------------------------------------
![image](https://user-images.githubusercontent.com/73475493/130626792-68ccf69e-0902-4788-9cc8-4a8002308fe6.png)
---------------------------------------
![image](https://user-images.githubusercontent.com/73475493/130626988-54d364b5-7660-45ec-a1e8-1052322d1e8e.png)

**Comment by acstll** [comment]
Hey @tomkroschwald, thanks for opening this.

I would say the event is the same (the one originated in `scale-tag`), that bubbles up. The same would happen if you listened for `click`.

To confirm that the event is the same, I would recommend you do:

```js
methods: {
  test(event) {
    console.log(event.target) // this should be <scale-tag>
  }
}
// I think you need to pass `$event` there -> @scaleClose="test($event)"
```

Then, to avoid the modal from emitting the event too, I would try this:

```js
methods: {
  test2(event) {
    event.stopPropagation(); // we make sure the event does not reach scale-modal
  }
}
```

Could you be so kind to try this? The [`event.stopPropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) should be the way to fix this.

Just so you know, we had a bug in the past where the modal would close if you had a `scale-tag` being closed inside of it. But now the `scaleClose` event is only emitted by the modal after it has closed.

Please let me know if this helps.

**Comment by tomkroschwald** [comment]
Hey @acstll,
thank you for your help. It works! :)
