### ISSUE TITLE
Slow/Weird Transition in Brand Header

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#572]
Hi there,

in the Brand Header Component during resize of the window there is a point where the menu transitions from normal to mobile.

This transition is quite slow and some flickering occours. If you size the window in the exact point there is some weird menu showing up (see screen 2).

this can be tested with

 a simple implementation like this

```
	  <ScaleAppShell>
	  <ScaleAppHeader slot="header" id="header">
		<div slot="menu-main">
		<ScaleNavMain name="Custom Item #1"></ScaleNavMain>
			<ScaleNavMain name="Custom Item #2" id="nav-main-with-mega-menu">
			</ScaleNavMain>
			<ScaleNavMain name="Custom Item #3"></ScaleNavMain>
			<ScaleNavMain name="Custom Item #4"></ScaleNavMain>
		</div>
     </ScaleAppHeader>
	  <p style={{ height: '500vh' }}>some large content</p>
	</ScaleAppShell>
```
![screen1](https://user-images.githubusercontent.com/66920189/132470681-5bcb92c9-4ee9-4621-97a1-3302920361f3.png)
![screen2](https://user-images.githubusercontent.com/66920189/132470683-086cac20-79ef-453c-b12e-2e294a0b621c.png)
![screen3](https://user-images.githubusercontent.com/66920189/132470687-9e84cbd3-400e-4a5d-8412-0ae4264c03bf.png)

**Comment by nowseemee** [comment]
Hi @tommy-codez, thanks for sharing your finding. What browser did you use to have this effect?

**Comment by tommy-codez** [comment]
Hi @nowseemee ,
I tested it on Chrome and Edge. If you slowly resize the window to the transistion point - there is this effect.

A developer found this in a multiscreen environment - but it also occurs when you resize the window with a single screen/window.

**Comment by nowseemee** [comment]
Hello again and sorry for coming back to you this late. Unfortunately I was not able to reproduce the issue. This is all I see:

https://user-images.githubusercontent.com/4532334/142996790-07066de5-a2b5-45c8-8204-068121a223f8.mov

Here is the html I'm using:
```
 <scale-app-shell id="app">
      <div class="block">
        <button id="change-button" style="margin: 1em">change sector</button>
      </div>
      <div class="block">Two</div>
      <scale-app-header slot="header" id="header">
        <div slot="logo">
          <app-logo claim href="#custom" logo-title="Custom"></app-logo>
        </div>
        <div slot="menu-main">
          <scale-nav-main is-active name="Menu item #1"></scale-nav-main>
          <scale-nav-main name="Menu item #2" id="nav-main-with-mega-menu">
            <app-mega-menu>
              <div slot="custom-body"><h1>hello</h1></div>
            </app-mega-menu></scale-nav-main>
          <scale-nav-main name="Menu item #3"></scale-nav-main>
          <scale-nav-main name="Menu item #4"></scale-nav-main>
        </div>
        ...
  </scale-app-shell>
```

Do you think you could share the exact way to reproduce this issue, please? That would help a lot because currently I'm a little stuck with this issue. Many thanks!

**Comment by tommy-codez** [comment]
Hi @nowseemee ,

sure I use react, btw. but I can easily reproduce it with this code:

```
 <ScaleAppShell id="app">
      <div className="block">
        <button id="change-button">change sector</button>
      </div>
      <div className="block">Two</div>
      <ScaleAppHeader slot="header" id="header">
        <div slot="logo">
          <AppLogo claim href="#custom" logo-title="Custom"></AppLogo>
        </div>
        <div slot="menu-main">
          <ScaleNavMain is-active name="Menu item #1"></ScaleNavMain>
          <ScaleNavMain name="Menu item #2" id="nav-main-with-mega-menu">
            <AppMegaMenu>
              <div slot="custom-body">
                <h1>hello</h1>
              </div>
            </AppMegaMenu>
          </ScaleNavMain>
          <ScaleNavMain name="Menu item #3"></ScaleNavMain>
          <ScaleNavMain name="Menu item #4"></ScaleNavMain>
        </div>
      </ScaleAppHeader>
    </ScaleAppShell>
```

You start the local create react app and open the browser-url and then resize the window exactly to the transistion point nad you get this:
![grafik](https://user-images.githubusercontent.com/66920189/143234131-f62d3f97-be7b-4cdf-bc87-2b297d405d00.png)

**Comment by felix-ico** [comment]
Hi @tommy-codez, I'm going through some older issues and noticed this one. I tested your code in a fresh react app with the latest scale-components version (beta3.0.0-beta.103) and can't reproduce the issue you described. I tested on Chrome and Firefox on both macOS and Windows as well as Edge on Windows.

**Comment by tommy-codez** [comment]
Yeah seems to be fixed - tested it in beta 54 - thanks
