### ISSUE TITLE
Circuit Breaker & Open Icon 

### ISSUE THREAD

**Issue by hari319** [telekom/scale#574]
Hello Scale Team,

we are using scale in our project and we have a requirement of a Icons. We need two type of icons the sample of [Circuit Break & Open](https://qph.fs.quoracdn.net/main-qimg-3121f4cdc75f37cd77c019f50a50187f) icon can be found in link. would it be possible from your side to provide us such icon. 

Greetings

**Comment by Kaawo** [comment]
Greetings everyone, 

when I get the requirements for icons from the Scale Team, I can adjust this design. :) ... and upload it afterwards.

Best regards
Kay

![image](https://user-images.githubusercontent.com/88150166/132849934-5389ba89-7750-499b-b7ae-19586317bb5f.png)

**Comment by timheiler-ico** [comment]
Hi @hari319 !

Thanks for using Scale!

For the Design of icons, there are resources available on the Brand&Design Platform
https://www.brand-design.telekom.com/en/articles/i/icons-for-user-interfaces/

The guideline there also includes information on form language and design principles for custom icons.

I will be forwarding your request to the Brand & Design team.

**Comment by oddcelot** [comment]
If you ever need to use a custom icon, you can always use the icon component
```html
<scale-icon path="M12...75h8.7z"></scale-icon>
```
(But maybe check the brand guide first 😉 )

**Comment by timheiler-ico** [comment]
Hello @hari319 !

After checking back with the team, the official process is as follows:

1st: Please design your icon proposals according to the guidelines:
   https://www.brand-design.telekom.com/en/articles/i/icons-for-user-interfaces/
2nd: Get in touch with brand dialogue to align the Telekom icon style & ensure consistency
   https://brand-dialog.telekom.com/
   
Once the icons are agreed with brand, using the path attribute as provided by @oddcelot is your quickest way to get working. 
Together with brand, we will then also consider making the new icons part of the official icon library.
