### ISSUE TITLE
Design rules for html drag and drop elements

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#583]
Hello there,

I am currently working on html element drag and drop and I am wondering if you have some design rules for it, like a dragged element has a opacity of 0.5 or something like that.

I hope you are getting my point :D

Thanks for your help guys!

**Comment by acstll** [comment]
Hey @christopherGdynia :) Thanks for asking.

we don't such design specs at the moment.

I would suggest you use the currently available tokens where possible —that should hopefully help a lot— and come up with the missing pieces.

We'll be glad to discuss any open questions in your work.

**Comment by tshimber** [comment]
I close the issue as seem to be answered. FYI @amir-ba
