### ISSUE TITLE
Date-Picker in Modal (Inconvenience/Scrollbar)

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#592]
Hi there,
if I have a Date Picker field in a modal dialog, it takes up a lot of space. There is a scrollbar and a lot of whitespace (see screenshot)

![date_picker_in_modal](https://user-images.githubusercontent.com/66920189/134647394-b9587366-56e3-4975-91c6-e525fa54d20f.png)

Would be better if the date-picker would not influence the parent dialog and show up as an overlay.

**Comment by acstll** [comment]
Hey @tommy-codez thanks for the feedback.

We had somebody else report the same issue before. They were able to solve it by using some custom CSS: https://github.com/telekom/scale/issues/539

There should be room for improving the position of the Date Picker (with a similar technique as in the Flyout Menu), but that's currently out of reach.

I would also suggest evaluating the possibility of not using a Modal for this use case, but rather a full page :)

**Comment by darnel-T** [comment]
Hey @acstll!
I have the same issue but my date time picker is inside a scale card. For some reason I cannot make it appear above the card, the datepicker is not visible correctly.
When I try to set the Z-index for the datepicker, nothing happens.
How can I solve that?
