### ISSUE TITLE
Scale-Link has no size

### ISSUE THREAD

**Issue by ChristianAtWork** [telekom/scale#608]
In the old Scale Version beta 15, the link had a size:

![image](https://user-images.githubusercontent.com/43496354/136016639-8b1dc598-4a87-48dd-9e68-98ff9e3f2dfb.png)

in the new Version beta 21, the link has no size. That causes Problems for our Selenide/Selenium Tests, they can't click it anymore:

![image](https://user-images.githubusercontent.com/43496354/136017690-5228a5f3-c1b0-49f8-ab3b-be0fe1d564be.png)

**Comment by acstll** [comment]
I fix for this has been released in the latest beta 22. Sorry for the trouble 🙏
