### ISSUE TITLE
Tooltip widget (new UI component)

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#610]
Hello there,

I'd like to make a feature request for extending tooltips, so that they are activated also on focus (not only on hover)

Although this design pattern is work in progress https://www.w3.org/TR/wai-aria-practices/#tooltip there are some working examples available on the w3 also: https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html

The behavior of the tooltip is well described here: https://www.w3.org/TR/wai-aria-practices/#tooltip

**Comment by mato-a** [comment]
Beta component is available already so I am closing this one.
I have created new issue about found bugs: https://github.com/telekom/scale/issues/718

**Comment by acstll** [comment]
Amazing, @mato-a thanks a lot for the feedback.
