### ISSUE TITLE
Button group (new UI component)

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#611]
Hello there,

I'd like to ask for new UI component button group that should work similarly to bootstrap https://getbootstrap.com/docs/5.1/components/button-group/

Specifically I am interested in radio button group features: https://getbootstrap.com/docs/5.1/components/button-group/#checkbox-and-radio-button-groups

Currently we use radio button groups in our app, using scale buttons and some logic to mark selected button with different background color. I suppose it is quite common use case.

**Comment by mato-a** [comment]
Toogle group component is in beta. Thanks for this 🥳 

We have integrated it into our project and so far we didn't find any issues with the new component, so I am closing this issue.

**Comment by acstll** [comment]
Amazing, thanks for the feedback!

**Comment by mato-a** [comment]
Hi there, 

We have found some accessibility issues in the context how we are trying to use the new toggle button group component.
Basically we are using the button group to select a certain tool from the toolbox. 
So what we need is actually radio button group that looks like the new toggle button group.

Here are some examples:
https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html
https://getbootstrap.com/docs/5.1/components/button-group/#checkbox-and-radio-button-groups

Besides accessibility issues - we are using toggle button group where radio button group is expected (`role=radiogroup`), there is also a functional issue that after selecting certain item more times it gets selected/unselected, but we would need a behavior of the radio button group in which clicking the same button will always keep it in selected status.

Would you consider adding such feature?

**Comment by acstll** [comment]
Hey @mato-a, definitely can consider it. This is highly appreciated feedback.

> after selecting certain item more times it gets selected/unselected, but we would need a behavior of the radio button group in which clicking the same button will always keep it in selected status

for this it'd make probably more sense to use input[type=radio] directly… we'll think about it and try and have this refactor (however it ends up being) ready before the next accessibility sprint.

**Comment by felix-ico** [comment]
we are currently working on a segmented-button that will support this functionality

**Comment by tshimber** [comment]
hi @mato-a !
here's segmented btn component https://telekom.github.io/scale/?path=/docs/beta-components-segmented-button--standard
please tell (considering it) if the issue is still relevant
FYI @amir-ba

**Comment by mato-a** [comment]
Hi, issue can be closed
