### ISSUE TITLE
Suffix for Text Field

### ISSUE THREAD

**Issue by jamie-magenta** [telekom/scale#612]
Hello,
we are currently integrating Scale into a new project. It would be great if the Text Field component supported something like a suffix, such as meters or days. I have created a quick demonstration of how something like this might look:
![example](https://user-images.githubusercontent.com/84012740/136346552-90dbd2e2-3f04-43bd-afa5-c93274cddd25.png)

Would it be possible to implement something like this?

**Comment by acstll** [comment]
@jamie-magenta just wanted to let you know this is currently a work in progress. We hope to be able to release something soon.

**Comment by jamie-magenta** [comment]
Hello @acstll, do you have any updates on this issue? 😃

**Comment by acstll** [comment]
Hi @jamie-magenta, thanks for the reminder! The design is ready, we just need to code it. I can't tell you any dates but I'm expecting this to be out soon.
