### ISSUE TITLE
use flyout menu with react

### ISSUE THREAD

**Issue by alzalabany** [telekom/scale#621]
Hello;

is there a way to use flyout menu like in this example using react ?

https://www.brand-design.telekom.com/scale/?path=/docs/beta-components-flyout-menu--brand-header-user-menu

**Comment by acstll** [comment]
Hey Momen, nice to hear from you.

It should be possible, yes. Did you run into any particular problems?

A new accessible version of the Flyout Menu is about to be released, so I would like to provide an example with this latest version. I will reply later today.
