### ISSUE TITLE
Add more colors to tags

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#622]
Hello,

currently we have limited possibility with TAGs coloring, it is ether almost black, tile or gray. Can you please add more colors support for TAGs. Background, we try News Page sketch and black Tags are not fitting to the design at all.
![grafik](https://user-images.githubusercontent.com/6813635/137325046-e8c16772-0948-4e23-8a48-0bb8acda9d66.png)
![grafik](https://user-images.githubusercontent.com/6813635/137325099-b53dbb2c-97ee-4811-b6fe-d7b7653857ca.png)

Would be nice to have this color as switch (e.g. `variant`).

**Comment by GAS85** [comment]
Thats good, but would be nice to have them predefined according to corporate color system and WCAG contrast rules.

**Comment by GAS85** [comment]
I'm far away backend dude, but will ask if somebody from colleagues would like to contribute.

**Comment by acstll** [comment]
I just added this to our backlog, we'll try and get to it soon. I'll close the issue, but feel free to reopen if you have any news. And thanks again for the suggestion!
