### ISSUE TITLE
Logo component: iconOnly

### ISSUE THREAD

**Issue by filipjnc** [telekom/scale#628]
It would be great to have a new property (e.g. iconOnly) in the Logo component that allows showing only the T logo without the slogan text. The slogan text will be then attached automatically as accessibility title.

**Comment by acstll** [comment]
Thank you @filipjnc! This should be doable. We'll get back to you soon.

**Comment by acstll** [comment]
Sorry for the delay @filipjnc We've added this to our backlog (so we won't forget).

**Comment by nowseemee** [comment]
When setting the language to `en` the logo will render without slogan text / clam.
