### ISSUE TITLE
Textfield Reset Option/Property

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#633]
Hi there,

an option/property to reset a text field would be nice to have ...

like this
![image](https://user-images.githubusercontent.com/66920189/138073502-ab69e09e-29f5-4c06-8df9-debd743183fb.png)

**Comment by rriedeltsi** [comment]
@nowseemee this feature is something we're aked about regulary, so it would be nice to have it. In addition to this, suffix / prefix icons like here

![input-with-icon2](https://user-images.githubusercontent.com/96128057/149123673-86c887c5-a9e1-4bca-af20-3cfc7ebdb2a7.png)
![input-with-icon](https://user-images.githubusercontent.com/96128057/149123678-76cb3250-beb1-4455-b197-94bb3a3f9cbf.png)

would be a nice addon :D

**Comment by GAS85** [comment]
Hey, would love to have this 😄

**Comment by felix-ico** [comment]
Hi we're looking into this. We see two features here:

-leading icon in the text-field
-suffix/reset button in text-field: there may be more features needed here (password show/hide, voice input, etc)

**Comment by felix-ico** [comment]
https://mui.com/material-ui/react-text-field/

**Comment by felix-ico** [comment]
suffix is also requested here https://github.com/telekom/scale/issues/612
