### ISSUE TITLE
Scale and React Support

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#635]
Hi there,
found in the docu 

```
The automatically generated proxy packages might be deprecated in v4:

@telekom/scale-components-react
@telekom/scale-components-react-neutral
```

what does it mean exactly?
is there a timeline for the major versions?

Thanks

**Comment by acstll** [comment]
Hey @tommy-codez, thanks for asking.

There is no timeline yet for the major versions.

v4 will be released once we're ready to leave the current "open beta" phase. But there probably shouldn't be any breaking changes. The major 4 should mainly and hopefully indicate the phase change.

Deprecation of the React proxy packages in v4 means exactly that they might be _marked_ as deprecated in v4 —you will be able to continue using it during v4—, and then removed (aka not released anymore) in v5.

So (1) we still need to make the final decision and (2) we'll get plenty of time to plan and act accordingly.

In case of deprecation we would encourage and guide teams to use something like [reactify-wc](https://github.com/BBKolton/reactify-wc), or, even better, hope that some [miracle](https://github.com/facebook/react/issues/11347) happens and a new version of React fully supports custom elements so we don't have the limitations mentioned in the docs. In the end we would like developers to better understand web components so the experience overall is better.

Any feedback on this from your side or any other teams using React will be highly appreciated.

Does this answer your question?
