### ISSUE TITLE
Include UMD Build to make importing scale through plain HTML possible

### ISSUE THREAD

**Issue by SebastianGode** [telekom/scale#639]
See https://unpkg.com/

[React](https://reactjs.org/docs/add-react-to-a-website.html) and other popular frameworks also offer the option to include them in plain html without the need of having npm/node-js installed on the machine. This works via the unpkg CDN which serves as an CDN for NPM modules. It would be great if you could participate there too as it is very simple to do it and does not require any hosting or delivery outside npm.

**Comment by iorlovsky** [comment]
+1, our product also needs this feature available. Is there any progress, please?

**Comment by acstll** [comment]
I replied there https://github.com/telekom/scale/issues/642#issuecomment-1580396175 🙏

**Comment by tischrei** [comment]
+1 from my side

**Comment by ayeshaa-m** [comment]
@SebastianGode The umd build creation is done and it will be available in upcoming release. You could probably access it through 
` <script
    type="module"
    src="node_modules/@telekom/scale-components-react/dist/index.umd.js"
  >`

Thanks.
