### ISSUE TITLE
Styling advice for resizable column and accessability

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#640]
Hello,

I am currently developing a table view with resizable column, do you have any advice on styling it.
My first "style"

![image](https://user-images.githubusercontent.com/84845536/138462914-32347534-7d29-4d40-a68e-fdda5ad53865.png)

[SandboxToTest](https://codesandbox.io/s/happy-mcnulty-zmv8k?file=/src/index.css)
You find the styles at the bottom
Css class: `.resizer`
Active class `.resizer.isResizing`

Do I need to make it accessable?

**Comment by timheiler-ico** [comment]
Hi @christopherGdynia and sorry for the late reply.

I suggest you take a look at the data grid component here https://www.brand-design.telekom.com/scale/?path=/story/components-data-grid--standard

This has the resizing function you were mentioning.

Let me know if you are still looking for more direction.

**Comment by christopherGdynia** [comment]
@timheiler-ico,

I don't see any keyboard functionality for resizing there
Additionally, I spoke to the Accessability Team and they said, if the default col width is enough, I don't need to make it accessable for keyboard, but if you have a solution I am interested :D
