### ISSUE TITLE
Date/Field not "resettable"

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#643]
Hi there,

i think this bug is somewhat related to a previous bug #440.

If I have Date Field with some value - I cannot reset it correctly (for example with an empty string). I always get some overlapping Labels/values.

```
    <ScaleDatePicker
              size="small"
              label="somelabel"
              name="someName"
              id="someID"
              identifier="someID"
              value={state.value}
              onInput={editDatesChangeHandler}
              onScaleChange={(e: CustomEvent) => {
                editDateInPicker(e);
              }}
            />
```

![reset](https://user-images.githubusercontent.com/66920189/138703928-8db76002-9099-4670-a3cb-045f52708738.png)

**Comment by nowseemee** [comment]
Many thanks for the hint, `3.0.0-beta.27` should fix this.

**Comment by tommy-codez** [comment]
Works now fine :)
