### ISSUE TITLE
Scale Icons are not consistent with the ones in the Brand-Design Dokumentation

### ISSUE THREAD

**Issue by telion2** [telekom/scale#646]
The svgs used in Scale are not the same as the ones documented in https://www.brand-design.telekom.com/downloads/icons/

This makes it difficult to decide with icons to use, as one version might go obsolete.
So I ask that if scale, becomes the root source for any SVG icons, that the documentation provides a possibility to download the icons. 
Also, it would be nice to have the icon page on the same level as the typography, as this is a page that will be visited often to find the needed Icon. I know it technically is a component, but it is cumbersome to find in the long list of components. I almost overlooked them. 

If scale does not become the root source for icons, I ask that scale is using the ones documented in the link I provided, as these are in my view the current official Icons. 

An example for an Icon that has 2 versions: Menu Icon: 
Brand-Design: https://www.brand-design.telekom.com/asset/icon-2081-hamburger-men/

Scale: https://www.brand-design.telekom.com/scale/?path=/docs/components-icon--icon-library 
```
<scale-icon-action-menu accessibility-title="menu" />
```
Since Scale is still in beta I want to note that any differences to brand-Design will cause additional overhead in applications that have to be compliant with Brand-Design and can't yet introduce scale, due to it being in beta.

**Comment by telion2** [comment]
Ok so as a developer I can either use: 
https://www.brand-design.telekom.com/scale/?path=/docs/components-icon--icon-library 
OR: 
https://www.brand-design.telekom.com/asset/icon-for-user-interfaces-0-icons-fr-user-interfaces/
And both sources provide the same icon set (I only checked a few). 

The source
https://www.brand-design.telekom.com/en/articles/i/icons-for-communication/  
provides Icons that are used for something else. 

Since that is out of the way, the remaining point would be "it would be nice to have the icon page on the same level as the typography,". 
Is this something you consider doing?

**Comment by tshimber** [comment]
hi @telion2 ! Scale is now in the maintenance mode, I guess the icons will stay as they are. we will close the issue if you don't have other questions
FYI @amir-ba
