### ISSUE TITLE
Large DropDown causes BrandHeader/AppShell To Scroll

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#649]
Hi there :)
this is quite a weird bug and somewhat difficult to explain -  so I am happy that I could make an example work on codesandbox where you can check and reproduce it :) (https://codesandbox.io/s/example-dropdown-brandheadermenu-bug-lw76i) (Also the behaviour differs in the browsers.)

Steps to reproduce:
- put a dropdown in his own component (causing rerendering with every change)
- the dropdown must have a bunch of entries, depending on your screensize/resolution
- You have an app-Shell / BrandHeader Menu component
- trigger a rerender of the dropdown

-> On every rerender the AppShell Menu starts moving and acts like the page is too large for the screen.
![grafik](https://user-images.githubusercontent.com/66920189/139011904-4b775c6c-1fff-4742-a617-69064b64ed4e.png)

**Comment by tommy-codez** [comment]
Hi,
we still have a lot of issues with the current dropdown component. (rendering/dynamic adding of items/default values etc..) Can you say when the new one will be available?

**Comment by acstll** [comment]
@tommy-codez this week 🚀

**Comment by nowseemee** [comment]
The new `dropdown-select` is now published with `3.0.0-beta.109`. It should provide solutions to the problems we were facing with the old `dropdown` component.
https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard
