### ISSUE TITLE
Focus gone after close modal dialog

### ISSUE THREAD

**Issue by lstraka-telekom** [telekom/scale#656]
I have a question about modal dialog and lost focus when the dialog is closed. Accessibility requirement is that original target which trigger open dialog should obtain focus back, if dialog is closed. 
Are you going to provide this feature inside modal component? Or do you have any suggestions how globally I should set it in my code without doing something manually in all closeDialog methods to provide focus back on target?

**Comment by acstll** [comment]
Thank you @mato-a for the reference, that was really helpful.

Yes, focus must return to the trigger element by default, but there are exceptions to this depending on each use case. So we think it's better to leave this decision to the developer.

We've added a [`setFocus`](https://github.com/telekom/scale/issues/658#issuecomment-954674060) method to `scale-button` and `scale-link` so you can set the focus to the trigger based on the `scale-close` event.
