### ISSUE TITLE
Icons are displayed multiple times

### ISSUE THREAD

**Issue by akiko29** [telekom/scale#659]
Hey guys,

we are running our Scale front ends (with Vue 3) in Openshift containers and noticed that the Scale icons are shown multiple times. It seems that the SVG inside the icon are rendered twice and in some case even more. Unfortunately I wasn't able to reproduce this bug locally.
Could you please provide a solution for this issue?
Thanks in advance!

![2021-10-08 10_42_35-Window](https://user-images.githubusercontent.com/44460117/139417230-8bf2491e-6e32-40c5-a905-721204881fff.png)

![7c44736a-eb8d-4eac-bdf7-533bea230e37](https://user-images.githubusercontent.com/44460117/139417244-07bc0bd2-9025-4346-ab37-59d5b2a1d156.PNG)

**Comment by acstll** [comment]
Hey @akiko29 I'm sorry to hear about this issue.

> Unfortunately I wasn't able to reproduce this bug locally.

so this means this only happens in the production environment, correct?

We will be more than glad to provide some help, but we have too little information to try and debug the issue. Could you please provide us with some more information?

- how are you loading the Scale library and what version are you using?
- what are any considerable differences between your local environment and the containers? (we're not familiar with Openshift containers)
- could you please share a snippet of some problematic code? (like the "Suche" button or the inputs)

Thank you very much!

**Comment by akiko29** [comment]
> so this means this only happens in the production environment, correct?

Exactly 


> how are you loading the Scale library and what version are you using?

We're using npm like we do locally. Scale is at Version ^3.0.0-beta.13 and at npm 6.14.15


> what are any considerable differences between your local environment and the containers? (we're not familiar with Openshift containers)

Basically the difference is that in the production environment Node.js is running inside Docker.


> could you please share a snippet of some problematic code? (like the "Suche" button or the inputs)

This is our code:

`<scale-button type="submit" data-filter-id="searchById">
     <scale-icon-action-search></scale-icon-action-search> Suche
  </scale-button>`

 And here the output of the rendering in our production environment:

`<scale-button data-filter-id="searchById" data-v-fe505356="" icon-position="before" class="hydrated"><scale-icon-action-search data-v-fe505356="" style="display: inline-flex;" class="hydrated"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><g fill="currentColor"><g><path fill-rule="evenodd" d="M21.4 19.6l-4.9-4.9a8.02 8.02 0 001.55-4.7c0-4.4-3.6-8-8-8S2 5.6 2 10s3.6 8 8 8c1.75 0 3.4-.55 4.7-1.55l4.9 4.9c.5.5 1.3.5 1.75 0 .5-.45.5-1.25.05-1.75zM3.5 10c0-3.6 2.9-6.5 6.5-6.5s6.5 2.9 6.5 6.5-2.9 6.5-6.5 6.5-6.5-2.9-6.5-6.5z"></path></g></g></svg><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><g fill="currentColor"><g><path fill-rule="evenodd" d="M21.4 19.6l-4.9-4.9a8.02 8.02 0 001.55-4.7c0-4.4-3.6-8-8-8S2 5.6 2 10s3.6 8 8 8c1.75 0 3.4-.55 4.7-1.55l4.9 4.9c.5.5 1.3.5 1.75 0 .5-.45.5-1.25.05-1.75zM3.5 10c0-3.6 2.9-6.5 6.5-6.5s6.5 2.9 6.5 6.5-2.9 6.5-6.5 6.5-6.5-2.9-6.5-6.5z"></path></g></g></svg></scale-icon-action-search> Suche </scale-button>`

I hope this helps for troubleshooting. Please let me know if you need any additional information.
Thanks in advance!

**Comment by acstll** [comment]
Thank you @akiko29 for your quick reply.

The first thing I would try is updating Scale to the latest beta version [`3.0.0-beta.27`](https://www.npmjs.com/package/@telekom/scale-components). Is that possible for you?

**Comment by akiko29** [comment]
Hi @acstll,
we did update the version just now but unfortunately nothing changed.

**Comment by acstll** [comment]
Thanks for trying. No worries.

Would it be possible for you to share your `package.json` file and maybe some Docker settings (without sharing any sensitive data)? We're gonna try and replicate it in a Openshift container as well so we can debug it.

Thanks again!

**Comment by akiko29** [comment]
No problem, here's our `package.json`:
```
{
  "name": "cdi-central-search",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "npm run lint:js && npm run lint:css",
    "lint:css": "stylelint \"src/**/*.vue\" --formatter verbose",
    "lint:js": "vue-cli-service lint",
    "test": "vue-cli-service test:unit",
    "update_snapshots": "vue-cli-service test:unit --updateSnapshot",
    "serve:standalone": "vue-cli-service serve --mode standalone"
  },
  "dependencies": {
    "@telekom/scale-components": "^3.0.0-beta.27",
    "babel-core": "^7.0.0-bridge.0",
    "core-js": "^3.6.5",
    "single-spa-vue": "^2.3.0",
    "systemjs-webpack-interop": "^2.3.7",
    "vue": "3.1.4",
    "vue-i18n": "8.22.4",
    "vue-router": "^4.0.10",
    "vuex": "^4.0.0-alpha.1"
  },
  "devDependencies": {
    "@commitlint/cli": "^9.1.2",
    "@commitlint/config-conventional": "^9.1.2",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/test-utils": "^2.0.0-alpha.1",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-vue": "^7.0.0",
    "jest": "^26.6.3",
    "prettier": "^2.0.5",
    "stylelint": "^13.6.1",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-webpack-plugin": "^2.1.0",
    "vue-cli-plugin-single-spa": "~2.2.0",
    "vue-jest": "^5.0.0-alpha.7",
    "vue-loader": "^16.3.0"
  },
  "gitHooks": {
    "commit-msg": "commitlint -e ''",
    "pre-push": "npm run lint && npm run test"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```
and the Docker file:
```
FROM nginx:1.20.1
ARG CONTAINER_ORIGIN
COPY openshift/nginx.conf /etc/nginx/nginx.conf
RUN sed -i "s|<CONTAINER_ORIGIN>|${CONTAINER_ORIGIN}|g" /etc/nginx/nginx.conf
WORKDIR /app
COPY ./dist .
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by acstll** [comment]
Thank you @akiko29, we will get back to you next week!

**Comment by reld** [comment]
@akiko29 Thanks for providing us with the data. It would be also great to get the nginx.conf file. This will save us time and also help us to replicate the system's setup as close as possible.
Thank you 🙏

**Comment by akiko29** [comment]
@reld, sure!

```
worker_processes auto;

pid /tmp/nginx.pid;

events {
 worker_connections 1024;
}

http {
 include /etc/nginx/mime.types; 
  client_body_temp_path /tmp/client_temp;
 proxy_temp_path       /tmp/proxy_temp_path;
 fastcgi_temp_path     /tmp/fastcgi_temp;
 uwsgi_temp_path       /tmp/uwsgi_temp;
 scgi_temp_path        /tmp/scgi_temp;

 server {
   listen 8080;
   server_name _;

   index index.html;
   error_log  /tmp/error.log;
   access_log /tmp/access.log;

   location / {
     root /app;
     try_files $uri /index.html;
   }
 }
}

```

**Comment by reld** [comment]
@akiko29 Brillliant, thanks for the file.
We will get into it and get back to you with our insights / foundings.
Until then, make yourself a wonderful time 👍

**Comment by acstll** [comment]
@akiko29 we were able to setup a project based on your package.json and config files and deployed it to an OpenShift container, but we couldn't reproduce the bug unfortunately. It behaves as expected.

Some remarks:
- while using `single-spa` there was a build error with Vue version `3.1.4`,  so we upgraded it to the latest 3.x.
- we ran and built the "single-spa" app in "standalone" mode

The only thing that we're suspicious about is `single-spa`, but it's only a hunch. Did you ever try deploying your app without it?

Would it be possible to arrange a meeting so we can take a look together in your production environment and debug it? If so, please email us at `ac (at) iconstorm.com`

**Comment by akiko29** [comment]
@acstll we have two other applications that are having the same issue and are running without Single-Spa.
Sure, we can debug it together, I'll drop an email for a meeting.

**Comment by acstll** [comment]
amazing, thank you!

**Comment by akiko29** [comment]
@acstll just a quick question: Did you run npm run build in your test or run serve? I'm asking because a college reminded me that the issue might have something to do with the build.

**Comment by acstll** [comment]
I'm almost sure we did `npm run build` (nginx serves the dist folder). @reld will be able to confirm this.

**Comment by Lalaluka** [comment]
Hi @acstll ,
can we reopen this issue? I'm facing the same issue using Vue3 and single-spa using beta.43.

It's an extremely weird issue. I did some investigation already and it's true that this cant be reproduced locally. This suggests some weird issue with single-spa/vue3 lifecycles colliding. But it somehow only affects the scale-icon lifecycle (????). I'm pretty convinced it needs to be a timing issue and tried some stuff already but didn't find the root cause.

I will try to build a minimal Setup reproducing the issue.

What I can confirm rn is:

- It has nothing to do with OpenShift (thats just the k8s coluster) we are using a different k8s cluster and it creates the same issues
- It has nothing todo with the nginx image @akiko29 used. We are using a different alpine image.
- Its not related to the build alone since running http-server locally works

But this should have been pretty obvious anyway.
