### ISSUE TITLE
Cannot change the scale-app-shell background color. 

### ISSUE THREAD

**Issue by gaurishkamat** [telekom/scale#664]
I am working on dark mode for a React based application.
I am using scale-app-shell which holds the main-container for my application.

How do I get access to the main element just below the scale-app-header (shown in the screenshot below) so that I can change its background color to transparent or app specific color.

Please find a screenshot below:
<img width="508" alt="Screenshot 2021-10-25 at 9 29 41 PM" src="https://user-images.githubusercontent.com/34893664/139641574-99cad36c-ed96-47af-a7a6-fe994f5c7af7.png">

I am using ^3.0.0-beta.22 version of the scaled-components.

**Comment by nowseemee** [comment]
Hi @gaurishkamat, you can override the global CSS variable `--scl-color-background-standard` or local to the app-shell: `--background`.

Let me know if this helps. Thanks!

**Comment by christopherGdynia** [comment]
Hi @gaurishkamat 

take a look at this #486

I have a working darkmode

**Comment by gaurishkamat** [comment]
Hi @nowseemee, changing the `--scl-color-background-standard` helped. Thanks a lot :)
