### ISSUE TITLE
Scale Tag - ToolTip (mouse over / aria label) doesn't work

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#667]
We are using the Scale "Tag" component. As a matter of usability the user needs to get more information by means of ToolTips (mouse over / aria lable). Instead, the heading of the modal is displayed (please compare also issue #666):
![Screenshot_ToolTip_not_working_with_Scale_Tag](https://user-images.githubusercontent.com/88503149/139905016-7aea1e4b-5388-4d84-8d82-6cf766cd3dd6.png)

Expected behaviour: The Scale "Tag" component supports ToolsTips.

**Comment by acstll** [comment]
OK, this is clearly related to #666 🤘 We will work on that one first. Thank you!

---
An actual new Tooltip component is being released imminently, you probably will be able to use it here.

**Comment by acstll** [comment]
@UBOrange have you tried adding `title` together with `aria-label` to the `scale-tag` component? I did test this and it works (without the table though).

```html
<scale-tag title="Blockiert durch vorgang" aria-label="Blockiert durch vorgang">Blockiert</scale-tag>
```

**Comment by UBOrange** [comment]
Adding title together with aria-label to the scale-tag component solves the problem. Thank you very much for your quick response and your help!
