### ISSUE TITLE
public Storybook URL

### ISSUE THREAD

**Issue by WalkingOS** [telekom/scale#673]
Hey guys,

We would like to import Scale in "UXPin Merge" (We will get a 2 week trial for test purposes).
Currently we can choose between a public and a private Storybook. 

In case we can't go with a private Storybook: Is there any way to get (brand-design.telekom.com/scale) as an public Storybook?

**Comment by acstll** [comment]
Hello @WalkingOS 

this is a really interesting use case! When you say "import", you mean you would like to use the components in UXPin Merge, correct? We'll be really happy to support you there.

Regarding Storybook, I'm not sure I understand the problem.

> Currently we can choose between a public and a private Storybook.

do you need to have an extra private instance of Storybook? Don't you have access to brand-design.com?

> Is there any way to get (brand-design.telekom.com/scale) as an public Storybook?

not currently, this is an open question (https://github.com/telekom/scale/issues/584) — if you clone the repo you can run it locally.

**Comment by WalkingOS** [comment]
@acstll thank you for the answer and the offer to support us! The UXPin Merge Team will also support us in this subject.

Yes, we wan't to use the components in UXPin and test if it's possible to design telekom standard prototypes with coded components.

We have access to brand-design.com but I'm not sure if it will be possible to import the scale storybook into UXPin Merge, because it's like not a classic private Storybook. (the brand-design instance is on top of it) So if the option "import your private Storybook" not works cause of that, we will need a plan B. 

> not currently, this is an open question (#584) — if you clone the repo you can run it locally.
I already asked the UXPin Team if it's possible to import a local storybook. The answer was a clear no o.o

**Comment by acstll** [comment]
Thank you, now I understand. UXPin Merge is using Storybook to do the importing.

Yes, it should be possible for you to have your own private "public" instance of Storybook for such a purpose, which then you can delete after the import. If plan A fails, please get in touch with me at ac(at)iconstorm.com and I will gladly assist you.

**Comment by acstll** [comment]
Closing this issue for now, but please let's keep in touch 🙂
