### ISSUE TITLE
Datagrid: Key-value pairs as row structure

### ISSUE THREAD

**Issue by akiko29** [telekom/scale#675]
Hey guys,

I think the data grid is a great component, unfortunately it's not really usable for us since we are working with a big amount of data in our project. It's quite a pain to put everything into an array since we're getting a JSON response from our back end which is not in the order we want to display it. Would it be possible to add key-value pairs for the row structure? Would be great!

Thanks in advance :)

**Comment by nowseemee** [comment]
Hi @akiko29, thanks for your kind feedback and for posting this question. 

Unfortunately, we don't have plans to change the API of the DataGrid as it might be expensive in terms of the effort compared to the potential benefits the refactoring might bring. However, this is by no means a show stopper for your use case - I expect writing a transformer utility function to massage the JSON payload into the shape required by the DataGrid is a viable option. 

I hope my answer is somewhat useful and sorry for not being able to provide greater assistance.

Please feel free to come back to us with further reasons for your feature request to be considered - we are happy to discuss new ideas.
