### ISSUE TITLE
Cannot add onClick listener to items in main-navigation attribute for Scale-Navigation

### ISSUE THREAD

**Issue by Xt1an** [telekom/scale#677]
Hello everyone!

I'm trying to add an onClick listener to my third level menu links, via an JSON-String directly in the HTML-File like this:
`[{
		"name": "Topic Three",
		"id": "Topic Three",
		"children": [
			{
				"name": "Second Level",
				"id": "Second Level 3",
				"children": [
					{
						"name": "Third Level",
						"id": "Third Level 4",
						"onClick": "myExpectedMethod()"
					}
				]
			}
                ]
}]`

I've tried "onclick", "click", "onClick", just the Method name without the bracket and other variations, to make sure it's no spelling issue, but it just won't work.

Is there a thing I'm missing?

**Comment by nowseemee** [comment]
Hi @Xt1an, instead of a JSON String, you have to pass an object to the components. Otherwise, `onClick` is the correct name - you got that right. Feel free to reopen in case you want me to expand on this.

**Comment by Xt1an** [comment]
> Hi @Xt1an, instead of a JSON String, you have to pass an object to the components. Otherwise, `onClick` is the correct name - you got that right. Feel free to reopen in case you want me to expand on this.

@nowseemee by object you mean the direct assignment of the attribute value in Javascript? Because that does not work either, atleast for me.

**Comment by nowseemee** [comment]
I see - can you provide a code sandbox with example code so I can better assist you?

**Comment by Xt1an** [comment]
Sorry for my late answer, unfortunately this would take to long, because i would have to replicate my menu bar implementation in the sandbox. Can i just send some screenshots? Or is there maybe an example code where someone has implemented it that way?

**Comment by nowseemee** [comment]
Try this way:
![image](https://user-images.githubusercontent.com/4532334/140723859-a8433854-56aa-402a-9ee2-0690d49d3fec.png)

**Comment by nowseemee** [comment]
Try this way:

![image](https://user-images.githubusercontent.com/4532334/140723959-88afcec5-7e63-4d9b-8ba2-de2b6586b79c.png)

**Comment by Xt1an** [comment]
> Try this way:
> 
> ![image](https://user-images.githubusercontent.com/4532334/140723959-88afcec5-7e63-4d9b-8ba2-de2b6586b79c.png)

Thank You! The problem was, that i had single quotes around the attribute names like 'name': 'value' 😅.

**Comment by nowseemee** [comment]
Nice, thanks for the feedback :)
