### ISSUE TITLE
Date Picker: How to display 1st of January 2022 as 01.01.2022 (and not as 1.1.2022)?

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#694]
Just a question / request for help: In our (German) context the Data Picker component should display the date "1st of January 2022" as 01.01.2022 (and not as 1.1.2022).
I checked the solution to ticket #634 "DatePicker Month in German" as working in the "Sandbox", but this solution also displays the date as 1.1.2022.
What do I need to do to get the format with the leading zeros?
Thanks for your help! :-)

**Comment by nowseemee** [comment]
Hi @UBOrange, thanks for the question.

You can use the `dateAdapter` prop to do this:

```
const DATE_FORMAT = /^(\d{1,2})\.(\d{1,2})\.(\d{4})$/;

picker.dateAdapter = {
  parse(value = '', createDate) {
    const matches = value.match(DATE_FORMAT);

    if (matches) {
      return createDate(matches[3], matches[2], matches[1]);
    }
  },
  format(date) {
   return date.toLocaleDateString("de-DE", { // you can use undefined as first argument
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    })
  },
};

```

> Date adapter, for custom parsing/formatting. Must be object with a parse function which accepts a string and returns a Date, and a format function which accepts a Date and returns a string. Default is IS0-8601 parsing and formatting.
