### ISSUE TITLE
Vue3 Slot Issues

### ISSUE THREAD

**Issue by SteffTek** [telekom/scale#698]
While working with the Vue3 I encountered an issue with the slot attribute used almost everywhere (Brand Header, Accordion, Tabs). It's deprecated in Vue3 and should not be used. Vue won't compile with a slot attribute.

![grafik](https://user-images.githubusercontent.com/5563452/142142466-40c356a3-960d-428c-80e6-c6d93c9234b6.png)

Is there a workaround for this limitation that doesn't involve turning off the linter? Or is this another issue entirely?

I tried it with v-slots, but it doesn't work or I am missing something that isn't documented in the scale documentation for Vue3.

![grafik](https://user-images.githubusercontent.com/5563452/142143184-8cf6db7d-c10d-430e-9d6a-00232ab60425.png)

Thanks and kind regards.

**Comment by acstll** [comment]
Thanks for asking @SteffTek 

[`slot` is an HTML attribute specific to the Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot). Its use in the Scale components is not related to the Vue slots feature in any way. (I'm guessing they deprecated `slot` in favor of `v-slot` to avoid conflicts with the platform). So it should be OK to use with Vue 3 or any other framework.

If you'd like to have a deeper understanding of slots and Shadow DOM I highly recommend this resource: https://javascript.info/slots-composition#named-slots

> Is there a workaround for this limitation that doesn't involve turning off the linter?

I would suggest you disable the linting rule specific to that error, without having to turn off the linter entirely. Here they show a way to do it: https://stackoverflow.com/questions/65913547/ionic-slot-attributes-are-deprecated-eslint-plugin-vue

After disabling the `vue/no-deprecated-slot-attribute` rule you should be able to build the project. Please let us know if that isn't so.

**Comment by Lalaluka** [comment]
Hi @acstll,
100% agree and I think we talked about this before. 
I'm not sure if it's worth to document it in the Storybook?

**Comment by SteffTek** [comment]
Hey together,

sorry for the late reply. I agree with @Lalaluka, it should be mentioned in the Storybook. 

It's the only rule that seems to be "broken". Maybe you can adjust the vue3-boilerplate too? It's missing the .eslintrc.js needed for this to work.

**Comment by Lalaluka** [comment]
The Vue Boilerplate uses Eslint Settings embedded in the Package.json
https://github.com/telekom/scale/blob/ff23adb72ffb9927314826eff26980d1d3487fb8/examples/vue3-boilerplate/package.json#L36

You can disable the rule there.

**Comment by SteffTek** [comment]
> The Vue Boilerplate uses Eslint Settings embedded in the Package.json
> 
> https://github.com/telekom/scale/blob/ff23adb72ffb9927314826eff26980d1d3487fb8/examples/vue3-boilerplate/package.json#L36
> 
> You can disable the rule there.

Well this would have been helpful to know in the first place, thanks! 

Did I miss it in the Storybook or isn't it mentioned either?

**Comment by acstll** [comment]
This is not mentioned in Storybook. It would be a great addition indeed.

Thank you @Lalaluka for the great feedback.
