### ISSUE TITLE
Contents of app-shell component not centered when using --header-max-width css variable

### ISSUE THREAD

**Issue by jankrueger** [telekom/scale#705]
Hey Scale team, 

we are using the CSS variable `--header-max-width` to restrict the application to span the whole screen on large devices. 
Setting the maximum width works, but after that the contents will be bound to the left and not centered. I believe the problem is caused by this change: https://github.com/telekom/scale/commit/8c8b8e969862a80df6c4eea1489292750e591250#diff-af3476b9cb234abdac7a5327c531a49edd5c5bbd9cbe0806646b053e09fb5552L56

I also thought there was another CSS variable in the past that applied to the actual contents but that must been before the move to github/refactoring i guess.

**Comment by acstll** [comment]
Hey @jankrueger thanks for opening this and for the hint to the problem. I wonder why we removed that declaration.

@nowseemee would it be OK to bring the `margin: 0 auto` declaration back?

**Comment by nowseemee** [comment]
Hi @jankrueger, thanks for reporting this bug. I've released the fix for it with `3.0.0-beta.32`. Cheers!

**Comment by jankrueger** [comment]
Thanks a lot, it works fine now! 👍
