### ISSUE TITLE
There is no option to change text in the label

### ISSUE THREAD

**Issue by Melicenta** [telekom/scale#711]
Component: https://www.brand-design.telekom.com/scale/?path=/docs/components-brand-header-navigation--custom-mobile-menu&globals=locale:en

![image](https://user-images.githubusercontent.com/10254315/144052638-a306770d-81b0-4a78-80e3-7fc85c1fe35a.png)

It would be great to have a possibility to change the label from 'close'

**Comment by nowseemee** [comment]
Hello @Melicenta and thanks for your question.

You can configure the label via the `icon-navigation` attribute:

```
[
  {"id":"menu","defaultName":"Menu","openedName":"Close"},
  ...
]
```

I hope this helps. Please feel free to share if you ever have findings or other questions. Thanks!
