### ISSUE TITLE
Overlap and focus errors in the flyout menu

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#712]
Hey

there are some errors in "flyout menu".

first:
Expandebal sublists overlap.
![image](https://user-images.githubusercontent.com/73475493/144056902-0a5b799f-3bf5-488c-886c-5f1bcfde72a4.png)
---
second one:
There is a "focus" error in the dev console for select and close actions.
![image](https://user-images.githubusercontent.com/73475493/144056658-735b9bcd-401a-4072-8b7c-c2cccdb1e5b5.png)

can you fix this please?
Great. Thanks!

**Comment by acstll** [comment]
Hey @tomkroschwald

Thank you for reporting this. We'd love to fix this one.

Could you please provide a bit more information, including:

- a code snippet of the menu as you're using it
- are you using vanilla JS or some framework?
- is the flyout located inside any other specially-positioned elements?
- what's the size of the viewport when the error overlapping errors occurs?

Thanks a lot in advance!

**Comment by tomkroschwald** [comment]
Hey @acstll,
we use scale together with Vue 2.

We have positioned the flyout menu in the menu. There the console error appears and the overlap occurs.
When the flyout menu is used in the main, only the overlap error occurs.

It is located here:

```html
<scale-app-shell>
    <scale-app-header slot="header" claim-lang="de">
        <div>
            <scale-menu-flyout>
                <div slot="trigger" style="height: 56px;">
                    <scale-nav-main name="Information"></scale-nav-main>
                </div>
                <scale-menu-flyout-list>
                    <scale-menu-flyout-item>Item 1</scale-menu-flyout-item>
                    <scale-menu-flyout-item>Item 2</scale-menu-flyout-item>
                    <scale-menu-flyout-item>More Options
                        <scale-menu-flyout-list slot="sublist">
                            <scale-menu-flyout-item>Option 1</scale-menu-flyout-item>
                            <scale-menu-flyout-item>Option 2</scale-menu-flyout-item>
                            <scale-menu-flyout-item>Option 3</scale-menu-flyout-item>
                        </scale-menu-flyout-list>
                    </scale-menu-flyout-item>
                    <scale-menu-flyout-item>More Options
                        <scale-menu-flyout-list slot="sublist">
                            <scale-menu-flyout-item>Option 1</scale-menu-flyout-item>
                            <scale-menu-flyout-item>Option 2</scale-menu-flyout-item>
                            <scale-menu-flyout-item>Option 3</scale-menu-flyout-item>
                        </scale-menu-flyout-list>
                        </scale-menu-flyout-item>
                </scale-menu-flyout-list>
            </scale-menu-flyout>
        </div>
    </scale-app-header>
</scale-app-shell>
```

![image](https://user-images.githubusercontent.com/73475493/144422222-8fc151b5-b59e-470c-99d6-77679aaaad62.png)

___
The errors appear with all window sizes. In this case the viewport is 1920x1080px.
![image](https://user-images.githubusercontent.com/73475493/144423219-0960746b-eb74-4340-b8db-8111195ba492.png)

I hope the information will help you!

**Comment by acstll** [comment]
Haven't forgotten about this, thanks for the patience! 🙏
