### ISSUE TITLE
Date Picker: Missing border around the icon when scaling the screen

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#717]
Scaling the screen to 67% (or less) the "Date Picker" component loses parts of his border around the icon (see the attached screen shot for an example). Browser: Chrome; but also seen using Firefox.
![Screenshot_Scale_Date-Picker_border_partly_missing](https://user-images.githubusercontent.com/88503149/144449849-dccf920c-9a0a-4e84-b33e-a381c04484b8.JPG)

**Comment by nowseemee** [comment]
Hi @UBOrange!

Can you see the same on https://www.brand-design.telekom.com/scale/iframe.html?id=components-date-picker--standard&args=&globals=locale:en&viewMode=story ?

Can you share an example code to reproduce the issue? Thanks a lot!

**Comment by UBOrange** [comment]
Here is the screenshot from Scale (https://www.brand-design.telekom.com/scale/?path=/story/components-date-picker--standard&globals=locale:en).
![image](https://user-images.githubusercontent.com/88503149/145013715-e50cc2ce-2c57-47d0-97b2-619f3cacf846.png)
Just set the screen size to 33% (using Chrome). Within our application it's enough to reduce the screen size to 67% to cause the effect.

**Comment by nowseemee** [comment]
Many thanks for the screenshot, @UBOrange - this should be fixed in the latest release: `3.0.0-beta.37`.
