### ISSUE TITLE
Tooltip bugs (beta)

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#718]
Hi all,

We tried integrating tooltip into our app and found these issues:

# 1. It is not documented with which html or scale components the tooltips are compatible, but I found that it doesn't work everywhere. The tooltip is not displayed or is displayed only partially:

  - supported: `scale-button`, `scale-checkbox`, `input`
  - broken: `scale-toggle-button`, `app-logo`, `img`, `a`

![obrázok](https://user-images.githubusercontent.com/49948501/144574962-8a14182a-708f-4c60-923a-4dde1879eb47.png)
![obrázok](https://user-images.githubusercontent.com/49948501/144575056-64317114-fe13-4147-aa03-f5cce91eb3e0.png)
![obrázok](https://user-images.githubusercontent.com/49948501/144575073-7609aa47-43d0-453d-a84c-cdf0ee5e7411.png)
![obrázok](https://user-images.githubusercontent.com/49948501/144575079-2b1ba8ae-95e5-4e03-81f8-418c343c66ce.png)

# 2. In addition to point above when tooltip is used for `app-logo` the telekom logo is not fully visible and it's moved up

![obrázok](https://user-images.githubusercontent.com/49948501/144575248-2a3b6853-efe1-4960-b0a7-398afcdc2a8f.png)

# 3. When you move focus in menu with TAB, focus moves also to tooltip. It does not happen with TAB+Shift

Tooltip should not get focus according the specs https://www.w3.org/TR/wai-aria-practices/#tooltip:

> Tooltip widgets do not receive focus. A hover that contains focusable elements can be made using a non-modal dialog. 

# 4. Tooltip from focused object is not hiding. When you move focus with keyboard and then also use mouse hover for another object, you can have 2 covering tooltips. The one triggered with keyboard focus should be hidden automatically in this case.

**Comment by mato-a** [comment]
Hi all,

Are there any updates concerning this?

**Comment by acstll** [comment]
We're still working on this @mato-a Thanks for the reminder and for the patience 🙏

**Comment by nowseemee** [comment]
Hey all, thanks for the valuable discussion. A rewrite of the tooltip component utilizing `floating-ui` instead of `popperjs` has been published (3.0.0-beta.108) and hopefully solves this issue. Feel free to reopen in case something is still not right.
