### ISSUE TITLE
Support autofocus attribute for text fields and areas

### ISSUE THREAD

**Issue by ScrumplexDTAG** [telekom/scale#720]
HTML5 `<input>` elements support an attribute called `autofocus` so that a text field is in focus when the page is loading. Setting autofocus like `<scale-text-field ... autofocus>` doesn't work, as it's not passed to the underlying `<input>` element. 

It could be implemented in a way that the `focus` event gets passed to the `<input>` element.

**Comment by nowseemee** [comment]
Hi @ScrumplexDTAG, many thanks for your suggestion. We will enable this attribute soon and let you know here as soon it's available.

**Comment by nowseemee** [comment]
The `input-autofocus` attribute was added to `scale-text-field` and `scale-textarea` in version `3.0.0-beta.34`. Thanks again for your valuable suggestion.

**Comment by ScrumplexDTAG** [comment]
Thanks for implementing this. Apparently this does not work as expected. I think browsers only look for this attribute once (probably when page is loaded fully). I guess Scale creates the input fields too late into the process which means that this has no effect at all. Maybe this needs to be implemented manually instead?

**Comment by nowseemee** [comment]
Hi @ScrumplexDTAG, it is nice to hear from you. Probably you ran into the issue that is mentioned in this article: https://blog.maisie.ink/react-ref-autofocus/#elements-added-to-the-dom-after-page-load

The autofocus behavior is inconsistent when adding an element to the DOM after the first render. Your best bet is to imperatively call the focus method of the component after adding it to the DOM. Something like this:
```
    <scale-text-field
      input-id="my-input"
      label="My Input"
    />

    <script>
      setTimeout(() => {
        window.document.querySelector('#my-input')();
      }, 1000);
    </script>
```

I hope this helps
