### ISSUE TITLE
When zooming more than 175% header breaks

### ISSUE THREAD

**Issue by dillasyx** [telekom/scale#732]
When I'm zooming for more than 175% (necessary for accessibility) then all links from the header are gone

**Comment by nowseemee** [comment]
Hello. The Brand Header has a mobile menu for smaller viewports.

**Comment by dillasyx** [comment]
![image](https://user-images.githubusercontent.com/11612223/145570910-3b890939-acb2-4519-9251-473c374d33e1.png)
Can't see anything, do I have to set mobile menu up?

**Comment by nowseemee** [comment]
Yes, the mobile menu has to be either configured via the `main-navigation` attribute or implemented using the custom slots:
```
    <scale-app-header slot="header" id="header">
      <div slot="menu-mobile"><pre>menu-mobile</pre></div>
    </scale-app-header>
```
