### ISSUE TITLE
Multi-line in Data Grid

### ISSUE THREAD

**Issue by robertgebhard** [telekom/scale#735]
Hi,

is it possible to display multi-line table contents in the data grid?

We need to display a large amount of data and want to avoid that the data grid becomes too wide.

We have tried to set "maxWidth" in the TextCell - this has been ignored. If we set "width", it will be accepted, but then the text will be cut off.

Greetings
Robert

**Comment by acstll** [comment]
Hey @robertgebhard 

that's not currently possible with the Text Cell, which will get cut ("ellipsed") by default.

Have you tried the HTML Cell? I think it was meant also for this cases of large content. You could use a `<p>` tag with    
 `white-space: normal` (that's needed) and probably something like `max-width: 60ch`.
 
Another option would be adding a link/toggle to open the content in a modal?

And, last but not least, a new Multi-line Text Cell to be developed and included is not to be discarded.

Let me know what you think.

**Comment by robertgebhard** [comment]
Hallo @acstll,

thank you for your answer. I have thought about the problem again and tried something around.

We sometimes have a large amount of data to display. It's important to users that they can see everything at the same time, and they don't want to open modals to see details.

I have tried the HTML cell. With this the data is not ideal to read in such a view.

If you have a lot of data, you have to open a modal first and then close it again. This makes it very inconvenient to capture the content of a table and to compare values with each other. Unfortunately, we cannot use this for our project.

I think a Multi-line Text Cell would be the best solution in this case and would also help other teams or projects to display data well.

Here's one of the many tables we have to display in the project, so you can get a better picture of it:
![Bildschirmfoto 2022-01-17 um 10 11 21](https://user-images.githubusercontent.com/95682620/149740769-4236d44c-f3fe-4485-a82f-f79f5b086fd7.png)

Thanks for your efforts.

**Comment by robertgebhard** [comment]
Hello there,
do you already have something new to report on the topic? The possibility to display multi-line content in the data grid is becoming increasingly important for our projects.
Thanks!

**Comment by acstll** [comment]
Not yet, but it's on our radar 🙏 — we have a lot of Data Grid improvements we want to make 💪

**Comment by VukDju** [comment]
Could you please give an example of how you were able to get the multi-line text in ScaleDataGrid? It is important to us to have text displayed in multiple lines...
