### ISSUE TITLE
Wrong Brand-Design Docs

### ISSUE THREAD

**Issue by H4CK3R-01** [telekom/scale#736]
Hi
I am using VueJS 3 and I had some Problems with the datepicker and textfields.

I wasn't able to change the location to the german date format although I used the example given in the docs.
According to the documentation the datepicker has the property "identifier" but it has to be "id". Otherwise it will not work.

And a second Problem I found is the text input field. I can disable it with the property "disabled". But if I want to set it to "invalid", nothing changes. I used the example from the docs, so I'm pretty sure that there is a bug or the documentation is wrong

**Comment by nowseemee** [comment]
Hello @H4CK3R-01, can you share the code you have used to enable localization for the date-picker with Vue, please?

**Comment by H4CK3R-01** [comment]
I used the code from the docs:
```
<template>
  <scale-date-picker label="Localization" identifier="picker"></scale-date-picker>
</template>
```
and
```
<script>
const picker = document.getElementById("picker");
picker.localization = {
  buttonLabel: "Datum wählen",
  placeholder: "TT.MM.JJJJ",
  selectedDateMessage: "Gewähltes Datum",
  prevMonthLabel: "Vorheriger Monat",
  nextMonthLabel: "Nächster Monat",
  monthSelectLabel: "Monat",
  yearSelectLabel: "Jahr",
  closeLabel: "Fenster schließen",
  keyboardInstruction:
      "Sie können mit den Pfeiltasten vor und zurück navigieren",
  calendarHeading: "Datum wählen",
  dayNames: [
    "Sonntag",
    "Montag",
    "Dienstag",
    "Mittwoch",
    "Donnerstag",
    "Freitag",
    "Samstag"
  ],
  monthNames: [
    "Januar",
    "Februar",
    "März",
    "April",
    "Mai",
    "Juni",
    "Juli",
    "August",
    "September",
    "Oktober",
    "November",
    "Dezember"
  ],
  monthNamesShort: [
    "Jan",
    "Feb",
    "Mär",
    "Apr",
    "Mai",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Okt",
    "Nov",
    "Dez"
  ],
  today: "heute",
  locale: "de-DE"
};

const DATE_FORMAT = /^(\d{1,2})\.(\d{1,2})\.(\d{4})$/;
picker.dateAdapter = {
  parse(value = "", createDate) {
    const matches = value.match(DATE_FORMAT);
    if (matches) {
      return createDate(matches[3], matches[2], matches[1]);
    }
  },
  format(date) {
    return `${date.getDate()}.${date.getMonth() + 1}.${date.getFullYear()}`;
  },
};
</script>
```

If I change `identifier` to `id` it works.

**Comment by nowseemee** [comment]
Oh, very well - thanks a lot for pointing out that the documentation was off. I've fixed it in the above PR and it will be published on the official page in the upcoming days. Should you have any other remarks you are more than welcome to report them. Thanks again!
