### ISSUE TITLE
Cannot find popperjs module

### ISSUE THREAD

**Issue by richardjanka** [telekom/scale#740]
Hello, 
I create a brand new Angular project with scale components (v. 3.0.0-beta.35) and when I serve the project I get an error: 

`Error:  node_modules/@telekom/scale-components/dist/types/components/tooltip/utilities/popover.d.ts:11:44 - error TS2307: Cannot find module '@popperjs/core' or its corresponding type declarations.
import { Instance as PopperInstance } from '@popperjs/core';
`

**Comment by nowseemee** [comment]
Hi @richardjanka, thanks for opening this issue. The new version `3.0.0-beta.36` should solve this problem - thanks again for helping us to uncover that this dependency was not listed. Much appreciated!
