### ISSUE TITLE
Modal: how to remove "X" or cookie accepte window

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#741]
Hello dear community,

would be nice to have "X" as an option that could be disabled. Use Case is e.g. cookie dialog where user have to accept or decline it, but not close window.
![grafik](https://user-images.githubusercontent.com/6813635/146026608-0c9a4925-11c4-4115-911e-b8feae3b67c4.png)

What you think about?

**Comment by acstll** [comment]
Hey @GAS85 thanks for asking.

You can effectively hide the close button with this bit of CSS:

```css
scale-modal.no-close-button::part(close-button) {
  display: none;
}
```

```html
<scale-model class="no-close-button">
```

But this **currently breaks the focus flow** (keeping the focus within the modal), so I wouldn't recommend you do this!

You can also prevent the modal from closing when users use the close button, by leveraging the `scale-before-close` event. Something like this:

```js
const el = document.querySelector('scale-modal') // use the appropriate selector, this is just to demo the idea

el.addEventListener('scale-before-close', function (event) {
  if (event.detail.trigger === 'CLOSE_BUTTON') {
    event.preventDefault() // this prevents the modal from closing
  }
})
```

Would this be enough for you?

**Comment by acstll** [comment]
@GAS85 were you able to solve this one?

**Comment by acstll** [comment]
Closing this assuming it's all good, please re-open or get in touch if not. We're open to considering adding this as an option for a cleaner solution. Thanks again for your feedback.

**Comment by GAS85** [comment]
Actually we simply add "Ok" as you can only agree to this window.
![grafik](https://user-images.githubusercontent.com/6813635/179211429-55b8cad3-39da-45e8-8b08-5e5b842ca9a6.png)

But for a new Window in works like this:
[![grafik](https://user-images.githubusercontent.com/6813635/179211570-55d47e19-b00a-4a1d-acf1-7a023995e719.png)](https://developer.telekom.de/catalog)
