### ISSUE TITLE
Sidebar Navigation media query

### ISSUE THREAD

**Issue by H4CK3R-01** [telekom/scale#764]
Hello
I am using VueJS 3 and have a problem with the sidebar navigation.

I want to use the collapsibleMediaQuery attribute to collapse the sidebar at a different width. (collapsible-media-query="(max-width: 1200px)").
This works as expected if the window size is above 1200px when the page is loaded, and then the window is collapsed to a width below 1200px.

But if the window width is below 1200px when the page is loaded, the sidebar is not collapsed. I have to resize the window to over 1200px and then back and it works again

**Comment by nowseemee** [comment]
Hi @H4CK3R-01, thanks for opening this ticket and sharing a detailed explanation. We will look into fixing this issue and come back to you as soon as the patch is released.

**Comment by H4CK3R-01** [comment]
Hi @nowseemee 
Is there any news for this problem?
We need this in our project....

**Comment by nowseemee** [comment]
Hi @H4CK3R-01 - we are still figuring this out. I will post here the progress by the end of today. Thanks for your patience and for coming back to me asking for updates.

**Comment by nowseemee** [comment]
This should be fixed in `3.0.0-beta.46`. Thanks for getting in touch, @H4CK3R-01!

**Comment by H4CK3R-01** [comment]
Thank you, I will try it tomorrow.

**Comment by H4CK3R-01** [comment]
It works :-)
Thank you
