### ISSUE TITLE
Tooltip for closing modal window

### ISSUE THREAD

**Issue by machovan** [telekom/scale#771]
Hello,
I would like to ask if it is OK that tooltip for "X" to close modal window is same as Title of modal window. I expected something like "Close" instead of that.
Thank you.

**Comment by maomaoZH** [comment]
Dear @machovan,
Thanks for reaching us. If I understand it correctly, you would like to have a feature for tooltip which user can close the tooltip by clicking, eg, a close "X" button?

**Comment by machovan** [comment]
Dear @maomaoZH 
I meant to replace text of tooltip for "X" button in modal dialog from the name of modal window to "Close" - see creen. What do you think about it?
![image](https://user-images.githubusercontent.com/97286043/148545579-e252956f-a081-44c9-9726-955260506710.png)

**Comment by maomaoZH** [comment]
Hi @machovan thanks for your quick feedback. We will have a look and get back to you!

**Comment by mato-a** [comment]
Hi,

This is related to: https://github.com/telekom/scale/issues/666

Modal has prop `closeButtonLabel` which I think should be used for this purpose. So it is not really a feature request, but a bug.
This prop could be renamed to `closeButtonAccessibilityTitle`

**Comment by mato-a** [comment]
Seems to be fixed here: https://github.com/telekom/scale/compare/v3.0.0-beta.47...v3.0.0-beta.48

We'll test it our app and get back to you.

**Comment by machovan** [comment]
Currently there is no tooltip for "X" button in modal dialog. Is it OK?

**Comment by mato-a** [comment]
So what happened is that only the related bug was fixed here: #666

But modal dialog is still missing the requested feature - to be able to set the title for `close button` (X).

Currently there is only `closeButtonLabel` which assigns aria-label to the `close button`.
Similar prop should be created `closeButtonTitle` which would assign title to the  `close button`.
