### ISSUE TITLE
Toggle-Group [beta] - border style issue with just one element | radius="both" not working

### ISSUE THREAD

**Issue by klmpfh** [telekom/scale#777]
Hey,

we tried the beta component Toggle-Group and noticed the following in our vue project.

If there is only one toggle button in the group, the frame is not displayed correctly on the left.
The attribute "radius" cannot be set to "both".

With only one element in the group, there is no frame on the left.

Can you check the constellation and fix it as soon as possible?

Thanks a lot,
Max Breitfeld
DTT AI

**Comment by klmpfh** [comment]
```
<scale-toggle-group>
  <scale-toggle-button radius="both">just one</scale-toggle-button>
</scale-toggle-group>
```

**Comment by maomaoZH** [comment]
Hi @klmpfh Thanks for reporting this issue. We will fix it as soon as possible and let you know.
