### ISSUE TITLE
Scale Dropdown values Overlap with label when selected using down arrow keys of keyboard.

### ISSUE THREAD

**Issue by toshniwala** [telekom/scale#778]
Hi Team,

I am trying to use "Scale Dropdown" functionality which is the component of scale library.
I am referring,
https://www.brand-design.telekom.com/scale/?path=/docs/components-dropdown--standard

When I select values from scale dropdown using down/up arrow key from keyboard then values get overlap with label of dropdown. Please refer attached image.

We are using "@telekom/scale-components": "^3.0.0-beta.27"

![scaledropdownIssue1](https://user-images.githubusercontent.com/97514549/148925254-ad506969-2494-4da1-bb85-a812669291d3.png)

Can I get some solution for this?

Thanks

**Comment by maomaoZH** [comment]
Hi @toshniwala  
Thanks for reporting this issue. I tried to reproduce this issue with my keyboard, but the dropdown list always covers the select box. Perhaps can you tell me which browser are you using when see this issue? 

Cheers
Maomao

**Comment by toshniwala** [comment]
@maomaoZH @acstll I am using google chrome and version of browser is  92.0.4515.107 (Official Build) (64-bit)

**Comment by maomaoZH** [comment]
Hi, I tried to re-produce this issue both on Mac and window. I can not produce it. Perhaps can you try again? 
![Screenshot (2)](https://user-images.githubusercontent.com/23239723/178259587-8375bb78-ab70-4481-b51b-5fa30dfdb7de.png)
