### ISSUE TITLE
Scale header issue on iPad pro landscape

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#781]
While checking different device dimensions in the Google Chrome browser (version 96.0.4664.110), I noticed that the Scale header component (version 3.0.0-beta.41) has an extra magenta line that should not appear. To achieve this behavior I used the iPad pro landscape mode with a custom zoom percentage. Not sure if this is a browser issue, or just an edge case breakpoint.

![image](https://user-images.githubusercontent.com/22682250/148959357-ad2fa92d-9778-4065-9886-f19a67e45016.png)

**Comment by maomaoZH** [comment]
Dear @pomoalex,

Thanks for reporting this issue. It is a general rendering problem from Chrome if you use Chrome user-agent for testing purpose. In real device, users should not see this magenta line. But please do let us know if this happens in a real device.

Cheers,
Maomao
