### ISSUE TITLE
DataGrid add Backend Filtering / Sorting support

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#784]
Hello,

I have had a look on `datagrid` and sorting with pagination happens in UI only, so it works only if Backend returns all the data to the Frontend in one call.

This is not possible in some cases when there is a lot of data and pagination with sorting should be a Backend task realized e.g. by additional query parameters on API call: `https://FQDN/api?page=1&limit=20`.

Is there is a way to realize such kind of use case with `datagrid` and backend sorting + pagination? Or could you please add this option?

Cheers,
Georgiy

**Comment by acstll** [comment]
Hey @GAS85,

an option would be to handle the pagination independently from the Data Grid, using the Pagination component.

For handling sorting, we don't have an ideal workaround but I added some code in [this example snippet here](https://github.com/telekom/scale/issues/811#issuecomment-1024327901), that shows how to get the sorting information, so you could sort also on the server call and re-render the data. I hope that is useful.

It's true that the Data Grid is "client-side" only. This is a trade-off we made while designing the component to make remove complexity from a first iteration. Your feedback is very valuable to get us thinking about making it more "backend friendly".
