### ISSUE TITLE
Autocomplete component and flyout menu usage

### ISSUE THREAD

**Issue by rriedeltsi** [telekom/scale#785]
Hi folks,

we're trying to build a autocomplete component like the [Material Autocomplete](https://material.angular.io/components/autocomplete/examples), as a combination of a text input and a result list:

![autocomplete](https://user-images.githubusercontent.com/96128057/149128422-1482fee3-4a46-4d03-b42c-7d2ad806b6f0.png)

For the result list, the scale FlyoutMenu seems an appropriate candidate, but we need to 

- trigger it manually (depending on the result of some search function which takes the user input and returns a list of matching records)
- place and size it so it sits just below the text input and has the same width
- limit the number of items in the menu / give it  a fixed height, and make the content scrollable (if the result size exceeds the space available)

Do you think this is achievable with the FlyoutMenu?

If not, I'd like to request the Autocomplete a a new feature.

Regards,
Ralf

**Comment by acstll** [comment]
Hello Ralf,

it's not a bad idea, it works visually, and the results in your screenshot are looking great imo.

However the semantics (as in accessibility) do not quite match. The Flyout Menu leverages the `menu` and `menuitem` roles, and an autocomplete component would need `list` and `option`.

So as a temporary solution, not final, I think it's good enough and definitely achievable. Though I would probably try something simpler with custom code only.

We do have this autocomplete feature/component in the roadmap :), so it'll be available at some point, but we don't know when exactly yet.

Thanks for the feedback and the request.

**Comment by felix-ico** [comment]
this looks similar to https://github.com/telekom/scale/issues/721
