### ISSUE TITLE
Data grid component highlight fields

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#789]
Hello all,
Is there a possibility to highlight fields in the Data grid component?
For example, we would like to implement such a case
![image](https://user-images.githubusercontent.com/4783247/149140413-44b775c1-4fca-4ba3-9198-de93553f728d.png)

**Comment by acstll** [comment]
Currently there is no way to do this. It shouldn't be too hard to enable such customisations, so we're adding this to our backlog.

We would suggest you use the Tag field type, which visually would be appropriate for this use case. Would this work for you? (There is no way either to customise the colors of the tag, which would be nice.)

**Comment by lordichek89** [comment]
Hello all,
Thanks for the reply. Not always a field should be highlighted (it depends on a logic) in our grid. Therefore we can't use tags for all cases in a field. And currently there is no way to change type depending on data in every row.
![image](https://user-images.githubusercontent.com/4783247/149462004-65819524-e4d5-4a77-a9e3-fe5f6efd634d.png)
