### ISSUE TITLE
Data Grid small headers

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#794]
Hello dear community,

Add grid to my Project and looks that Headers are somehow too small (smaller than content in Grid and everything els), got a feeling like CSS was broken, but seems this is as per design:

![grafik](https://user-images.githubusercontent.com/6813635/149473889-780e1c53-94f5-40c9-ab75-c6bab7015157.png)

Can it be adjusted somehow?

Cheers,
Georgiy.

**Comment by maomaoZH** [comment]
Hi Georgiy,

Thanks for reaching us.  The table head title has default font size 12px. If you want to style by yourself, you can inject your own styles simply by passing styles value to <scale-data-grid />. In your case, this could be something like  
![Screenshot 2022-01-18 at 13 03 10](https://user-images.githubusercontent.com/23239723/149925450-d58ead6d-d6e8-4bd2-979a-507854a52877.png)

I hope this will help you. Feel free to contact us anytime if there is something more coming up.

Cheers,
Maomao

**Comment by lordichek89** [comment]
Hello all,
But it doesn't work
I added these styles in React scale component
![image](https://user-images.githubusercontent.com/4783247/149952739-38c7b8d8-baa6-4295-9a30-85aa8a5f354e.png)
The headers have the same font size
![image](https://user-images.githubusercontent.com/4783247/149952903-492446aa-8f1c-4b87-b8b2-2bd871c9e7a4.png)

**Comment by maomaoZH** [comment]
Hi Gerogiy,

May I ask if the solution provided above work for you?

Best,
Maomao

**Comment by GAS85** [comment]
Hi Maomao,

thanks, now it looks much better:D

Cheers,
Georgiy
