### ISSUE TITLE
Data Grid Options - overlap

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#795]
Hello dear community,

Using Data Grid with Options and seems it has a bug. When user open `Sort By` and then `Toggle View` it will overlap one on other.
To get rid of it user needs to "catch" `Sort By` field and click on it.
![grafik](https://user-images.githubusercontent.com/6813635/149474168-a06cbdd7-975d-4b31-ba90-d83d8f83539a.png)

Cheers,
Georgiy

**Comment by maomaoZH** [comment]
Hi Georgiy,

Thanks for reporting this issue. We will have a look and fix it as soon as possible. 

Cheers,
Maomao
