### ISSUE TITLE
Header, main navigation, user navigation

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#799]
Hello all,
I am implementing a small Vue application.
I can't render the Header component, get the mistake when i try to pass an array (main navigation or user navigation) in scale-app-header. What am i doing wrong?
![image](https://user-images.githubusercontent.com/4783247/149793718-609f344a-3cdf-4612-93ab-33770fa1b6f7.png)
![image](https://user-images.githubusercontent.com/4783247/149793544-7ff47e8e-cad1-44be-8450-c8e204cd5eb7.png)

**Comment by reed665** [comment]
faced the same issue, just copied and pasted `userNavigation` prop value from the documentation

```js
const userNavigation = [{
      type: 'userInfo', shortName: 'Alexander', name: 'Alexander Dreyer', email: 'alexander.dreyer@t-online.de',
    }, { type: 'divider' }, {
      type: 'item', name: 'Customer Care', id: 'customer-care', href: 'https://www.telekom.de/kundencenter/startseite', icon: 't-product-measure-internet-speed', iconPosition: 'prefix',
    }, {
      type: 'item', name: 'Login Settings', id: 'login-settings', href: 'https://account.idm.telekom.com/account-manager/index.xhtml', icon: 'service-settings', iconPosition: 'prefix',
    }, { type: 'divider' }, {
      type: 'item', name: 'Optional Link', id: 'optional-link', href: '#optional-link',
    }, { type: 'divider' }, {
      type: 'button', name: 'Logout', id: 'logout', href: 'https://accounts.login.idm.telekom.com/sessionmessage/logout', variant: 'secondary',
    }];
```

**Comment by nowseemee** [comment]
Hi folks, thanks for opening this issue.

Unfortunately, passing non-primitive values to a custom element via its attribute will not work. What you can do instead is to assign the configuration directly to the element's appropriate property. Here is an example:

![image](https://user-images.githubusercontent.com/4532334/149955668-abda7801-5639-4b61-a1fd-36a591d86eef.png)

I hope this will work for your use cases. Let me know. Many thanks.

**Comment by lordichek89** [comment]
Hello all,
Thanks for the reply.
Seems it works.

**Comment by reed665** [comment]
I also checked Vue 3 docs and I found that there is `.prop` modified for such a case, but somehow it doesn't work in this case. not sure why 🤔 
https://v3.vuejs.org/guide/web-components.html#passing-dom-properties

```vue
<template>
  <scale-app-header :user-navigation.prop="userNavigation" />
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  setup() {
    const userNavigation = [
      {
        type: 'userInfo', shortName: 'Alexander', name: 'Alexander Dreyer', email: 'alexander.dreyer@t-online.de',
      },
    ]
    
    return {
      userNavigation
    }
  }
})
</script>
```
