### ISSUE TITLE
Data Grid add E-Mail Type

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#801]
Hello dear Community,

using Data Grit meet one problem, I need to add E-Mails, that are in a best way clickable.

I try to set type to link, but in this case it does not work, and ether Frontend or Backend needs to modify values from `max.musterman@some.domain` to `mailto:max.musterman@some.domain`.
Unfortunately in this case it will be also written as is:
![grafik](https://user-images.githubusercontent.com/6813635/149951569-da3a34cf-aa1a-48f9-920a-703b3c336d3e.png)

Could you please add type `E-Mail` to the data grid, so that I do not need to modify data and do not have `mailto:` prefix in UI?

Cheers,
Georgiy

**Comment by maomaoZH** [comment]
Hi Georgiy,

Thanks for reaching us! It is a good idea to add email data type. We will get back to you as soon as possible.

Best,
Maomao
