### ISSUE TITLE
Radio Button has blue circle when in focus 

### ISSUE THREAD

**Issue by telion2** [telekom/scale#802]
https://www.brand-design.telekom.com/scale/?path=/story/components-radio-button--standard&globals=locale:de

When clicking on the Radiobutton it shows a blue circle as a border. (it disappears when clicking elsewhere) 
(Tested with Firefox & Chrome)  

I know its rather intuitive and a subjective opinion, and I couldn't find a guideline to this specific case in Brand Design, 
but my immediate reaction was rather negative. 
But maybe that is just me. 

I think the contrast between the colours is too strong and/or the border has a solid colour instead of a shadow effect or something like that. 
Maybe use another colour or another effect? E.g. black or no Effect? Or Shadows?

**Comment by acstll** [comment]
Hey @telion2, thanks for asking.

The blue circle represents the focus state. It's an [accessibility requirement to make it obvious and visible for people with low vision](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus#accessibility_concerns).

We use the same blue tone for the focus state across all components that are focusable.

If you really wanted to customise that, for the radio button there is a `--box-shadow-control-focus` CSS variable that should be useful. Other focusable elements should have a similar variable (but there might be inconsistencies, we're working on those).

**Comment by telion2** [comment]
You are right that the user should be able to see that the radio button is in a state of focus. 

I looked up vuetify and PrimeVue checkboxes that I think look great. 

I think PrimeVue nails it:
https://primefaces.org/primevue/showcase/#/checkbox

Vuetify has no focus state though, but if you reuse and adapt the hover effect, I reckon that it would look great. 
https://vuetifyjs.com/en/components/checkboxes/

**Comment by acstll** [comment]
Thank you for your feedback 🙏
