### ISSUE TITLE
Inconsistent "getting started" documentation

### ISSUE THREAD

**Issue by defaude** [telekom/scale#803]
The code snippet for the custom element loader on https://github.com/telekom/scale#setup-with-a-bundler-or-es-modules looks like this:

```js
applyPolyfills().then(() => {
  defineCustomElements(window)
})
```

However, the documentation on https://www.brand-design.telekom.com/scale/?path=/story/scale-for-developers-scale-and-react--page&globals=locale:en simply states:

```js
defineCustomElements();
```

Both seem to work, but which one is the "correct" and most recent one?

**Comment by defaude** [comment]
➡️  see https://github.com/defaude/scale-reactivity for an example where this happens. Just `npm install && npm start`.

(I'm using node v16.13.2 and npm 8.1.2)

**Comment by christopherGdynia** [comment]
Hello @defaude,

```applyPolyfills``` is used for Browser compatibility and backwards compatibility, [see](https://stenciljs.com/docs/browser-support).

```defineCustomeElements``` will register the ScaleComponents to use it in html.

If you want to support older Browserversions or multiple Browsertypes use ```applyPolyfills```

**Comment by defaude** [comment]
Alrighty, thanks!
