### ISSUE TITLE
Feature Request: Option to choose location of icon in Accordion

### ISSUE THREAD

**Issue by Lalaluka** [telekom/scale#806]
Currently, the only possible position of the Icon on the Collapsibles is left. In some designs, a location on the right would be more convenient. for example like this (ignore the borders):
<img width="382" alt="Bildschirmfoto 2022-01-20 um 19 13 34" src="https://user-images.githubusercontent.com/26364692/150397294-1516f566-6e4c-4eaa-a4f7-18ac441082f5.png">

Could such a new attribute be supported? For example called `iconLocation`?

**Comment by maomaoZH** [comment]
Dear @Lalaluka 

Thanks for reaching us. It is a good idea to give user a flexibility to choose. We will get back to you asap. 

Cheers,
Maomao

**Comment by Lalaluka** [comment]
Any news on this? 

If you currently don't have the capabilities to develop the feature I could write a PR myself.

**Comment by maomaoZH** [comment]
Hi @Lalaluka,  we are currently indeed a bit overloaded. Please feel free to create a PR. We will be very happy to review it.

**Comment by Lalaluka** [comment]
Hi @maomaoZH 
I created #863 :)

**Comment by Lalaluka** [comment]
Hi @maomaoZH,
could you take a look at the PR? I kind of bricked my fork 😅 So merging it would enable me to renew my fork

**Comment by maomaoZH** [comment]
@Lalaluka The new release `3.0.0-beta.51` is done. This includes your PR. Thanks again for your contribution!
