### ISSUE TITLE
Bug: Weird ScaleCheckbox behavior

### ISSUE THREAD

**Issue by defaude** [telekom/scale#809]
When a bunch of `ScaleCheckbox` is rendered to the page and all of them are given `undefined` as value for their `disabled` props, the very first click on one of the checkboxes triggers **weird** behavior affecting all of them at once.

You can see an example [here](https://codesandbox.io/s/flamboyant-booth-k12s0)

The typings allow `undefined` as proper value for the `disabled` attribute, though: https://unpkg.com/browse/@telekom/scale-components@3.0.0-beta.43/dist/types/components.d.ts (line 9473). I think this is meant to say that the `disabled` attribute is optional, not necessarily that you can **pass** `undefined` as value. Nevertheless, the logic receiving the attributes seems to break somehow in that case, causing the strange behavior.

**Comment by maomaoZH** [comment]
Dear @defaude , 

Thanks for reporting this issue. We will have a look and get back to you soon! 

Regards.
Maomao

**Comment by maomaoZH** [comment]
Dear @defaude , 

Thanks for reporting this issue. We will have a look and get back to you soon! 

Regards,
Maomao

**Comment by acstll** [comment]
A release will be out with a fix that might resolve this one (see #817)

**Comment by acstll** [comment]
This is fixed in the latest release (`3.0.0-beta.46`) 🎉
