### ISSUE TITLE
Data grid Fields and Rows

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#812]
Hello all,
How can i hide any field in the component?
For example here, i shouldn't display ID. But ID need when i will be select rows.
![image](https://user-images.githubusercontent.com/4783247/151126262-dd3e437a-87f3-4960-a264-1ea5f347cb71.png)

**Comment by reed665** [comment]
Hi!
Did you try to add `visible: false` to your field?

**Comment by lordichek89** [comment]
Hi,
Thanks! it really works. Although the documentation for the component doens't contain the property.
