### ISSUE TITLE
Scale & React without wrapper

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#815]
Hello there,

I have beed trying to set up Scale & React without the wrapper package.

Listening to events is a bit different, but it's usable, I will share my experience later.

But, ScaleAppHeader isn't working at all.
Not even the german claim is shown.
trying to use different casings (dashcase and lowercase) didn't work.
JSON.stringify on mainNavigation didn't work.

```tsx
   <scale-app-header
          activeRouteId={getActiveRoute()}
          logoTitle="Zur Startseite"
          logo-href="/"
          mainNavigation={mainNavigation}
          claimLang={'de'}
          slot={'header'}
        >
```

rendered in html
```html
<scale-app-header activerouteid="home" logotitle="Zur Startseite" logohref="/" mainnavigation="[object Object],[object Object]" claimlang="de" slot="header" class="hydrated">
```

**Comment by christopherGdynia** [comment]
Webcomponent scale button in React does download the html
I am using beta 23 for both.
Throws lesse erros then the newer version.
```tsx
<ScaleButton href="https://my.url" target="_blank" > This button works as expected </ScaleButton>
<scale-button href="https://my.url" target="_blank"> This button is downloading the page</scale-button>

```

**Comment by acstll** [comment]
@christopherGdynia I'm closing this. But please feel free to keep sharing any findings. Always appreciated.
