### ISSUE TITLE
footer and logo are not displayed on plain html file

### ISSUE THREAD

**Issue by joawin** [telekom/scale#816]
Hi,
i have used your vanilla example but I seems that `<scale-app-footer>` and `<scale-logo>` are not working.
I used example html file and added them but nothing is visible on the website.

`

```
<body>
    <div class="container">
      <h1>Scale + Vanilla</h1>
      <scale-button
        href="https://www.brand-design.telekom.com/en/account/login/?redirect_url=/scale/"
        >Open the docs</scale-button>
      <scale-button></scale-button>
      <scale-logo size="100"></scale-logo>

      <scale-app-footer variant="standard" claim-lang="en"></scale-app-footer>
    </div>
  </body>

```

`

**Comment by maomaoZH** [comment]
Dear @joawin, thanks for reaching us. Perhaps you have done this, but I just want to double check to exclude the possibility. Have you successfully installed the package and include them in your html file?  
`<link rel="stylesheet" href="node_modules/@telekom/scale-components/dist/scale-components/scale-components.css"/>`
`<script type="module" src="node_modules/@telekom/scale-components/dist/scale-components/scalecomponents.esm.js"></script>`

**Comment by joawin** [comment]
Hi @maomaoZH ,
yes i have installed the package and included it in my html file.
I did the following steps

- Clone the repository and got to the examples/vanilla folder
- run `npm install`
- run 'npm run start' and try to add `<scale-app-footer>`

The files are already included in the example index.html

**Comment by maomaoZH** [comment]
Hi @joawin,
sorry I misunderstood your issue. From the project example folder, the `scale-components-neutural` is installed. In this library, the components `scale-logo`, `scale-header`, `scale-footer` are excluded.  In addition, the design tokens are different. If you want to try out with other components, it should work. For example, `scale-card`, or `scale-date-picker`, ect. 
Another tip I could suggest is: 1 install `@telekom/scale-components`  and update the link path in the html file `<link rel="stylesheet" href="node_modules/@telekom/scale-components/dist/scale-components/scale-components.css"/>`
`<script type="module" src="node_modules/@telekom/scale-components/dist/scale-components/scalecomponents.esm.js"></script>`, then you should be able to check the `scale-logo` or `scale-footer` components. 
Should you have more questions, feel free to contact us anytime.
Cheers!

Maomao

**Comment by joawin** [comment]
Hi @maomaoZH ,
now it looks quite better. 
Thank you
