### ISSUE TITLE
React - ScaleCheckbox: disabled triggers onScaleChange 

### ISSUE THREAD

**Issue by ChristianAtWork** [telekom/scale#817]
we have a `ScaleCheckbox` that gets `disabled` after click. 
we do a request and enable the checkbox when we get the response.
the seconed time we switch disabled state,  `onScaleChange` is called and unchecks the `ScaleCheckbox`

with `onChange` it works

im not a stencil expert, but could the `emitEvent` in `handleDisabledChange` be the Problem?

https://github.com/telekom/scale/blob/8545c211438ee21d89191181ab8314bec7eeaf8f/packages/components/src/components/checkbox/checkbox.tsx#L88-L93

**Comment by acstll** [comment]
@ChristianAtWork a release will be out soon with the fix. Thanks for the feedback!

**Comment by nowseemee** [comment]
3.0.0-beta.45 is published - many thanks for making this happen!

**Comment by ChristianAtWork** [comment]
thx for the fast reaction :D
