### ISSUE TITLE
Tooltips does not overlay elements

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#818]
Hi there,

it seems the Tooltip doesnt overlay elements in a page. Sometimes the label/fields are showing and the tooltip is underneath.
Also there are some issues when the tooltip is on an edge of a site. This behavior differs in different browsers..

I made a small example of this... https://codesandbox.io/s/tooltip-y4y5k

Greetings,

**Comment by Lalaluka** [comment]
Took a look.
The z-index seems to never be applied.
https://github.com/telekom/scale/blob/8545c211438ee21d89191181ab8314bec7eeaf8f/packages/components/src/components/tooltip/tooltip.css#L32

Adding the z-index manually to the shadow dom seems to fix it.
I might try to write a fix later :)

**Comment by Lalaluka** [comment]
Fixing it is pretty trivial (just one line of CSS) see: #821

**Comment by maomaoZH** [comment]
Dear @tommy-codez,  Thanks for reporting this issue. 
@Lalaluka Thanks for the fix!

**Comment by nowseemee** [comment]
Meanwhile, this patch got published: `3.0.0-beta.46` - Huge thanks to @Lalaluka!!! 🚀
