### ISSUE TITLE
Data grid removing selected rows

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#823]
Hello all,
I am using the component Data grid with pagination
When i remove rows from second page, i face with the issue, the pagination disappears

https://user-images.githubusercontent.com/4783247/151753892-ecb63aa3-ab76-4860-8b31-a5f11c9a676d.mp4

**Comment by nowseemee** [comment]
hi @lordichek89, thanks for opening this issue. The patch ☝🏻 got merged and published: `3.0.0-beta.44`.

**Comment by lordichek89** [comment]
Hi all,
Currently it works properly. 
Thanks for the quick fix!
