### ISSUE TITLE
Data grid - SyntaxError (React)

### ISSUE THREAD

**Issue by vissarionas** [telekom/scale#824]
Hello people!

We have a bunch of `SyntaxError: Unexpected token ... in JSON at position ...` with the following peace of code in our react application:
```
<ScaleDataGrid
  fields={[
    { type: 'number', label: 'id' },
    { type: 'number', label: 'age' },
  ]}
  rows={[
    [1821, 24],
    [1940, 34],
  ]}
/>
```

BTW, there is this `Beta Component` tag at the top of the docs page, but the component is not listed in the `Beta Components` on the sidenav.

**Comment by nowseemee** [comment]
Hi @vissarionas, thanks for your message. I've changed the beta badge to the proper AA (https://github.com/telekom/scale/pull/832/commits/baa365cc6ec208f93bfe1524438802441848bd4f), however, I had difficulties reproducing the SyntaxError - could you please tell me more about your setup, perhaps posting a reproduction code sandbox? Thanks!

**Comment by vissarionas** [comment]
I have a hard time finding an online sandbox to demonstrate it, but here is a screenshot of my localhost experiment:
![Screenshot from 2022-02-01 14-57-09](https://user-images.githubusercontent.com/11361429/151972769-a89f60ee-7c2d-48f9-8f32-a3091ca32502.png)

**Comment by nikolab-pn** [comment]
I think this happend when rows property is updated using hooks

Sandbox: https://codesandbox.io/s/strange-morse-glzgt?file=/src/App.js

**Comment by vissarionas** [comment]
Thanks for the sandbox. I couldn't make it for some reason.
If you tweak it by providing hardcoded rows in the `rows` prop (instead of the state ones), you still see those errors just because the state of the component is updated (when `setRows` is called).
