### ISSUE TITLE
scale-dropdown with scale-modal behaviour

### ISSUE THREAD

**Issue by DeJacobb** [telekom/scale#826]
When opening a link to another view in my gui the dropdown menu inside a scale-modal breaks like this:
![image](https://user-images.githubusercontent.com/98537062/151786554-e99ea25c-e8aa-42c4-a7c3-6d7ac00c0bbc.png)

This can be fixed by reloading the site, but it breaks again, when routing to another site and opening the modal.

Is this a bug or am I using the components wrong?

**Comment by acstll** [comment]
@DeJacobb sorry for the super-late reply, we totally missed this one.

Are you still having the issue? This looks like a known issue with the Dropdown.

(A new version of the Dropdown with a custom flyout is in the works, so this issue won't exist.)

**Comment by acstll** [comment]
Closing this while waiting for the new beta Dropdown to be out very soon, please re-open or get in touch if not. Thanks again!
