### ISSUE TITLE
Add possibility to add CSS to tooltip

### ISSUE THREAD

**Issue by H4CK3R-01** [telekom/scale#837]
Hi,
is it possible to add a styles property to the tooltip element?
Currently I'm using JavaScript to set the width of .slot-container to 100%. But it would be better to doe this directly with some CSS.

What I am currently using:
`document.querySelector('#scale-tooltip-1').shadowRoot.querySelector('.slot-container').setAttribute('style', 'width:100%');`

**Comment by acstll** [comment]
Hi @H4CK3R-01 

not currently, but we could definitely allow this. We'll add the corresponding `part` attribute to this element, and could also add a CSS variable.

(Thanks for sharing the workaround, as it was easy for me to spot the relevant bits in the code.)

**Comment by nowseemee** [comment]
Hey all, thanks for the valuable discussion. A rewrite of the tooltip component utilizing `floating-ui` instead of `popperjs` has been published (3.0.0-beta.108) and hopefully solves this issue. Feel free to reopen in case something is still not right.
