### ISSUE TITLE
Sidebar navigation collapsible is missing icon when not focused or hovered

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#838]
Hello there,

I'd like to report issue with Sidebar Navigation.
The sidebar navigation collapsible icon on the items containing other items is visible only if it has focus or hover, but otherwise it disappears.

Maybe this is by design, but in our use case we want to display the fact that the item contains other items even if it is not focused or hovered. So at least some prop should be added so it is possible to configure this behavior.

With focus/hover:
![image](https://user-images.githubusercontent.com/49948501/152146238-392cfbd9-c8c3-4fc1-b8f4-6627b8b0ec2d.png)

Without focus/hover:
![image](https://user-images.githubusercontent.com/49948501/152146293-e82cb50e-4a15-4473-ab84-b5d53330ffea.png)

**Comment by nowseemee** [comment]
Hiiii @mato-a, this should be fixed in `3.0.0-beta.46`. Thanks for getting in touch!
