### ISSUE TITLE
Accessibility issue with the scale-modal

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#842]
Hey,

When I operate my application with the keyboard and open a scale-modal by pressing the Enter key and then close it again, the focus does not go back to the initial element.  This behavior has been criticized by our accessibility reviewer.
Is there a way to customize this behavior for this?

We use Scale together with Vue 2. When clicking on a scale-button the @click event sets the variable "opened" to "true" and passes it to the modal as prop.

**Comment by Lalaluka** [comment]
You can set the focus in your application through Vue.js I don't think it's possible to do so in the modal code:
`this.$refs.yourModalOpeningElement.$el.focus()`

You could execute this for example on the @scaleClose event.

**Comment by tomkroschwald** [comment]
Ok I'll try that! thanks for the idea
