### ISSUE TITLE
DataGrid - pagination and sort

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#845]
Hi,

We are using DataGrid to diplay data, in one part of application backend is returning paginated data due to amount of data. Would it be possible to add props for pagination where se cound manually set number of elements and what page is displayed? Also how would you go about sorting if it is also done on backend?

We could use Table and but we are using DataGrid on in other places and they have different design.

**Comment by acstll** [comment]
Hey @nikolab-pn, thanks for asking.

The Data Grid has this limitation currently of not being too "backend friendly" (it's in our roadmap to improve this). So working with pagination/sorting from the backend is difficult thou not impossible.

You have to use the pagination separately, with the Pagination component (the same way you would with the Table). And for sorting, there's a workaround I suggested recently. Where you use the settings from the `sortable` feature (which works only client-side) to refetch the data from the server and update the Data Grid, please check out the snippet here: https://github.com/telekom/scale/issues/811#issuecomment-1024327901 and also the comment here https://github.com/telekom/scale/issues/784#issuecomment-1024339024

I hope this helps, I'm closing this issue but we can keep the conversation going if you need further support 🙂
