### ISSUE TITLE
Datagrid HTML Cell with Vue 3 and Single SPA not working

### ISSUE THREAD

**Issue by dshrd** [telekom/scale#848]
Hi guys,

we are running our application as a micro-frontend-architecture with Vue3 and Single SPA. The Scale version is `^3.0.0-beta.43`.
I've tried to implement a very basic Datagrid with one HTML cell and I'm getting the following error in the console:
![grafik](https://user-images.githubusercontent.com/95762437/152532478-109cbad3-9d9f-483a-93c2-87e87382fd7c.png)

If I remove the HTML cell everything just works fine. Any ideas what could cause this issue?

Best Regards,
Daniela

**Comment by acstll** [comment]
Hello Daniela 👋 

I'm thinking something could be wrong in the data you're passing to the component, but it could also be a bug…

Could you please share a snippet of the code of your data grid?

Thanks in advance!

**Comment by dshrd** [comment]
Hi Arturo,

sure, here's one snippet I've tested:
App.vue
```
<template>
  <scale-data-grid heading="Suchergebnisse" id="example"></scale-data-grid>
</template>

<script>
export default {
  name: "OrganisationList",
  mounted() {
    const dataGrid = document.querySelector("#example");
    dataGrid.fields = [
      {
        type: "text",
        label: "Name",
        sortable: true,
      },
      {
        type: "text",
        label: "Straße",
        sortable: true,
      },
      {
        type: "number",
        label: "PLZ",
        sortable: true,
      },
      {
        type: "text",
        label: "Ort",
        sortable: true,
      },
      {
        type: "text",
        label: "Status",
        sortable: true,
      },
      {
        type: "html",
        label: "HTML",
        sortable: false,
      },
    ];
    dataGrid.rows = [
      [
        "name",
        "straße",
        12345,
        "ort",
        "status",
        "<p>test</p>",
      ],
    ];
  },
};
</script>
```
I've tried some plain text in the HTML cell as well as provided example with `document.createElement('scale-icon-service-support')`

**Comment by maomaoZH** [comment]
Hi @dshrd,

Thanks for providing the code sample. HTML cell accepts only HTML element. The code above `<p>test</p>` will be treated as string. Therefore it complains "TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'". In your case, if you want to append a `<p>` tag, for example, you could write  as `document.createElement("p").appendChild(document.createTextNode("this is a test"))`, then you will have the html tag displayed in the dom. 
![Screenshot 2022-02-10 at 10 09 28](https://user-images.githubusercontent.com/23239723/153366562-7af831f9-e71a-434c-a14a-fc540db124e8.png)
Please let us know if there is further issues!

Cheers,
Maomao

**Comment by dshrd** [comment]
Hi @maomaoZH ,

as I said I've tried `document.create` as example in the documentation and it isn't working. Just now I've tried the code snippet you shared. Still the same problem.

**Comment by maomaoZH** [comment]
Hi, @dshrd  may I ask do you still have the same TypeError message? Please note: that in the HTML cell, you need to click the expand icon in order to see your html document.

**Comment by dshrd** [comment]
Still the same error
![grafik](https://user-images.githubusercontent.com/95762437/153381081-c694e443-56fa-4173-bce8-65c2b525ae0b.png)

and nothing in the Datagrid
![grafik](https://user-images.githubusercontent.com/95762437/153380930-794ff484-e27e-4d71-8c2b-4acb8721211a.png)

**Comment by maomaoZH** [comment]
Hi, @dshrd thanks for the quick feedback. We will invest this issue and come back to you asap.

**Comment by dshrd** [comment]
Hi @acstll, @maomaoZH,

any updates so far?

**Comment by maomaoZH** [comment]
Hi @dshrd , we are currently a bit overloaded. I am afraid this issue is still in progress.

**Comment by maomaoZH** [comment]
Dear @dshrd  I apologise again for the delay. Would you please install the latest scale library and have a look again. We tested from our side, the html tag works in both Vue3 and React. This is the sand box https://codesandbox.io/s/epic-hofstadter-uvw5c0?file=/src/App.vue Please let us know if you still have issues.

**Comment by dshrd** [comment]
Hi @maomaoZH ,

I've update the Scale-components to the latest version and the bug is still there.
So I removed the HTML Cell to check if the error was caused by something else. As I did so, I noticed that the data grid cell's width is constantly growing which I suppose is not intended to happen. I don't know is these two issues are related, I just wanted to mention it.

Best Regards

**Comment by maomaoZH** [comment]
Hi @dshrd,
Do you mind creating a sandbox to show your bug/issue you mentioned above?  By the way, may i ask which OS and browser are you using ? This may help us to invest the issue better. 

Thanks!
Maomao

**Comment by maomaoZH** [comment]
We have tested this issue with different scenarios  like vue3, react and vanilla js. The issue is not reproducible anymore. If you still encounter the issue, we would love to support you. Please feel free to re-open it. If possible , creating a sandbox would help us a lot to invest the problem. ❤️
