### ISSUE TITLE
Date Picker styles

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#853]
Hello all,
Is there any possibility to change styles for the Date Picker component?
I don't see such the case in the documentation. And now i get not the needed scroll.
![image](https://user-images.githubusercontent.com/4783247/152793110-05e71171-b6c4-4556-827b-8c9163a4c080.png)

**Comment by nowseemee** [comment]
Hi @lordichek89, this issue came up before - the solution was to wrap the modal contents into a Card with some special styles. Have a look and let me know if this helps: https://github.com/telekom/scale/issues/592

**Comment by nowseemee** [comment]
Can you try this?
```
.duet-date__dialog-content {
  position: absolute;
  left: 50%;
  transform: translate(-50%, -80%);
}
```
from https://github.com/telekom/scale/issues/539

**Comment by lordichek89** [comment]
Hello all,
applied above styles, the component moves.
![image](https://user-images.githubusercontent.com/4783247/153425326-1d4e2c91-cc93-4597-a1fb-d1f416eb642c.png)

**Comment by lordichek89** [comment]
After applying the above styles UI looks not good. I applied another styles and after added overflow: hidden for the modal window. And now it's ok.  So we have an opportunity add styles for the component Date Picker, don't we? That was my initial question, because the current documentation doesn't have the prop "styles".

**Comment by felix-ico** [comment]
Hi @lordichek89, thanks for the input, we added the styles to the storybook documentation https://github.com/telekom/scale/commit/fd48fb1b1d72746f3332f52a739e462cc2dacd32
