### ISSUE TITLE
Form submit not triggered on enter

### ISSUE THREAD

**Issue by pomoalex** [telekom/scale#859]
In a form that contains multiple scale-text-field ans a scale-button of type submit, hitting enter in any of the inputs does not trigger the submit of the form as it should be.

**Comment by nowseemee** [comment]
Hi @pomoalex, thanks for opening this issue. This is a super unfortunate limitation of web components using Shadow DOM. Sadly we can only offer a workaround for this explained in this issue: https://github.com/telekom/scale/issues/404 Let me know if it helps.

**Comment by acstll** [comment]
The Text Field and similar input components are not using Shadow DOM anymore. And the Button has a "fix" for this. I thought this would work… 🤔 @pomoalex would you be so kind and share a snippet (or a live example) of your form?

**Comment by pomoalex** [comment]
The form I have looks like this: 
```
<form action="..." method="post" autocomplete="off" novalidate="novalidate">
    
    <div class="scl-input-with-button">
        <scale-text-field input-id="cardNumber" name="cardNumber" type="tel" label="Servicekartennummer*" value="992003020632539" max-length="15" required="" class="hydrated">...</scale-text-field>
        <button class="button-with-icon" type="button">
            <scale-icon-alert-help accessibility-title="help" fill="var(--icon-color)" class="selectable hydrated" size="22" style="display: inline-flex;">...</scale-icon-alert-help>
        </button>
    </div>

    <scale-text-field input-id="cardPin" name="cardPin" type="password" label="PIN*" max-length="5" required="" class="hydrated">...</scale-text-field>

    <div class="button-bar vertical-spacing--32">
        <scale-button variant="primary" type="submit" icon-position="before" class="hydrated">
            <scale-icon-content-lock accessibility-title="lock" size="21" class="hydrated" style="display: inline-flex;">...</scale-icon-content-lock>
            Jetzt bezahlen
        </scale-button>
        <scale-button variant="secondary" type="button" href=".../cancel" icon-position="before" class="hydrated">Zurück</scale-button>
    </div>
</form>
```

I have to mention that the submit triggers when I only have one input, but no longer works when multiple ones are prent.

**Comment by acstll** [comment]
@pomoalex do you still have this issue? I can take a look…

**Comment by nikolab-pn** [comment]
Hi @acstll,

I can confirm that this is still the issue, form subimt is not working when there is more than 1 input field. As a workaround it is possible to add <input type="submit" hidden /> and than submit is triggering with enter key.

Here is example in react: https://codesandbox.io/s/submit-button-multi-input-8g28g6?file=/src/App.js

**Comment by acstll** [comment]
Hey @nikolab-pn — thanks again for replying so quickly.

I found out forms will get submitted when they have a single `input[type=text]` by design, even if there's no button or `input[type=submit]` in the form. See https://stackoverflow.com/a/35235768 (`scale-button` does not count as a button because the actual <button> is in the Shadow DOM).

There's a PR (#1120) with a "fix", based on the `input[type=submit][hidden]` technique found in [your sandbox](https://codesandbox.io/s/submit-button-multi-input-8g28g6?file=/src/App.js). It basically adds this element to the form if appropriate.

Do you think the solution is too "invasive" and you'd rather add the `<input type="submit" hidden>` yourself?

**Comment by nikolab-pn** [comment]
Solution sounds good to me. Thanks for quick fix.

btw. is there a plan to add some kind of changelog to releases so that it's more visible when something is fixed?

**Comment by acstll** [comment]
> Solution sounds good to me. Thanks for quick fix.
👍

There is one here: https://github.com/telekom/scale/blob/main/CHANGELOG.md 🙂

**Comment by nikolab-pn** [comment]
Sry, didn't see that one :man_facepalming:. I was looking under Releases section. This is great, thank you.
