### ISSUE TITLE
Add Time Picker Element or expand Date Picker with Time

### ISSUE THREAD

**Issue by GAS85** [telekom/scale#860]
Hello Dear community,

I need to create element where user can select **date** and **time**, with date it is simple - use Date Picker, but I could not find anything related to the Time selection. Is there any element already planned? Or as expanded bar to the Date Picker?

Cheers!

**Comment by ledex** [comment]
Hi! Are there any news regarding the DateTimePicker? 

Cheers :)

**Comment by nowseemee** [comment]
Hi Karsten @ledex, thanks a lot for bumping this topic, it’s definitely not forgotten from our side. Unfortunately, we cannot provide any dates yet — many thanks for the patience!
