### ISSUE TITLE
Data grid stretches to an infinity in Firefox 

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#861]
Hello all,
I faced with a strange display the data-grid in Firefox (version 97.0).  The component stretches.
Attach the component from your documentation.
Firefox:
![image](https://user-images.githubusercontent.com/4783247/153178661-9964a6e2-ecdc-48fd-be2b-2b28a576e492.png)

In Chrome the same data grid looks good:
![image](https://user-images.githubusercontent.com/4783247/153178771-d03e420d-3107-4394-a3e9-cff8a158a77b.png)

**Comment by nowseemee** [comment]
Hi @lordichek89, I can confirm this is a problem with the latest version of Firefox - will take a closer look and come back to you. Thanks for letting us know!

**Comment by lordichek89** [comment]
Hello all,
Is there any news about the bug?

**Comment by maomaoZH** [comment]
Hi @lordichek89, We have checked this issue internally and we could not re-produce this anymore. Could you please update your Firefox and check it again?

**Comment by lordichek89** [comment]
@maomaoZH in which version do you check the bug?

**Comment by maomaoZH** [comment]
I have the same Firefox version 97.0.1 and test the latest scale version 3.0.0-beta.52.

**Comment by lordichek89** [comment]
@maomaoZH these images from your documentation. In my project i use scale version 3.0.0-beta.44 and the same issue.

**Comment by lordichek89** [comment]
@maomaoZH 
Updated scale, nothing changed. Yes, i work on Windows machine
![image](https://user-images.githubusercontent.com/4783247/156734614-e233f16b-7199-4d16-aca3-a3d91a612492.png)
![image](https://user-images.githubusercontent.com/4783247/156734532-f444e475-d3db-41a0-aca7-7249e1dcf43e.png)

**Comment by nowseemee** [comment]
Hi @lordichek89, this bug should be hopefully fixed with the latest version: `3.0.0-beta.53`. Thanks for reporting!

**Comment by lordichek89** [comment]
Hi @nowseemee, 
are you sure that now it works?
![image](https://user-images.githubusercontent.com/4783247/158529235-9532d359-16cb-4f46-8aee-a48e1ed30b95.png)
![image](https://user-images.githubusercontent.com/4783247/158529303-61f839de-aec9-4958-85c9-d55d9fcfcdc4.png)
![image](https://user-images.githubusercontent.com/4783247/158529376-749dfc23-4172-41f0-bd7c-3336ba4481c2.png)

**Comment by GAS85** [comment]
Ubuntu with FF 98 has the same issue.

**Comment by lippielip** [comment]
@marvinLaubenstein (╯°□°）╯︵ ┻━┻
