### ISSUE TITLE
Stencil problem with the "Dropdown" component

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#867]
Status as of Aug 17, 2021
"... we have a technical update regarding the “Dropdown crashing” bug.
We have made a React-only component using the Scale design tokens for you to replace the buggy Dropdown, until we finish the refactor without rushing it. It looks and behaves exactly the same, but it’s plain React. It's in a private repo in GitHub.
... Arturo ..."
The "private" Dropdown is still in use in our application. We would like to exchange it with the "official" Scale Dropdown. Did you finish the refactor? - If not: By when could you do so?
Thanks for your help :-)

**Comment by nowseemee** [comment]
Hi @UBOrange, thanks for asking about the Dropdown. We don't have the refactored version ready yet. I'll come back to you with more exact dates soon.

**Comment by UBOrange** [comment]
Hi @nowseemee - any updates? Please see your comment above ("I'll come back to you with more exact dates soon."). Thanks a lot for your help.

**Comment by nowseemee** [comment]
Hi @UBOrange, thanks a lot for bumping this topic, it’s definitely not forgotten from our side. Unfortunately, we cannot provide any dates yet — thanks for the patience!

**Comment by UBOrange** [comment]
Hi @nowseemee, 
would it be possible to provide an updated "React-only component" (please see the very first comment of this issue) with the latest Scale design?

**Comment by acstll** [comment]
Oh, @UBOrange you mean to update the custom React-only component with the latest tokens? are you using >beta.100 already? That should be definitely possible and rather quick. Do you still have access to the private repo?

**Comment by acstll** [comment]
Oh, I see now @christopherGdynia posted the code :) (had the tab opened and didn't get that last message).

**Comment by UBOrange** [comment]
@christopherGdynia, @acstll thanks a lot for your excellent support :-)

**Comment by nowseemee** [comment]
The new `dropdown-select` is now published with `3.0.0-beta.109`. It should provide solutions to the problems we were facing with the old `dropdown` component.
https://telekom.github.io/scale/?path=/docs/beta-components-dropdown-select--standard
