### ISSUE TITLE
scale-link focus issue

### ISSUE THREAD

**Issue by peterszeles** [telekom/scale#871]
There is an accessibility issue while using the `<scale-link>`. 
When the keyboard navigation is used to navigate between items (scale-cards and scale-buttons) it does not focus on `<scale-link>`. The focus should work like on the `<scale-button>`

**Comment by nowseemee** [comment]
Hi @peterszeles, thanks for getting in touch. I've tested the link component in a few different browsers and the focus was working for me. Can you please share more details about your setup? How to reproduce this problem? Thanks!

**Comment by felix-ico** [comment]
hi @peterszeles, I've just confirmed that behavior on the latest scale version using your code snippet. Alternatively to your workaround, setting the optional attribute `inner-tabindex` seems to achieve the desired effect as well:

```
      <div>
        <button>html button</button>
        <scale-button inner-tabindex="0">1st scale button</scale-button>
        <scale-link inner-tabindex="1">scale link</scale-link>
        <scale-button inner-tabindex="2">2nd scale button</scale-button>
      </div>
```

**Comment by nowseemee** [comment]
In the above example, the href attribute is missing - that's why it's not focusable.
