### ISSUE TITLE
Sector navigation has unwanted padding

### ISSUE THREAD

**Issue by Scrumplex** [telekom/scale#872]
![Screenshot](https://user-images.githubusercontent.com/11587657/154018487-71961dec-1467-4f74-983c-72deed06257d.png)

As far as I can tell this is from the user-agent style for ul:

```
/* user agent style */
ul {
    display: block;
    list-style-type: disc;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    padding-inline-start: 40px;
}
```
Specifically `padding-inline-start`.
I can't fix this myself as I can't seem to be able to modify CSS values inside a shadow-root.

**Comment by maomaoZH** [comment]
Hi @Scrumplex, we don't apply shadom dom in this component. Would you please try to modify the class css value , eg ```.header .sector-navigation {
      padding-inline-start: 0;
    }```.
please let me know if this does not help.

cheers,
Maomao

**Comment by Scrumplex** [comment]
> we don't apply shadom dom in this component

The `scale-app-shell` has a shadow-root, which contains the `scale-app-header`. So I can't change it with a global CSS property.

See: 
![image](https://user-images.githubusercontent.com/11587657/154253127-87d29521-e83b-449a-bdec-0a78c40ad7a2.png)

**Comment by Scrumplex** [comment]
> 2 modify css via styles props which will inject your own css styles into shadow dom,  like:
> `<scale-app-shell styles=":host .header .sector-navigation { padding-inline-start: 0; }">`

this one worked!

Of course this is just a workaround and I would prefer if this was fixed here as well, so I would suggest we keep this issue open

**Comment by nowseemee** [comment]
Padding was removed on the 2nd of March 2022.
