### ISSUE TITLE
center scale-tooltip trigger

### ISSUE THREAD

**Issue by tomkroschwald** [telekom/scale#874]
Hey,
I have a problem with the scale-tooltip.

I want to use this in a `<td>`. The value should be displayed centered in the cell.
To realize this, I need to change the "width" property in the .slot-container class.
![image](https://user-images.githubusercontent.com/73475493/154492894-8a2fb807-403f-4171-bf35-d90cf0489fea.png)

However, this does not work.
![image](https://user-images.githubusercontent.com/73475493/154493242-7ff86b61-0a8e-4618-87f2-7f3ec8733f70.png)

What can I do?
Is there a possibility that a "styles" attribute is implemented with to the tooltip?

I use Scale together with Vue 2.

**Comment by nowseemee** [comment]
hi @tomkroschwald, yes we are going to add this and let you know when it's published. Thanks for making us aware of the missing "styles" feature.

**Comment by nowseemee** [comment]
Here is a workaround for the time being: https://github.com/telekom/scale/issues/837

**Comment by nowseemee** [comment]
hi @tomkroschwald, I've published this change: `3.0.0-beta.49`. Thanks for asking about it.
