### ISSUE TITLE
Footer Minimal Variant - Custom Navigation

### ISSUE THREAD

**Issue by christophstockinger** [telekom/scale#878]
I have used the Footer component in the minimal variant. In it I wanted to place a custom footer navigation over the slot. The example in Storybook shows how to place a `<span> </span>`. Das sind aber keine Menü-Links. If I then place two links in an`ul > li` pattern, both `li` tags will be placed below each other. However, if I use only two `<a>` tags they are displayed next to each other.

This seems to be a bug, that in the default variant also the `ul > li` pattern is used. Also the direct use of the original code (https://github.com/telekom/scale/blob/e46feea32044a9b626b5c67e14318410c41ba5d7/packages/components/src/components/telekom/app-footer/app-footer.tsx#L71) leads to an underlaying display.

Furthermore, using two anchor tags is also not accessibility compliant.

**Comment by nowseemee** [comment]
Hi @christophstockinger, thanks for opening this issue. The custom slots in the footer are unstyled so It's up to the consumer to add CSS. Can you try this?

**Comment by nowseemee** [comment]
Feel free to reopen whenever you cycle back to this topic.
