### ISSUE TITLE
Please update the documentation and storybook for the use of scale-grid

### ISSUE THREAD

**Issue by christophstockinger** [telekom/scale#880]
I found a component in the repo called Scale Grid. However, I can't find any documentation about it in Storybook - apart from the designer documentation.

Then in the repo I found an HTML file on how to use it. But this should be recorded directly in a README.md for developers.

https://github.com/telekom/scale/blob/e46feea32044a9b626b5c67e14318410c41ba5d7/packages/components/src/html/grid.html

**Comment by nowseemee** [comment]
Hi, please have a look here: https://www.brand-design.telekom.com/scale/?path=/docs/components-data-grid--standard

**Comment by nowseemee** [comment]
Oh, pardon, here you can find information: https://github.com/telekom/scale/pull/674
