### ISSUE TITLE
Header does not behave correctly

### ISSUE THREAD

**Issue by christophstockinger** [telekom/scale#882]
I installed the header on my project today, but it does not behave as in Storybook. However, an analysis via Devtools shows that the styles are applied as in Storybook. 

How do I get rid of the magenta area below the menu in the sticky state?

https://user-images.githubusercontent.com/24808473/154866811-549ca8c6-c072-4f32-a555-2aec6b2e6867.mov

**Comment by nowseemee** [comment]
Hi @christophstockinger, this is interesting and looks like a CSS leak to me but more information would be needed to tell - can you make a reproduction codepen, please?

**Comment by christophstockinger** [comment]
Hi @nowseemee. I created a repo because I don't use codepen and have no idea how to add telekom lib.

Have a look --> https://github.com/christophstockinger/os_telekom-scale
