### ISSUE TITLE
Neutral-Themed Checkbox does not display checkmark

### ISSUE THREAD

**Issue by Theoderich** [telekom/scale#892]
When I use the neutral theme, the checkbox component does not display a checkmark in the selected state.
The checkbox is just a solid purple when selected.

Here is a sandbox demonstrating the Problem:
[codesandbox.io](https://codesandbox.io/s/scale-neutral-checkbox-7revlu?file=/index.html)

**Comment by nowseemee** [comment]
Hi @Theoderich, many thanks for letting us know. This should be fixed in `3.0.0-beta.49`.
