### ISSUE TITLE
ScaleSlider in React broken

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#897]
@nowseemee I guess you were right.

The `ScaleSlider` is somehow broken.

It's showing `NaN`, but the `value` is a number, shown in the example.

[Sandbox](https://codesandbox.io/s/affectionate-vaughan-2fumdr?file=/index.js)

**Comment by nowseemee** [comment]
Interesting, I'll have a look.

**Comment by marvinLaubenstein** [comment]
Hi @christopherGdynia , we have tested the `ScaleSlider` in several ways. Unfortunately, we could not find any error on the `ScaleSlider` itself. We currently assume that the problem belongs to Formik.

[ScaleSlider Test Sandbox](https://codesandbox.io/s/scale-slider-react-sandbox-ld3mp2)

**Comment by christopherGdynia** [comment]
Hi @marvinLaubenstein, thanks for your help.

I've found the solution D:

```dif
const Slider = ({ label, ...props }) => {
  const [field, , helper] = useField(props);
  console.log(props, field);
  const handleChange = (e) => {
    const val = e.detail;
    if (!Number.isNaN(val)) {
      helper.setValue(val);
      if (props.onChange) {
        props.onChange(e);
      }
    }
  };
  return (
    <>
      <ScaleSlider
+     {...props}
        label={label}
        name={field.name}
        value={field.value + 0}
        onScaleChange={handleChange}
-        className={props.className}
-        disabled={props.disabled}
-        style={props.style}
-        min={props.min}
-        max={props.max}
-        step={props.step}
      />
      {field.value}
    </>
  );
};

```

**Comment by marvinLaubenstein** [comment]
Perfect :D
