### ISSUE TITLE
Scale Text field: the part of texts between the label and the top margin is visible

### ISSUE THREAD

**Issue by tetianaqaware** [telekom/scale#909]
For multi-line texts, the part of texts between the label inside of the text field and the top margin is visible

**Comment by maomaoZH** [comment]
Hi @tetianaqaware,

This issue is related to https://github.com/telekom/scale/issues/846. Soon we will do a new release which includes this fix. We will let you know when the release is done.

Regards,
Maomao

**Comment by maomaoZH** [comment]
Dear @tetianaqaware ,  We have release our version with tag @next. In this version, this issue is resolved. Please try our new package by installing `npm install @telekom/scale-components@next`.
