### ISSUE TITLE
Double scrollbar in modal

### ISSUE THREAD

**Issue by megahuut** [telekom/scale#910]
Hey there,

I have currently a bug I can´t fix by my own.

I have multiple modal windows in use which are structurally the same. But one of them has a double scrollbar and is therefore bugy. I have already tried to overwrite the overflow value but without success.

![git_bug_scrollbar](https://user-images.githubusercontent.com/17705248/156003894-230d3ff8-33a7-400b-8ba5-d1197ebba1e4.PNG)

I hope you have a solution for me because thats the only bug preventing me to release the application.
Thanks a lot.

Regards,
Markus Stäudler
DTIT

**Comment by maomaoZH** [comment]
Hi @megahuut 
>  I have already tried to overwrite the overflow value but without success. 

Have you tried to inject your own styles by passing the value to styles props? It looks like:
`<scale-modal styles=":host .modal__window .modal__body-wrapper {overflow-y: /*your value*/}">`

Please let me know if this helps!
Maomao

**Comment by megahuut** [comment]
Hi @maomaoZH 

thanks a lot that helped. I only tried to call the key via stylesheet and only host. I´m no professional dev so yea...;)
But thanks!

Greets Markus
