### ISSUE TITLE
Pass props to `AppLogo` on Footer

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#917]
Hello there,

the `BrandHeader` does have the options to set `href`, `title` and maybe `aria-describedby` for `AppLogo`, will the `footer `get the same features?

**Comment by nowseemee** [comment]
Hello, thanks for bringing this up - yes, we will add these to the Footer as we are already preparing a new version of it.

**Comment by nowseemee** [comment]
Thanks a lot for the PR @christopherGdynia - we just published the changes: `3.0.0-beta.52`. A new Storybook on B&D will follow in 24-48 hours.
