### ISSUE TITLE
`ScaleRadioButtonGroup` contains a `form` element

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#920]
Hello there,

I discovered, the `ScaleRadioButtonGroup` contains a `form` element, is this intended?

I think, it's a mistake.

Quoting [this](https://stackoverflow.com/questions/555928/is-it-valid-to-have-a-html-form-inside-another-html-form) 
> "Every form must be enclosed within a FORM element. There can be several forms in a single document, but the FORM element can't be nested."

**Comment by acstll** [comment]
This is indeed a mistake! Thanks for pointing this out @christopherGdynia 🙏
