### ISSUE TITLE
a11y: Close Flyout Menu on second click of trigger

### ISSUE THREAD

**Issue by filipjnc** [telekom/scale#922]
Currently, subsequent clicks on the trigger button of a Flyout Menu does not do anything.

Since the trigger is not a hover event but a toggle button, it should act like a toggle for good accessibility & ergonomics. Meaning that if the Flyout Menu is currently open, a subsequent click should close the Flyout Menu.

This is less relevant for keyboard navigation, because after opening the Flyout Menu, the focus is trapped in the list. Closing the Flyout Menu then is possible via ESC key - which is ok.

Reproduction possible with the standard docs example:
https://www.brand-design.telekom.com/scale/?path=/docs/components-flyout-menu--standard

**Comment by Tireile** [comment]
@acstll Hello, do you have any updates?

**Comment by acstll** [comment]
@Tireile thanks for the ping, will be working on this this week.

**Comment by acstll** [comment]
Sure, will do!
