### ISSUE TITLE
Modal dialog two scrollbars when scale-checkbox used

### ISSUE THREAD

**Issue by lstraka-telekom** [telekom/scale#935]
Hi 

I have a problem in modal dialog. Everything was working well yet . I use only several `<scale-card>` with some text in dialog, scrollbar come to correct place ...body of dialog was scrollable ....But now I got new feature to place checkbox to the bottom of those cards in dialog and see what happend, There are always 2 scrollbars.
See example here ...

https://codesandbox.io/s/example-scale-angular-0xubn7?file=/src/app/app.component.html

**Comment by megahuut** [comment]
Hi @lstraka-telekom,

I had the same problem and sadly I don´t know the reason for this behave but in the ticket below is my workaround.

See in: https://github.com/telekom/scale/issues/910

Greets Markus
