### ISSUE TITLE
Notifications component - accessibility

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#938]
We got an accessibility issue with the notifications component: The message is not read out to the visually impaired user.
This is not surprising since the component is still in beta status. Issue #932 likely documents the root cause.

We need to tell the auditor by when the problem could be solved. 
Thus, this "issue" is just a question: By when approximately could you provide a solution?

Thank you very much for your help.

**Comment by acstll** [comment]
Thanks for asking @UBOrange! We rather not commit to dates, but I think we can have this next week.

We will test it internally for now. When we do the next accessibility sprint to AA-certify the current beta components we will check again.

**Comment by acstll** [comment]
I'm closing this but labelling it as "question", we can keep in touch right here 🙂
