### ISSUE TITLE
Button missing attributes name and value

### ISSUE THREAD

**Issue by megahuut** [telekom/scale#939]
Hey there,

I´ve got a feature request. Would it be possible to implement the name and value attributes to scale-button? Especially for type submit.

Thanks a lot.

Greets Markus

**Comment by acstll** [comment]
Hey Markus,

I wasn't aware these attributes were part of [the plain old `button` spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-name) 🙃 — thanks for opening this!

Definitely, we will add it.

**Comment by megahuut** [comment]
Hi again,

it seems that it still doesn´t work :(

![git_bug_button](https://user-images.githubusercontent.com/17705248/165511878-a0661817-38bf-4592-b5ef-d1345d9ca4b1.PNG)

**Comment by acstll** [comment]
@megahuut the fix is in `3.0.0-beta.102`, what version are you using?

The betas above "100" are still under the `next` npm dist tag. You have to either include `@next` or the actual version number, while installing or in your package.json:

`npm install @telekom/scale-components@next`

**Comment by megahuut** [comment]
ahh okey thanks. Thought this was already in a stable release. Thx.
