### ISSUE TITLE
Data Grid Tags Cell

### ISSUE THREAD

**Issue by lordichek89** [telekom/scale#955]
Hello all,
can i implement such case now? 
![image](https://user-images.githubusercontent.com/4783247/159734191-c0d9887c-c665-41fd-91cc-9f6ecebf32ba.png)

**Comment by acstll** [comment]
Not really, sorry!

(We're planning some updates for the Data Grid in Q2/Q3, so definitely considering this.)

**Comment by acstll** [comment]
#1076 👀
