### ISSUE TITLE
Attach click event in breadcrumb

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#969]
Hello there,

I have an issue with how the breadcrumb is behaving now: https://github.com/telekom/scale/blob/main/packages/components/src/components/breadcrumb/breadcrumb.tsx

If I provide element with `href` attribute defined, `a` element will be created, and otherwise `span` element is generated.

However I want to be able to have a breadcrumb item that looks like a link but I want to attach custom click event to it, because in our use case we have non URL based navigation in some parts of our application, so just setting `href` doesn't fit my need. 

Also much better solution for URL based navigation would be to attach `[routerLink]='/xyz'` style attribute that would enable Angular just to simulate the navigation, but would not actually trigger page refresh. However `[routerLink]` also gets lost in the generation of `a`/`span` element...

Would it be possible to enhance this so that for example if `click` event is defined for breadcrumb item an element is generated that looks like link but has click event attached? So basically I want to use it like this:
```html
<scale-breadcrumb separator="---">
  <a (click)="navigationService.navigate(1)">{{getItem(1)}}</a>
  <a (click)="navigationService.navigate(2)">{{getItem(2)}}</a>
  <a (click)="navigationService.navigate(3)">{{getItem(3)}}</a>
</scale-breadcrumb>
```

Or is there any workaround possible even with current Scale implementation?

There is one more issue with the code above. Actually if `getItem(2)` dynamically changes value (as in my case) those changes are propagated only the first time. This issue can be solved by using slightly different markup, but it isn't documented anywhere and I would expect it to work anyway. My workaround: 
```
<a (click)="navigationService.navigate(1)" [textContent]="getItem(1)"></a>
```

**Comment by acstll** [comment]
Hey @mato-a, thanks for asking.

If you're not using an URL-based navigation, I wouldn't use `a` tags.

How about you attach a single listener in the `scale-breadcrumb`, so you can use `span`s?

Here's an example (in React) https://github.com/telekom/scale/issues/737#issuecomment-1015446493 — Something like this (illustrative only):

```html
<scale-breadcrumb separator="---" (click)="handleClick($event)">
  <span data-item="1" [textContent]="getItem(1)"></span>
  <span data-item="2" [textContent]="getItem(2)"></span>
  <span data-item="3" [textContent]="getItem(3)"></span>
</scale-breadcrumb>
```

```js
function handleClick(event) {
  const target = // get the target with event.composedPath()
  const item = target.dataset.item // using data-item here but could be anything else you prefer
  navigationService.navigate(item)
}
```

⚠️ Important: https://javascript.info/shadow-dom-events#bubbling-event-composedpath

> Actually if getItem(2) dynamically changes value (as in my case) those changes are propagated only the first time.

this is related to how the component is built (which isn't ideal, but some legacy code we might refactor in the future). So if you're workaround works, I think it's a nice solution you found there 👍 

I hope this helps. Let me know.

**Comment by acstll** [comment]
I forgot about this:

> However I want to be able to have a breadcrumb item that looks like a link

for this we can use some custom CSS, I can help with that too, just let me know!

**Comment by mato-a** [comment]
Hi @acstll ,

Thanks for your help, I was able to find a workaround that works for me. 👍 

I want to use `a` tags because we might add also URL based navigation in the future... it is just a very low prio for us now...

When breadcrumb links are generated only `href` and `textContent` props are transferred it seems, so the solution with `data-item` didn't work for me. I had to resort to parsing the textContent.

To achieve the look of `a` link I've used `href="javascript:void(0)"`

Woraround:

```html
<scale-breadcrumb separator="---" (click)="handleClick($event)">
  <a href="javascript:void(0)" [textContent]="getItemText(1)"></a>
  <a href="javascript:void(0)" [textContent]="getItemText(2)"></a>
  <a href="javascript:void(0)" [textContent]="getItemText(3)"></a>
</scale-breadcrumb>
```

```ts
function handleClick(event) {
  const itemText = (event.composedPath()[0] as HTMLElement).textContent;

  // get navigation item based on textContent
  const item = this.parseItemText(itemText); 

  // could be changed to URL based navigation: `this.router.navigate([...itemPath])`
  this.navigationService.navigate(item); 
}
```

**Comment by acstll** [comment]
> When breadcrumb links are generated only href and textContent props are transferred it seems, so the solution with data-item didn't work for me.

sorry, you're right and I was wrong about `data-` 🙏

> I was able to find a workaround that works for me. 👍

I'm super glad.

(I'm closing this one but as always, feel free to reach out here or elsewhere if needed.)

**Comment by christopherGdynia** [comment]
@mato-a, I have used angular for a project recently and i am noticing that you are calling a function inside in html template in angular.

Isn't this bad for the performance, I have had some bad experiences with it.

I am just curious :D

**Comment by mato-a** [comment]
Hi @christopherGdynia ,

It depends on how complex is the function and how often it gets called... If it's just a simple getter with few conditions that usually doesn't have any perceivable performance penalty... If it is more complex or gets called often then it is generally better to cache it somehow...

The code above was just for demonstration, actually I've used pipe there: `[textContent]="'NAVBAR.SECTION_1' | translate"`

**Comment by christopherGdynia** [comment]
Oh ok, thanks for the info :D
