### ISSUE TITLE
scale-text-field min/max property at type number

### ISSUE THREAD

**Issue by peterszeles** [telekom/scale#971]
Hi there,

I found out that the **`<scale-text-field></scale-text-field>`** component does not support `min` and `max` property at `type=number`. There is only `max-length` and `min-length` props which are only for text input. Is it planned for the future to add `min` and `max` props to this component? Or is it planned to create a new component for numbers like `<scale-input-field>`?
I need something like this: `<scale-text-field type="number" min="1" max="10" step="1"></scale-text-field>`

Thank you :)

**Comment by acstll** [comment]
Thanks @peterszeles for opening this.

We can add the `min` and `max` attributes to `scale-text`, those are certainly missing 👍

**Comment by peterszeles** [comment]
Cool, thank you so much :)
